### ISSUE TITLE
[BUG] - CropImageView.wholeImageRect has comments in wrong place

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [CanHub/Android-Image-Cropper#101]
- Lib Version [e.g. 1.1.0]
2.3.0
 
**Describe the bug**
This:

```kt

    val wholeImageRect: Rect?
        get() {
...
        } // get the points of the crop rectangle adjusted to source bitmap
    // get the rectangle for the points (it may be larger than original if rotation is not straight)
```

**To Reproduce**
1. Go to the source code of it, and look for yourself.

**Expected behavior**
Shouldn't have comments after the "}"

**Screenshots**
Here:
![image](https://user-images.githubusercontent.com/5357526/113038920-be17f200-919f-11eb-9a2b-a28daef4c591.png)

**Smartphone (please complete the following information):**
None.

**Additional context**
Nothing.

**Comment by Canato** [comment]
@AndroidDeveloperLB thanks for pointing!

On one above line we have this check `val bitmap = mBitmap ?: return null` where it can return `null`

For sure this code can get some improvements, please feel free to drop a PR with possible improvements =D

**Comment by AndroidDeveloperLB** [comment]
Sorry you are correct.

**Comment by AndroidDeveloperLB** [comment]
But the comments are in wrong place though

**Comment by Canato** [comment]
> But the comments are in wrong place though

Indeed, there are many comments in strange places or not following the same structure in the whole project.
Already fixed some and planning to fix more, but would be great to find a toll that spot this automatically on the code reviews.

**Comment by AndroidDeveloperLB** [comment]
@Canato Updated the bug report to talk about the comments.
I think this occurred on many places after the conversion, too.

**Comment by Canato** [comment]
> @Canato Updated the bug report to talk about the comments.
> I think this occurred on many places after the conversion, too.

Can open a PR! Let's improve this hahaha, I don't have the time now and on my todo list has other priorities now.
Can check on the Projects tab. 

I will do as soon I can, but you can jump and do earlier =D

**Comment by AndroidDeveloperLB** [comment]
@Canato When you convert to Kotlin, you have to look at the resulting code. This includes comments too, as they can get into a mess (sometimes even get duplicate ones).

**Comment by Canato** [comment]
Thanks @AndroidDeveloperLB for pointing it again. Very useful.
Sorry that this is not on your level of appreciation.

Hope more people can see the good side of it and help instead of just pointing issues.

**Comment by AndroidDeveloperLB** [comment]
@Canato I don't understand. What is " level of appreciation" ? 
I very much like this library. I just meant that it's very important to look at the kotlin code after conversion.
That's it.
I converted a lot of Java code, and I know the annoyances of it, and the bugs it can cause. If a person isn't careful, new bugs can appear.

**Comment by Canato** [comment]
I see, sorry if sounded wrong. I saw you pointing the same case many times "need to pay attention on the convertion"

I totally agree with you, I did the best I could, cause there was a lot and when I review peoples refactor I try to review as much I could to :)

But indeed many to keep going, we will get there

**Comment by AndroidDeveloperLB** [comment]
?
