### ISSUE TITLE
[BUG] - Loading and cropping takes literally minutes to execute

### ISSUE THREAD

**Issue by Moliholy** [CanHub/Android-Image-Cropper#103]
- Lib Version 2.3.0
 
**Describe the bug**
Nothing too complex. It sometimes simply takes a lot of time to load the image and perform the cropping. This doesn't occur every time, but it does from time to time (say 1 out of 3).

**To Reproduce**
1. Select an image from the gallery or take a photo with the camera.
2. With the image's URI, initialize the library through a fragment.
3. Wait for  the image to load.
4. Crop the image.

**Expected behavior**
3 and 4 are supposed to occur reasonably fast, but it takes minutes to load the image and to crop it. Sometimes, after more than 10 minutes, I simply gave up.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [OnePlus 6]
 - OS: [Android 10]

**Additional context**
My device, OnePlus 6, has a pretty good hardware, so I definitely do not think it's a matter of resources.

**Comment by Canato** [comment]
Hey @Moliholy thanks for pointing, not sure what we can do here...

Gonna ask you to help with some tests. Can you `git clone` the library in your local Android Studio and build the `Sample` app we have in the library code?

Then execute this steps:
1. Open the app
1. Select `Sample Calling CropImage` option (third one)
1. Select `Outside Camera and Start(URI)` 
1. Take a picture
1. Accept the picture
1. Clip on crop, top right.

This take longer to process in your `OnePlus 6` ? 
**Please, provide a video, so I can understand better**

Maybe is something device related

**Comment by Moliholy** [comment]
Gonna do that, but in the meantime I'll share what I found out while debugging my app:

It seems when asynchronously executing a coroutine in the `Default` scheduler, it never manages to run a single line of code of that coroutine. I'm constantly using coroutines throughout the app, and it's the very first time I found this issue. I'll keep an eye ono this while executing the tests you mention.

Oh, and thanks a lot for the super quick reply!

**Comment by Canato** [comment]
My pleasure, all this image stuffs need to be done in the main-ui thread.

**Comment by Moliholy** [comment]
I just tried your tests, but there's not much to say: it works like a charm. It might be myself doing something weird in the code. I'll keep researching...

**Comment by Canato** [comment]
I will close this, but if you find something that we could improve or could help other people using the library, please add here =D.

Hopefully the sample code can help you some how.
