### ISSUE TITLE
[BUG] - Not able to access CropImage.activity() function in Java class

### ISSUE THREAD

**Issue by prashant-13** [CanHub/Android-Image-Cropper#108]
- Lib Version [2.3.1]
 
**Not able to call CropImage.activity() fun, it is giving error. As it is not mentioned with  @JvmStatic annotation. Please add  @JvmStatic in fun activity() so that we can use this lib in java project**

**Comment by Canato** [comment]
@prashant-13 can you please open a PR with this changes so I can release fast?

**Comment by mampress** [comment]
Have you fixed it? Thanks in advance

**Comment by Canato** [comment]
@mampress when is fixed and release this issue will be close. Someone need to drop a PR to fix this so we can merge =)

**Comment by mampress** [comment]
Sorry, I'm quite new to GitHub so I don't know how to open one

**Comment by Canato** [comment]
@mampress welcome =D

This is the library [guide to contribute](https://github.com/CanHub/Android-Image-Cropper/blob/main/CONTRIBUTING.md), our "rules". 

[This is a great guide](https://github.com/firstcontributions/first-contributions) explaining how to fork and how to contribute.

Looking forward for your PR soon !!!

**Comment by mampress** [comment]
As soon as I understand what a PR properly I'll commit one =D

**Comment by ashcode1997** [comment]
@mampress how did u reesolved the problem ?

**Comment by mampress** [comment]
> @mampress how did u reesolved the problem ?

haven't resolved it yet

**Comment by Canato** [comment]
@prashant-13 Thanks for the PR!

@ashcode1997 @mampress 
Please check the pre-release `2.3.2-alpha` and let me know on the [discussion #110](https://github.com/CanHub/Android-Image-Cropper/discussions/110) if everything is working

**Comment by mampress** [comment]
CropImage.activity() works perfectly

**Comment by mampress** [comment]
Now Im facing the same problem with CropImage.getActivityResult();

**Comment by ashcode1997** [comment]
@mampress  same here

**Comment by ashcode1997** [comment]
error :- Non static cannot be referenced from static context

**Comment by Canato** [comment]
@NmMedina will work on this #113
