### ISSUE TITLE
Problem Calling CropImage.getActivityResult from Java

### ISSUE THREAD

**Issue by NmMedina** [CanHub/Android-Image-Cropper#113]
Hi there I'm coming from the old repository due I'm having problems with Android 11 when accepting the Photo but when I'm trying to get the result from the activity I can't get the result due it's not static, reviewing the Java version has the static modifier

    @Nullable
    public static ActivityResult getActivityResult(@Nullable Intent data) {
        return data != null ? (ActivityResult) data.getParcelableExtra(CROP_IMAGE_EXTRA_RESULT) : null;
    }

but the kt file doesn't have the @JvmStatic

    /**
     * Get [CropImageActivity] result data object for crop image activity started using [ ][.activity].
     *
     * @param data result data intent as received in onActivityResult(int, int, Intent).
     * @return Crop Image Activity Result object or null if none exists
     */
    // TODO don't return null
    fun getActivityResult(data: Intent?): ActivityResult? =
        data?.getParcelableExtra<Parcelable>(CROP_IMAGE_EXTRA_RESULT) as? ActivityResult?

Is the intended behavior? I cant figure out how to use that method, any advice will be welcome

![image](https://user-images.githubusercontent.com/9562328/114578616-0c6ecb80-9c4b-11eb-82dc-440643a446f6.png)

**Comment by Canato** [comment]
Hello @NmMedina welcome to the lib

Please check this [discussion](https://github.com/CanHub/Android-Image-Cropper/discussions/110) 

We add some `@JvmStatic` but look like we always need more. 
So, before make `n` comments and releases for each method is better we do just one! 

For this we need to add a Java Sample code, to be sure is working. 

Please feel free to add the Java Sample and open a PR for it

**Comment by NmMedina** [comment]
Hi, @Canato Thanks for the fast response! Perfect I going to work on this example and make a PR

**Comment by Canato** [comment]
Let this open, so people know you are working on this! 

Will link with the discussion

**Comment by TacoTheDank** [comment]
Experiencing this as well. Please fix ASAP!

**Comment by junaediwidjojo** [comment]
Hello

I really need help on this, my codes is full on java so need this library working on java too.

What should I do to help you fix this bug?

I still new in PR that you mentioned, trying to push my sample in separate branch but not working.
Attached is my java sample code, hope you can help me to check it.
[Uploading SExtendActivityJava.java.txt…]()


Thank you

**Comment by Canato** [comment]
Hey @junaediwidjojo thanks for being involved =D.

To add a PR you will need to create a fork form the repository and create the PR from your forkRepo to this repo.
On the top right corner of github you can see
![Screenshot 2021-05-05 at 12 33 46](https://user-images.githubusercontent.com/15942449/117134909-26a94e80-ad9e-11eb-81bc-4e8e761faefc.png)

The latest button is the one you wanna.

Later you will be able to open a PR like this:
![Screenshot 2021-05-05 at 12 36 41](https://user-images.githubusercontent.com/15942449/117135256-97e90180-ad9e-11eb-9c28-a9c8c57b42f5.png)

As well, please take a read in the [CONTRIBUTING GUIDE](https://github.com/CanHub/Android-Image-Cropper/blob/main/CONTRIBUTING.md)

For this work we need some stuffs:
1. Java sample code using all methods, like we have in kotlin
1. Add `@JVMStatic` where need

**Comment by andre719mv** [comment]
CropImage.getPickImageChooserIntent also can`t be called from Java

**Comment by Canato** [comment]
> CropImage.getPickImageChooserIntent, getPickImageResultUri also can`t be called from Java

please open a PR or issue for this.
