### ISSUE TITLE
[BUG] - width must be > 0

### ISSUE THREAD

**Issue by hassanargon** [CanHub/Android-Image-Cropper#115]
- Lib Version 2.3.1
 
**Describe the bug**
When I crop multiple images then my app crash and this error shows in Logcat
`java.lang.IllegalArgumentException: width must be > 0`

**Code**

>  for (int i = 0; i < cropImageViews.size(); i++) {
>                     Bitmap bitmap = cropImageViews.get(i).getCroppedImage();
>                     setUri(bitmap);
>                 }

I know I am doing something wrong but please guide me on this.

**Comment by Canato** [comment]
Hey @hassanargon this one will be trick to debug hahaha

So you said you can crop some images, but when you do with a lot of images in sequence it break, right?

Do you know how many images? like after 5 or 10? 
This maybe be a concurrency issue where `cropImageViews.get(i)` **return an empty image**.

Maybe we can add some Logs/debug to be sure that all images exists?.
Or even an IF condition, like: 
```
for (int i = 0; i < cropImageViews.size(); i++) {
    temp = cropImageViews.get(i)
    If(temp != null) {
        Log.v("HERE", temp);
        Bitmap bitmap = cropImageViews.get(i).getCroppedImage();
        setUri(bitmap);
    } else {
        Log.v("HERE", "null temp");
    }
}
```

**Comment by hassanargon** [comment]
@Canato I am adding a maximum of ten images into the List and then want to get all cropped Images. And I also debug the code, all Crop image views have the image. And it is crashing on the second iteration, which means when `i=1` then it crashes.

**Comment by Canato** [comment]
@hassanargon your layout has 10 `CropImageView` and they user is cropping in each one of them ?

Maybe would be value if you can provide me some project that I can run and take a look.
Please fork this library and add your code to the project sample we have here. 

Sorry, hard for me to have the vision about what is going on =/
