### ISSUE TITLE
Non-static 'getActivityResult(android.content.Intent)' cannot be referenced from a static context

### ISSUE THREAD

**Issue by appsapiconsole** [CanHub/Android-Image-Cropper#123]
- Lib Version 3.0.1
 
**Describe the bug**
Non-static 'getActivityResult(android.content.Intent)' cannot be referenced from a static context

![image](https://user-images.githubusercontent.com/56867915/116654588-e1061380-a9a2-11eb-8fc9-668a5dd4f668.png)

**Comment by Canato** [comment]
Hey @appsapiconsole this is something was reported here: https://github.com/CanHub/Android-Image-Cropper/issues/113

To really solve this problem we need a java sample code and to add `@Jvmstatic` to the methods. @NmMedina was taking a look on this, but please open the PR if you know what to do =D
