### ISSUE TITLE
[BUG] - should isReadExternalStoragePermissionsRequired be marked @JvmStatic

### ISSUE THREAD

**Issue by gwharvey** [CanHub/Android-Image-Cropper#129]
- Lib Version [e.g. 1.1.0] 3.1.0
 
**Describe the bug**
When porting to 3.1.0 from 2.2.2, I found that I could no longer access isReadExternalStoragePermissionsRequired.  I believe this should be a static function.  Can you please add usage of this function to the sample code?

**To Reproduce**
1. Add the following code to your Java project "if (CropImage.isReadExternalStoragePermissionsRequired(getContext(), imageUri))"
2. Rebuild using 3.1.0
3. See compile error

**Expected behavior**
Should compile correctly or have a sample which shows to new usage.

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11

**Additional context**
Building using Android Studio 4.2.0

**Comment by Canato** [comment]
Hey @gwharvey thanks for the detailed issue. 

Look like we have more java issues cases with
> CropImage.getPickImageChooserIntent, getPickImageResultUri also can`t be called from Java

Would you mind opening a PR with all this changes? Ideally with the sample + fix, I'm not anymore a java user so I feel safer when someone who knows what is doing and can test could put the hands on.
