### ISSUE TITLE
[BUG] - Wiki Docs need update

### ISSUE THREAD

**Issue by Morons** [CanHub/Android-Image-Cropper#134]
[Limit cropped image result min max size](https://github.com/CanHub/Android-Image-Cropper/wiki/Limit-cropped-image-result-min-max-size)
still refer to `com.theartofdev.edmodo.cropper.CropImageView`
rather than `com.canhub.cropper.CropImageView`
I am sure more changes lik this is nessesary!

**Comment by Canato** [comment]
Thanks @Morons was a lot of documentation and code to learn and import in the transition. Indeed we still find some bits to fix!

Already fix this one, feel free to keep pointing when you find =D
We are always improving.
