### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by MdFarhanRaja** [CanHub/Android-Image-Cropper#135]
- Lib Version [3.1.1]
 
**Describe the bug**
/data/user/0/com.kw.wanderer/cache/temp_file_20210531_192600.
Not getting file extension below Android 10

**Comment by Canato** [comment]
Hey @MdFarhanRaja thanks for the report I could not reproduce.

Could you please:
- Add a title, like `missing extension on path`
- Give some steps to reproduce? (which device?, which method are you using to get this, which flow of the crop image are you using) 
- If possible to give a code that will break using a emulator so I can reproduce and debug
**OR**
Feel free to drop a PR fixing the issue
