### ISSUE TITLE
[BUG] - ContextThemeWrapper cannot be cast to FragmentActivity while setImageUriAsync

### ISSUE THREAD

**Issue by WMariusz** [CanHub/Android-Image-Cropper#136]
- Lib Version 3.1.1
 
**Describe the bug**
`CropImageView.setImageUriAsync` leads to 
`android.view.ContextThemeWrapper cannot be cast to androidx.fragment.app.FragmentActivity` 
when `CropImageView` is nested inside view that have overrided `android:theme` atribute

**To Reproduce**
1. Set image uri on `CropImageView` with `setImageUriAsync`
2. Apply `ThemeOverlay` by add it to view layout `android:theme`
3. See error

**Expected behavior**
Try to unpack `FragmentActivity` from `ContextThemeWrapper`

**Additional context**
See https://github.com/WMariusz/Android-Image-Cropper/tree/bug/theme-overlay-context-wrapper
i have added two commits, first with bug and second with workaround that issue

**Comment by Canato** [comment]
Thanks for the detailed bug description and the commits.

Indeed we cannot expect that context will have/be a fragmentActivity and was a mistake that I didn't spot before.

Would you like to open a PR for the library with the fix issue? I'm just worry about the `while` inside `getFragmentActivityFrom`, maybe we could get block in a loop here forever?


But if you open the PR with the fix and updating the changelog we can merge and release =)

**Comment by WMariusz** [comment]
IMO this loop should not block app as long as view is created with activity context.

So you would have to create a view from some `Service` or other `Activity`, for example from `NativeActivity` to block it.

Right now i cant find better solution.
