### ISSUE TITLE
Not Working on Android 10 or Above [BUG] - 

### ISSUE THREAD

**Issue by junaidandroidcp** [CanHub/Android-Image-Cropper#137]
- Lib Version [e.g. 1.1.0]
 
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3XL]

**Additional context**

**Comment by Canato** [comment]
> * Lib Version [e.g. 1.1.0]
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. Pixel 3XL]
> * OS: [e.g. iOS8.1]
> 
> **Additional context**
> Add any other context about the problem here.

no content, please add some information for reproduce
