### ISSUE TITLE
Missing extension on path below Android 10

### ISSUE THREAD

**Issue by MdFarhanRaja** [CanHub/Android-Image-Cropper#138]
- Lib Version 3.1.1

On Button Click

        CropImage.activity()
            .setGuidelines(CropImageView.Guidelines.ON)
            .setFixAspectRatio(true)
            .setCropShape(cropShape)
            .setOutputCompressQuality(50)
            .setOutputCompressFormat(Bitmap.CompressFormat.JPEG)
            .setAspectRatio(1, 1)
            .start(activity)

onActivityResult

        val result: CropImage.ActivityResult = CropImage.getActivityResult(data)!!
        val resultUri: Uri? = result?.uriContent
        val resultFilePath: String? = result?.getUriFilePath(mContext, true)
        val file = File(resultFilePath)

File absolute path
/data/user/0/com.kw.wanderer/cache/temp_file_20210531_192600.

Not getting file extension on below all android 10 devices.

**Comment by Canato** [comment]
Could reproduce, will check during the week.

Thanks!

**Comment by Canato** [comment]
Ok. already did the fix, was easier than I expected, still need to run some tests before merge, so will hold until Monday
