### ISSUE TITLE
[BUG] - ExifInterface.ORIENTATION_TRANSVERSE as returned by CameraX not correctly handled

### ISSUE THREAD

**Issue by sameerjj** [CanHub/Android-Image-Cropper#144]
- Lib Version 3.1.0
 
**Describe the bug**
If an image is passed into the cropper with EXIF orientation data outside of 0,90,180,270, the cropper displays the incorrect orientation of the image.

More specifically, image with EXIF data ORIENTATION_TRANSVERSE is not rotated or displayed correctly

**To Reproduce**
- Capture an image using CameraX and use the selfie camera (`CameraSelector.DEFAULT_FRONT_CAMERA`) while device is in portrait mode
- Pass the image into the cropper using `cropperView.setImageUriAsync(uri)`
- Observe that the orientation of the image is not correct and displayed in landscape mode, requiring 270degrees clockwise rotation to be displayed correctly.

**Expected behavior**
- Image to display in portrait mode as captured

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 11

**Comment by Canato** [comment]
Morning @sameerjj 

Thanks for the detailed explanation. 

- Could you provide a video?
- And can you share how are you using the library in your code? can be some copy/paste from your project

**Comment by nejcburic** [comment]
I have same issue using Pixel 5. Is there a solution provided? @Canato

**Comment by Canato** [comment]
@nejcburic not yet, I could not reproduce. I asked some questions but was ghosted. Happy to follow this if I can understand better what is going on. Suggest to open a new issue with all information need =D
