### ISSUE TITLE
Implementation Error

### ISSUE THREAD

**Issue by Rizza-Rabe** [CanHub/Android-Image-Cropper#146]
- Lib Version 3.1.3
 
Android Studio Throws error:
"Fail to resolve: com.github.CanHub:Android-Image-Cropper:3.1.3"
![16244455235292139217008406975166](https://user-images.githubusercontent.com/72380210/123084792-218a8680-d454-11eb-92a1-274f9503629b.jpg)

**Comment by Canato** [comment]
Hello @Rizza-Rabe welcome to the library.

Did you have `maven -  jitpack` add to your project?

**Tip:**
Next time you can always add a printscreen or just copy/paste the code =)

**Comment by Rizza-Rabe** [comment]
Yes i have jitpack.io
like this
repo{
mavenCentral()
maven {url https://jitpack.io} like this.
}

**Comment by Canato** [comment]
which gradle file is each one of this code?

**Comment by Rizza-Rabe** [comment]
Tried the outside Gradle. not work. And in inside gradle not work either.

**Comment by Canato** [comment]
ok, need to be in the gradle file. But your project should have at least two gradle files or more.

Which is the package/path to the gradle files you are using?

jitpack need to be in root gradle file
and the library implementation need to be on the module gradle file

**Comment by denchic45** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/80104523/123218003-de6ff800-d4d3-11eb-88fd-4c6bf906d44a.png)
![image](https://user-images.githubusercontent.com/80104523/123218062-edef4100-d4d3-11eb-9a4d-36eada54c99a.png)

**Comment by Canato** [comment]
Hey @denchic45 same questions, which gradle files are you putting this code? 

There is this warning about offline, probably is nothing

**Comment by denchic45** [comment]
I put this code in a Gradle project
![image](https://user-images.githubusercontent.com/80104523/123230693-2e54bc00-d4e0-11eb-99ec-7e388953e0f8.png)

I put the dependency in the gradle of the app module
![image](https://user-images.githubusercontent.com/80104523/123230951-6b20b300-d4e0-11eb-8017-9f0e933a5046.png)

After synchronizing it, I receive these messages:
![image](https://user-images.githubusercontent.com/80104523/123231123-95727080-d4e0-11eb-84fb-ad84675e391b.png)

**Comment by Canato** [comment]
Could you try an old version like `3.1.0` and see if is the same issue?

**Comment by Rizza-Rabe** [comment]
It also gives an error in all versions.

**Comment by Canato** [comment]
Could you change the order to
```
mavenCentral()
maven { url 'https://jitpack.io'}
```

**Comment by denchic45** [comment]
Same result :(

**Comment by Canato** [comment]
Wanna help you people, but no idea what could be =/ Jitpack look up and running, we didn't had this issue before.

Please let me know if you find a solution or what the problem is ><'

**Comment by denchic45** [comment]
I will still experiment with this :) And so the problem is strange, I already had Jitpack earlier for other libraries

**Comment by connyduck** [comment]
It says you should `Disable offline mode and sync project`, have you tried that?

**Comment by lightstudioapp** [comment]
You need to enable gradle online mode and connect your pc/laptop to internet.

**Comment by denchic45** [comment]
Yes, I tried it first, but it didn't help

**Comment by Canato** [comment]
@Rizza-Rabe I can see that you are using the library, how did you fix this?

**Comment by Canato** [comment]
The owner of the issue have the library already working. Hopefully will share with us =D

**Comment by zihadrizkyef** [comment]
it also occured to me. i've tried many version but gradle still cannot found it. what's wrong?

**Comment by hueimin426** [comment]
I got this error as well. May I know how to solve this?
