### ISSUE TITLE
[Feat] - Add a custom UI

### ISSUE THREAD

**Issue by ashcode1997** [CanHub/Android-Image-Cropper#148]
Currently we have the crop icon on the action bar , so I want a customization that the crop button should be below the crop preview . In short I want to hide the action bar icons and want a separate button for crop .

**Comment by Canato** [comment]
@ashcode1997 maybe you can create your own layout using `cropImageView` like we have on the [sample code here](https://github.com/CanHub/Android-Image-Cropper/blob/main/sample/src/main/java/com/canhub/cropper/sample/crop_image_view/app/SCropImageViewFragment.kt)

Basically you put the image and button where you want, and on the button click you call:
`cropImageView.getCroppedImageAsync()` 

On the sample code above this is on the toolbar, but you can put anywhere.

would this solve your issue?
