### ISSUE TITLE
Uri error

### ISSUE THREAD

**Issue by Rizza-Rabe** [CanHub/Android-Image-Cropper#151]
Image taken directly from camera throws Error when using Cursor to extract real image path.
`CropImag.ActivityResult result = CropImage.getActivityResult(data)`

`result.getOriginalUri`

and error occured here:
`Cursor cursor = getContentResolver().query(image_uri, null, null, null, null);`
`cursor.moveToFirst();
int idx = cursor.getColumnIndex(MediaStore.Images.ImageColumn.DATA);

//Throws an error here
String real_path = cursor.getString(idx);
cursor.close();
`

**Comment by Canato** [comment]
> Hey! If possible explain on #146 how did you fix the library import

Is kind of hard to read this issue, could you please follow the issue format:
>  - Lib Version [e.g. 1.1.0]
>  
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Smartphone (please complete the following information):**
>  - Device: [e.g. Pixel 3XL]
>  - OS: [e.g. iOS8.1]
> 
> **Additional context**
> Add any other context about the problem here.

**Comment by Rizza-Rabe** [comment]
Ok. So I think the cropped image path is not working. When I pass it to File and try to get its size it shows 0B. Even firebase throws error when uri came from (result.getUriContent) but was normally working on (result.getUriOriginal) wich is the orginal path of the image.

**Comment by Canato** [comment]
`result.getUriContent` is not the file path, is the uri content. you need to use `result.getUriFilePath` to get the `file://` schema

**Comment by Rizza-Rabe** [comment]
you mean the `result.getUriContent.getPath`?

**Comment by Rizza-Rabe** [comment]
Ye I see now. Thanks. Btw what is the use of UniqueName?

**Comment by Canato** [comment]
This is the documentation:
> * @param uniqueName If true, make each image cropped have a different file name, this could
> * cause memory issues, use wisely. [Default: false]

If not easy to understand let me know so we can improve the text =D

But this is important if you are making multiple crops in sequence
