### ISSUE TITLE
[BUG] - Issue in Android 11 Closing after it opened 

### ISSUE THREAD

**Issue by balaji-roamsoft** [CanHub/Android-Image-Cropper#153]
- Lib Version [e.g. 3.1.3]
 
**Describe the bug**
`System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference`
when i call 
```
CropImage.activity(imgUri)
    .setAllowRotation(true)
    .setOutputCompressQuality(60)
    .setOutputCompressFormat(Bitmap.CompressFormat.JPEG)
    .setGuidelines(CropImageView.Guidelines.ON).start(context);
```
crop screen opened and closes immediately
```
CropImage.ActivityResult result = CropImage.getActivityResult(data);
File file = new File(getUriPath(context, result.getUriContent()));
```
gettling null in `result.getUriContent()`

**To Reproduce**
Working fine on upto android 10

**Expected behavior**
It should open to crop screen

**Screenshots**

**Smartphone (please complete the following information):**
  Pixel- 4 

**Additional context**

**Comment by Canato** [comment]
Hey @balaji-roamsoft could you print the value of `imgUri` before call the library? 

What is the value?

**Comment by balaji-roamsoft** [comment]
content://com.ippopay.agent.fileprovider/storage%2Femulated%2F0/IppoPay%20Agent/Snap_1625131382.jpg

**Comment by balaji-roamsoft** [comment]
I'm Getting this problem on Android 11 below that working fine

**Comment by Canato** [comment]
@balaji-roamsoft will try to reproduce after work, just to be sure, could you run the sample app in this library and check if we have the same issue?

If possible send me a video of the open/close behaviour using the sample app

**Comment by balaji-roamsoft** [comment]
Sample app works fine. i'll check and update

**Comment by Canato** [comment]
@balaji-roamsoft maybe was something small or not, but could you share what happened so I can help more people in future?
