### ISSUE TITLE
[BUG] - Android 11 issues

### ISSUE THREAD

**Issue by RK03ind** [CanHub/Android-Image-Cropper#155]
Getting this error while converting result uri to bitmap
Anything with android file provider ??
E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /my_images/Pictures/cropped1275987617537390602.jpg: open failed: ENOENT (No such file or directory)

**Comment by Canato** [comment]
Hey @RK03ind good day, welcome to the community, I will ask you to **please follow the repository template for bugs.**
`new issue > Bug report` 

Will close this issue so we can open with more information.

When adding the information please show the code you are using and/or the test/bug in the sample code from the library
