### ISSUE TITLE
Show crop icon at toolbar of CropActivity

### ISSUE THREAD

**Issue by hardapps1692** [CanHub/Android-Image-Cropper#156]
This is fabulous cropping library ever I seen. But I want to show a crop shape icon at top of the toolbar of Cropactivity. Please assist with it.

**Comment by Canato** [comment]
Hey @hardapps1692 will make this a discussion =D

We have some options for customisation, you can change the icon on our activity extending our!

For this you can check [this code](https://github.com/CanHub/Android-Image-Cropper/blob/main/sample/src/main/java/com/canhub/cropper/sample/extend_activity/app/SExtendActivity.kt)

So basically you can add your toolbar and call our methods, so you just need to create your screen. 

[This is the sample layout for extend activity](https://github.com/CanHub/Android-Image-Cropper/blob/main/sample/src/main/res/layout/extended_activity.xml) 

You can make `saveBtn` a `ImageView` and add the icon. 

Can check more stuff in the [Wiki](https://github.com/CanHub/Android-Image-Cropper/wiki). Some stuff are outdate, sorry =/. But the code sample is working.
