### ISSUE TITLE
[BUG] - Camera Issue

### ISSUE THREAD

**Issue by sdlingam7** [CanHub/Android-Image-Cropper#158]
```
   ActivityResultLauncher<CropImageContractOptions> pickImageResult =
            registerForActivityResult(new CropImageContract(), (result) -> {
                if (result.isSuccessful()) {
                    picturePath = result.getUriFilePath(getContext(), true);
                    Picasso.get().load(new File(picturePath)).fit().into(img_User_Image);
                    getRetro_UpdateProfilePic(picturePath);
                }
            });

    public void pickImage() {
        pickImageResult.launch(new CropImageContractOptions(imageUri, new CropImageOptions())
                .setGuidelines(CropImageView.Guidelines.ON));
    }
```

This is my code. While i pick image from gallery, it's working fine. But while capture image from camera, it does not goes to crop activity, show error  CropImage.CancelledResult.INSTANCE .  

**Check this code in android 11, i have tried in vivo and oneplus device, both are android 11.** 

Thanks

**Comment by Canato** [comment]
Hey @sdlingam7  good day, welcome to the community, I will ask you to please follow the repository template for bugs.
`new issue > Bug report`

Will close this issue so we can open with more information. 
(lib version, tested on sample code, detailed steps to reproduce, screenshot/video) 

Maybe this is a device/OS versions issue, please try to use the sample in this library to be sure.
