### ISSUE TITLE
[Feat] - Pinch to zoom

### ISSUE THREAD

**Issue by mnayef95impressions** [CanHub/Android-Image-Cropper#159]
**Is your feature request related to a problem? Please describe.**
Currently, there is only auto-zoom while cropping but it's will be nice to have the pinch to zoom feature.

**Describe the solution you'd like**
Adding a pinch to zoom

**Comment by Canato** [comment]
Hey @mnayef95impressions  welcome and thanks for the suggestion.

Would be a lovely feat, if you feel please drop a PR with the code for it =D

I will tag with `help wanted` and `good first issue` maybe someone in the community will do it!

If no one take ownership of this feature in the next two weeks the stale robot will stale and later close.
If you want to keep this open just keep updating the progress of the feature ^^
