### ISSUE TITLE
[BUG] - Camera crop image activity is not removed

### ISSUE THREAD

**Issue by sapsalgea** [CanHub/Android-Image-Cropper#162]
- Lib Version: 3.2.1

[youtube video](https://www.youtube.com/watch?v=ODZDNa7Gkr4)

## Steps to reproduce the behaviour:

1. Open Camera
2. Capture a Image
1. Crop a image 
1. Open crop selector again
1. Don't select any image
1. return

Cropping photos from the gallery will not result in this. 
this bug appears when after cropping with the camera .

After cropping with the camera, if you do not select an image from the gallery, the camera image result will continue to appear.

### Actual Behaviour:
You can see your first cropped image

### Expected behaviour:
You should close crop activity because you don't have a image selected

**Comment by Canato** [comment]
Interesting bug, never got in his case, but I know why this happen, we use the same file name to save cache memory of the device, so we don't create an image copy for every crop done.

Not an urgent bug, but for sure something would be nice to fix.

The fix will be something like this: (If someone has more time before myself)
- After crop pressed, clean original URL parameter

**Comment by ibdman1991** [comment]
Please, how to clean original URL parameter ?

**Comment by Canato** [comment]
> @Canato  Please, how to clean original URL parameter ?

Not sure if this is possible. Need to check if original url is accessible (not on my computer today) we probably need a PR to improve this

**Comment by Canato** [comment]
Just check the code and we can't need some PR to improve it. Please feel free to drop a PR with a fix and we can discuss =D
