### ISSUE TITLE
[BUG] - the image is not saved after cropping.

### ISSUE THREAD

**Issue by inforaamitsolutions** [CanHub/Android-Image-Cropper#163]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version [e.g. 1.1.0]
 
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Media**
Please add screenshots and/or screen recordings to help explain your problem.
We cannot help without more information

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3XL]

**Additional context**

**Comment by Canato** [comment]
Please use the template with correct information. Deleting what is need just comments. Thanks
