### ISSUE TITLE
Android version 9  image path generated without image extension[BUG] - 

### ISSUE THREAD

**Issue by Jaaveethoptisol** [CanHub/Android-Image-Cropper#168]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version [e.g 3.1.1]
 
**Describe the bug**
Image path not getting properly

**To Reproduce**
Check with Android version 9

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. All Version 9 devices]
 - OS: [e.g. Android Version 9]

**Additional context**
Am using the image crop library with my application for the android version 9 image path is generated without image extension

Kindly help me to sort this issue.

**Comment by Canato** [comment]
@Jaaveethoptisol Good day =D
Some requests so I can help you better

1. Please update your library to the latest version 
2. Please fill the form/template and delete the placeholders
3. Could you reproduce this bug in the sample code? 

Thanks!

**Comment by Canato** [comment]
This was fixed in `3.1.2`

https://github.com/CanHub/Android-Image-Cropper/releases/tag/3.1.2
