### ISSUE TITLE
Implementation using java, with alternative for  deprecated onActivityResult()

### ISSUE THREAD

**Issue by jesulonimii** [CanHub/Android-Image-Cropper#169]
Please can we have a guide for implementing your library using java?

**Comment by Canato** [comment]
@jesulonimii please feel free to create one. I'm not a Java user, but the community can contribute

We have a sample code using the library: https://github.com/CanHub/Android-Image-Cropper/tree/main/sample/src/main/java/com/canhub/cropper/sample/crop_image_java

**Comment by Canato** [comment]
This is not an issue, will move to discussion
