### ISSUE TITLE
[BUG - Question Maybe] - Toolbar is missing

### ISSUE THREAD

**Issue by TurKurT656** [CanHub/Android-Image-Cropper#176]
**Library version**
 - 3.2.2
 
**Describe the bug**
When Crop Screen shows up, toolbar is missing and only the picked photo with copper guidelines are available on the screen.

**To Reproduce**
1. launch the Copper with:
`
cropImage.launch(
            options {
                setGuidelines(CropImageView.Guidelines.ON)
            }
        )
`
2. Select a photo or take a picture.
3. Touch the checkmark
4. See the crop screen without toolbar

**Expected behavior**
A Toolbar is needed (with rotate and crop buttons)

**Media**
![Screenshot_2021-08-09-17](https://user-images.githubusercontent.com/7152030/128729243-7f8c072c-c4fb-438e-9211-3cb02d0a737e.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. realme 7]
 - OS: [e.g. Android 11]

**Additional context**
I'm not sure if this is an expected behavior or a bug.

**Comment by Canato** [comment]
Hey @TurKurT656 welcome to the lib =D

Do you theme has not action bar? We have this note, maybe help you
```xml
<activity android:name="com.canhub.cropper.CropImageActivity"
  android:theme="@style/Base.Theme.AppCompat"/> <!-- optional (needed if default theme has no action bar) -->
```

Please let me know if work or not

**Comment by TurKurT656** [comment]
Sorry my bad. My app was on previous version of Android Image Cropper and because of that I forgot to change the package name to the new one in the manifest. works like a charm :)

**Comment by SantuBasakDev** [comment]
> Hey @TurKurT656 welcome to the lib =D
> 
> Do you theme has no action bar? We have this note, maybe help you.
> 
> Add on your manifest:
> 
> ```
> <activity android:name="com.canhub.cropper.CropImageActivity"
>   android:theme="@style/Base.Theme.AppCompat"/> 
> ```
> 
> Please let me know if work or not

It's working.
