### ISSUE TITLE
[BUG] - In low budget devices, camera is unable to deliver the result

### ISSUE THREAD

**Issue by yajnesh** [CanHub/Android-Image-Cropper#181]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code
Yes Reproducible in sample code

 - Lib Version
 com.github.CanHub:Android-Image-Cropper:3.2.1
 
**Describe the bug**
In low budget devices like "Xiaomi Remi 8A dual", If the image is clicked via camera option, ```com.canhub.cropper.CropImageContract.parseResult``` , the ```result``` variable is always null.

**To Reproduce**
1. Choose camera option while choosing image

**Smartphone**
 - Device: Xiaomi Remi 8A dual
 - OS: Android 10

**Comment by Canato** [comment]
Hey @yajnesh thanks for raising this, without reproduce is hard for me to fix, but feel free to drop a PR. I will be looking close to #180 hopefully is the same bug and we can fix in one go? 🤔

**Comment by Canato** [comment]
@yajnesh I found the bug in the other ticket, but maybe is not related to this one. Could you share a video of it not working on the sample code? 

Maybe we are limited by the device =/// if so, we could think about how to compress the image
