### ISSUE TITLE
[Feat] - Separate Exception class or return code 

### ISSUE THREAD

**Issue by dhoehl** [CanHub/Android-Image-Cropper#186]
Maybe this is already implemented somehow and I did not find it but:

Wouldn't it be nice to return a custom Exception with an error code instead of a generic exception?

My current use case: If the user presses the back button I do not want to display an error message, if it fails of other reasons I might. I don't see how to achieve this besides comparing the error message atm but this is highly risky to do and will most likely break in future updates.

**Comment by Canato** [comment]
Hey @dhoehl welcome =D.

Thanks for the suggestions, indeed is a nice feature! 

Please feel free to open a PR with better exceptions, for sure will be a win for the whole community

**Comment by dhoehl** [comment]
Sadly I am not familiar with Kotlin. So just in case someone wants to take over this, I would be really happy. Does not sound like a huge task, but I cannot be of any help here

**Comment by Canato** [comment]
I add the labels so people can jump in. But if you know Kotlin is close enough and I will check the PR to help you. Maybe is a good first kotlin experience hahahaha
