### ISSUE TITLE
Unresolved reference: registerForActivityResult migrating from ArthurHub/Android-Image-Cropper

### ISSUE THREAD

**Issue by oscarabilleira** [CanHub/Android-Image-Cropper#188]
Anyone has this problem?

I followed the instructions to migrate from ArthurHub/Android-Image-Cropper (where with android 11+ camera si not working) using the wiki: https://github.com/CanHub/Android-Image-Cropper/wiki/🚨-How-to-migrate-Android-Image-Cropper--🚨
but when I try to add this code returns "Unresolved reference: registerForActivityResult”... I try in a lot of diferent versions but no way... allways the same error.

The code is posted here https://github.com/CanHub/Android-Image-Cropper/wiki/Pick-image-for-cropping-from-Camera-or-Gallery
```

private val pickImageCustom =
       registerForActivityResult(
           object : PickImageContract() {
               override fun parseResult(resultCode: Int, intent: Intent?): Uri? {
                   if (intent != null) {
                       context?.let {
                           context = null
                           return CropImage.getPickImageResultUriFilePath(it, intent).toUri()
                       }
                   }
                   context = null
                   return null
               }
           }
       )

```

**Comment by Canato** [comment]
Welcome to the lib @oscarabilleira =D

`registerForActivityResult` is not part of this library. Is a Android library, you can see here: https://developer.android.com/training/basics/intents/result

You probably need to update your other main libraries, like `appcompat`,  `androidx.activity` and `androidx.fragment` 

will close since is outside of the scope of this repo ^^, if any question ask me =)

**Comment by oscarabilleira** [comment]
Yes that was exactly the problem.. thanks a lot.

**Comment by shero333** [comment]
Facing same issue with graded libraries! Does anyone know this issue?

**Comment by shero333** [comment]
@oscarabilleira facing same issue with upgraded latest libraries of appcompat! but still the issue occurs! any hook on it?
