### ISSUE TITLE
Hello please java code provide

### ISSUE THREAD

**Issue by krishna2917** [CanHub/Android-Image-Cropper#192]
Hello please java code provide

**Comment by Canato** [comment]
Hello @krishna2917 there is a Java sample in the `sample/` folder, please check it.

If you need more information feel free to open a PR with more Java code that we can add in the library

**Comment by Canato** [comment]
Closing this, cause is not an issue, if someone think this should be open please comment here and I will reopen

(I'm on holidays until next week, may take more time to answer)
