### ISSUE TITLE
[BUG] - Non-static 'startPickImageActivity(android.app.Activity)' cannot be referenced from a static context

### ISSUE THREAD

**Issue by krishna2917** [CanHub/Android-Image-Cropper#193]
Non-static 'startPickImageActivity(android.app.Activity)' cannot be referenced from a static context

**Comment by krishna2917** [comment]
CropImage.startPickImageActivity(QrScan.this);  error red line show

**Comment by krishna2917** [comment]
2. problem -    Uri imageuri = CropImage.getPickImageResultUri(this, data);  "error red line show"
3. problem -      assert resul != null;
                        Uri imgPath = resul.getUri();  "error red line show"

**Comment by Canato** [comment]
Will close this now, please open the issue with the right template complete.

`New issue > bug`
