### ISSUE TITLE
[Feat] - 

### ISSUE THREAD

**Issue by krishna2917** [CanHub/Android-Image-Cropper#194]
1. CropImage.startPickImageActivity(QrScan.this);   "error red line show"

2. problem - Uri imageuri = CropImage.getPickImageResultUri(this, data);   "error red line show"

3. problem - assert resul != null;
    Uri imgPath = resul.getUri();   "error red line show"

**Comment by Canato** [comment]
Helloo =D. Like I said in the other issue, please follow the repository template for issues
