### ISSUE TITLE
[BUG] -  problem - Uri imageuri = CropImage.getPickImageResultUri(this, data);   "error red line show"

### ISSUE THREAD

**Issue by krishna2917** [CanHub/Android-Image-Cropper#195]
1. problem  - CropImage.startPickImageActivity(QrScan.this);   "error red line show"

2. problem - Uri imageuri = CropImage.getPickImageResultUri(this, data);   "error red line show"

3. problem - assert resul != null;
    Uri imgPath = resul.getUri();   "error red line show"

**Comment by Canato** [comment]
Hello @krishna2917 welcome to the library. 

To help you I will need to ask some questions. 
To make this easy please follow the template provide when you create a issue
`New issue > Bug`

Will close this now because is not following the repository template.
