### ISSUE TITLE
[BUG] - Cropper doesn't open in android 11 MIUI 12.0.1

### ISSUE THREAD

**Issue by ankiitdev** [CanHub/Android-Image-Cropper#198]
As soon as I click on the image from Gallery or Camera, instead of showing the cropper the activity finishes up. In the sample code it shows a message "cropping image was cancelled by the user".
In the sample code it works in one case when I'm chosing "Outside Camera and Start(Uri)" option but then we only have the option of using phone's camera not gallery

**Comment by Canato** [comment]
Hello @ankiitdev welcome to the library. To help you I will need to ask some questions. To make this easy please follow the template provide when you create a issue
`New issue > Bug`

Will close this now because is not following the repository template.
