### ISSUE TITLE
[BUG] - Doesn't set the right initial crop window rectangle on some images

### ISSUE THREAD

**Issue by James471** [CanHub/Android-Image-Cropper#203]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version [e.g. 1.1.0]
 
**Describe the bug**
`setInitialCropWindowRectangle()` sets the rectangle at a different position than intended

**To Reproduce**
1. Set a debug break point at line 30 in SMainActivity.kt in the sample app
2. Open the sample app in PR
3. Click on 'reproduce bug' button 
4. Click on 'crop'
5. See the value of `rect` in android studio debugger.

**Expected behavior**
Value of `rect` should have been equal to `croppingRectangle` but it isn't.

**Media**
Refer to the sample app

**Smartphone (please complete the following information):**
 - Device: Vivo 1820
 - OS: 8.1.0

**Additional context**
-

**Comment by Canato** [comment]
@James471  please check the PR comment

**Comment by James471** [comment]
Thanks for looking into this. I am traveling, I will check it out as soon as I get a chance.

**Comment by Canato** [comment]
More on #204
