### ISSUE TITLE
[BUG] - Not working in android 11

### ISSUE THREAD

**Issue by ankitpipada** [CanHub/Android-Image-Cropper#206]
Not working in android 11 got Unknown bits set in runtime_flags: 0x800000 error hello team pls update

**Comment by Canato** [comment]
Hello @ankitpipada welcome to the library. To help you I will need to ask some questions. To make this easy please follow the template provide when you create a issue
`New issue > Bug`

Will close this now because is not following the repository template.

**Comment by ankitpipada** [comment]
library working on <Android 10 
App stop working when app run on android 11 
Scenario 
Click on button open Bottom sheet contain Camera ,Gallery ,Photo
Click Camera open camera app capture photo Show 2 option Cancel(X) and Right Click right or cancel app shop
I think app goes to background and show Unknown bits set in runtime_flags: 0x800000 
error 
I am working on last 15 days but unable to capture photo pls suggest

**Comment by Canato** [comment]
Hey, what I understood from your scenario:
1. Open sample app
1. Choose `CustomActivity`, you will see 3 options
1. Click Camera option
1. Capture a photo

## Here is a video of it working: 
_(every time I crop, it reload the screen with the cropped image)_
- **Pixel 3, Android 11**
_(tested on android 10 and 12 too)_


https://user-images.githubusercontent.com/15942449/133060401-8c6aaf6e-5b91-40fe-b742-06c7fd0bc716.mp4
