### ISSUE TITLE
Failed to load sampled bitmap / File is not a picture error

### ISSUE THREAD

**Issue by VEIKKO99** [CanHub/Android-Image-Cropper#21]
I'm using 1.1.1 version of the library.

I'm getting error:
 **java.lang.RuntimeException: Failed to load sampled bitmap: content://example.com.example.cropper.fileprovider/my_images/Pictures/pickImageResult2620448784152359897.jpeg
File is not a picture** when using CropImage activity. 

Error occurs on Android 10 (Nokia 5.3 device) but I have also received error from our users that the same error occurs also on Android 11 devices.

I have previously used ArthurHub / Android-Image-Cropper version of the library and It didn't have this problem on Android 10. Only on Android 11. 

Do you have any idea what I'm doing wrong or is there something on the library what should be fixed?

Thanks.

**Comment by Canato** [comment]
Hey @VEIKKO99 
Just to be sure, versions `1.1.1` is not a real version of the library, was done in the #14 for testing. We will launch yet.

Try to use versions `1.1.0` or wait next release to see if the problem persist

**Comment by VEIKKO99** [comment]
Ok,

I will do that, sorry for the hassle 👍

**Comment by medroa** [comment]
I try to use versions 1.1.0
  implementation 'com.github.CanHub:Android-Image-Cropper:1.1.0'

However, it doesn't build and I get the following error message:
  Failed to resolve: com.github.CanHub:Android-Image-Cropper:1.1.0

**Comment by Canato** [comment]
> I try to use versions 1.1.0
> implementation 'com.github.CanHub:Android-Image-Cropper:1.1.0'
> 
> However, it doesn't build and I get the following error message:
> Failed to resolve: com.github.CanHub:Android-Image-Cropper:1.1.0

@medroa please use the latest release `1.1.1` we change from GithubPackages to JItPack.
If you prefer to use `1.1.0` you need to import using GithubPackages. 

For next time you can open a new issue or even an [Discussion](https://github.com/CanHub/Android-Image-Cropper/discussions) =D

**Comment by jmcrox** [comment]
I have the same problem on Android 10 and 11.

I figured out the problem was on CropImage#getCaptureImageOurputUri(Context). This method was returned differents files uris in each call for these Android versions.

I have created a PR with my correction.

Thanks.
