### ISSUE TITLE
[Feat] - Jetpack compose support

### ISSUE THREAD

**Issue by jso8910** [CanHub/Android-Image-Cropper#211]
With the recent release of Jetpack Compose, I am wondering if you are ever considering adding jetpack compose support to this module

**Comment by Canato** [comment]
Hey @jso8910 I plan to move the whole library into Jetpack compose. But even without it, jetpack compose can call normal xml layouts and xml layouts can call jetpack compose, so should be working already.

There is something missing?  

On the same level, feel free to drop a PR and move it to Jetpack compose.

Obs: This is more a discussion over an issue, will move it to discussions
