### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by surajsahani** [CanHub/Android-Image-Cropper#212]
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.github.CanHub:Android-Image-Cropper:3.2.1: Skipped due to earlier error
`buildscript {
    ext.kotlin_version = "1.5.21"
    repositories {
        maven { url 'https://jitpack.io' }
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.8'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
        google()
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

**Comment by Canato** [comment]
Hey @surajsahani welcome to the library and thanks for the Issue. 

Can you please follow the template we have for bugs? There is many questions there I could use to help you.
Plus `[Bug]` as title do not give a understanding of what is happening with you. Let's please use more meaningful titles. 


Don't forget you can use ``` notation in github to format your code, this make it more visible to read, for example:
```kt
`buildscript {
ext.kotlin_version = "1.5.21"
repositories {
maven { url 'https://jitpack.io' }
google()
mavenCentral()
}
dependencies {
classpath 'com.android.tools.build:gradle:7.0.0'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
classpath 'com.google.gms:google-services:4.3.8'
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'
// NOTE: Do not place your application dependencies here; they belong
// in the individual module build.gradle files
}
}

allprojects {
repositories {
maven { url 'https://jitpack.io' }
google()
mavenCentral()
jcenter() // Warning: this repository is going to shut down soon
}
}

task clean(type: Delete) {
delete rootProject.buildDir
}`
```

About your error, `Could not determine artifacts for com.github.CanHub:Android-Image-Cropper:3.2.1: Skipped due to earlier error` 

why don't you try with the latest version? `3.3.5` 

And it say `Skipped due to earlier error` we need to check which error is this one.

I will **close** this issue so you can reopen following the template,
Is important to remember that my work here is volunteer and to save time and have better answer help me that people use the templates. Thanks!!
