### ISSUE TITLE
[BUG] - Manifest merger failed with multiple errors, see logs

### ISSUE THREAD

**Issue by vishalpatel1327** [CanHub/Android-Image-Cropper#216]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version [e.g. 3.3.5]
 
**Describe the bug**
I cant integrate with the latest SDK. ( compileSdkVersion 31)

https://www.loom.com/share/15b02df517544349931c4c33cc46a0d7

**Comment by Canato** [comment]
@vishalpatel1327 can you post a picture of your Android Manifest please?

Is the blue link appear in your logs in the end of the video. Probably some of your settings is missing export

**Comment by Canato** [comment]
Please check this file https://github.com/CanHub/Android-Image-Cropper/blob/main/build.gradle

Starting on line 29. You may need to copy this commands in your build.gradle and run this commands to understand what is missing.

**Comment by vishalpatel1327** [comment]
after running  **doAddAndroidExportedForDependencies** its working .
Maybe one signal library having an issue.

u r rock brother
