### ISSUE TITLE
Crashing while having a phone Call in Android 11 (Oppo f19 Pro)

### ISSUE THREAD

**Issue by sanketkagithub** [CanHub/Android-Image-Cropper#219]
after clicking on tick mark on image, activity gets recreated.....while on phone call..(I think app goes on low memory while having a phone call. (Android 11) Rest cases its fine working nicely only while having a phone call its an issue. Could someone please help?)[BUG] -

**Comment by Canato** [comment]
Welcome @sanketkagithub to help the volunteer work in the project we have the issue templates. Please re-open the issue following the templates =D
