### ISSUE TITLE
[BUG] - ScaleType Problem

### ISSUE THREAD

**Issue by PiotrBandurski** [CanHub/Android-Image-Cropper#220]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version 3.3.5
 
**Describe the bug**
I think that scale type is not working (Or I'm doing something wrong). When I have CropImageView with ratio for example 3x5 and I want to crop square image and im setting ScaleType to CENTER_CROP I would expect that preview of image will be filled (like in android ImageView). 

**To Reproduce**
1. In extended_activity.xml add `app:cropScaleType="centerCrop"` to `<com.canhub.cropper.CropImageView`
2. Run sample app
3. click "SAMPLE OF CUSTOM ACTIVITY"
4. Pick/take square photo
5. Go to crop screen
6. CropImageView is not filled

**Expected behavior**
Image should fill whole CropImageView

**Media**
<img src="https://user-images.githubusercontent.com/12571316/134816130-709354b2-8a0a-4eed-9c07-ac2d496d6eb4.png"  width="300" >

**Smartphone (please complete the following information):**
 - Device: xiaomi mi a 2 lite
 - OS: Android 9

**Additional context**
But maybe Im doing something wrong :D

**Comment by Canato** [comment]
Hey @PiotrBandurski Welcome!

And much thanks for using the template, helps a lot!

The issue here is because our `CropImageView` is a `FrameLayout` that contains a `ImageView` 

So in the code if we do `imageView.scaleType = ImageView.ScaleType.CENTER_CROP` it works!
But for be able to do from the xml we need to create a BindAdapter! 
Is something small that need some testing, I can do by the end of the week, but if you wanna open a PR for it, please fell free.

Will add some tags in case someone else wanna help

**Comment by PiotrBandurski** [comment]
No problem, my pleasure :) 

When I set 
`imageView.scaleType = ImageView.ScaleType.CENTER_CROP`,  it fills image view but I'm not able to exceed crop borders (darker image on screenshoot) I can create pull request with it but can you point me where to fix issue with crop borders?
<img src="https://user-images.githubusercontent.com/12571316/134873590-4be2edd1-cbf3-42a3-b91f-8ff506a0460b.png" width="300">

**Comment by Canato** [comment]
Strange behaviour, will dig it a little @@

**Comment by PiotrBandurski** [comment]
I tried to fix `CropOverlayView` but it is too complex for me

**Comment by Canato** [comment]
Will try to check over weekend, this is annoying @@

**Comment by Canato** [comment]
@PiotrBandurski this is a bug that we have in other places that I will need top fix anyway =| 

Can open the PR and I test it, will try to fix the bug on the weekend

**Comment by Marchuck** [comment]
Hello folks 👋 
I faced similar issue with  `centerCrop` when I was migrating from legacy to this new library. 
When I compared old Java code to the new Kotlin one, I spotted there's tiny change in `applyImageMatrix` [source](https://github.com/CanHub/Android-Image-Cropper/blob/main/cropper/src/main/java/com/canhub/cropper/CropImageView.kt#L1312)

there's no preceding if for scaleType like it was before, so current part:
```
mImageMatrix.mapRect(cropRect)
if (center) {
    // set the zoomed area to be as to the center of cropping window as possible
    mZoomOffsetX = ...
```
should be
```
mImageMatrix.mapRect(cropRect)
if (mScaleType == ScaleType.CENTER_CROP && center && !animate) {
    mZoomOffsetX = 0f
    mZoomOffsetY = 0f
} else if (center) {
    // set the zoomed area to be as to the center of cropping window as possible
    mZoomOffsetX = ...
```
             
hope it helped 🤞

**Comment by Canato** [comment]
@Marchuck could you please open a PR with the fix? Thanks!

**Comment by scana** [comment]
@Canato @Marchuck this is actually not the only part of code that is missing.

The thing is that together with @Marchuck we were using forked version of the old library and difference mentioned by him is actually a fix that we have implemented on our own (and never shared 🤦)

I'll open a PR for it.
