### ISSUE TITLE
[Feat] - use in java

### ISSUE THREAD

**Issue by mehdiwaysi** [CanHub/Android-Image-Cropper#224]
can you help me how to use this library with java

**Comment by Canato** [comment]
Please check https://github.com/CanHub/Android-Image-Cropper/tree/main/sample/src/main/java/com/canhub/cropper/sample/crop_image_java

Already answer this questions some time in discussion before, don't forget to search please =D

If you have any issue let me know please ^^

**Comment by mehdiwaysi** [comment]
thank you very much    On Wednesday, September 29, 2021, 07:10:15 PM GMT+3:30, Canato ***@***.***> wrote:  
 
 


Closed #224.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
