### ISSUE TITLE
[hacktoberfest] - UI tests

### ISSUE THREAD

**Issue by Canato** [CanHub/Android-Image-Cropper#229]
We need emulator UI tests using our sample code

**Comment by karandeeppotato** [comment]
Hi there, I am willing to work on this can you please assign me?

**Comment by Canato** [comment]
Assigned @karandeeppotato but do not feel the pressure to do all the tests, if you do one already helps and other people can do more, or if you feel like it can do it all ^^ or many

**Comment by karandeeppotato** [comment]
I guess I should do one or two tests and leave the rest for other first-timers as they should also get a chance in the HACTOBERFEST. 😉

**Comment by karandeeppotato** [comment]
@Canato 
Hi there, I did two tests, the code is working perfectly.
didn't find any issue.
Should I conduct more tests?

**Comment by Canato** [comment]
@karandeeppotato let's merge this :D

If you wanna open more Pars feel free for it :)

**Comment by karandeeppotato** [comment]
no I'm trying to reproduce the issue.. but can't
that's what I meant earlier

**Comment by Canato** [comment]
@karandeeppotato which issue?

**Comment by karandeeppotato** [comment]
@Canato 
Sir, i am saying that i was testing out the main code in order to find an issue.
But couldn't find one..

**Comment by karandeeppotato** [comment]
The main code is working well in my emulated system

**Comment by Canato** [comment]
@kaanhangithub great! the code should be stable and working. This issue is not about finding any issue or bug, but about creating automate UI tests for the library, so future changes cannot be merged without tests

**Comment by visheshjindal** [comment]
Hi @Canato 

I can write automated UI test cases as well for the framework using Espresso. But wouldn't be able to cover 100% in one go.

can you please scope it out?

And assign it to me. Thanks

**Comment by Canato** [comment]
Hey @visheshjindal best way to scope is using the flow we have by buttons.

e.g. `Open the app > "sample calling cropimage" > "outside camera and start(urI)"` 

So we do one test for each of this flows to start.

**Comment by visheshjindal** [comment]
Cool, Lets just start with that @Canato 

Please do assign it to me.

**Comment by Canato** [comment]
Until next year
