### ISSUE TITLE
[hacktoberfest] - Unit and integration tests

### ISSUE THREAD

**Issue by Canato** [CanHub/Android-Image-Cropper#230]
Test some important maths we have, like BitmapUtils methods

**Comment by visheshjindal** [comment]
Hi @Canato 

I would like to work on this. Please assign this to me. 

Thanks

**Comment by visheshjindal** [comment]
Thanks @Canato

**Comment by Canato** [comment]
If you feel like just do some of the tests we need, we can open a second ticket more specific too =D. Let me know when you scope your work ^^

**Comment by visheshjindal** [comment]
Hi @Canato 

I am going to look into it today. Will you update about the scope.

Apart from that do you mind If I add any mocking framework to the lib e.g. Mockk

Thank You.

**Comment by Canato** [comment]
No problem to add libraries, let's just prefer MockK over mockito, more kotlin friendly

**Comment by visheshjindal** [comment]
Hi @Canato 

I have raised a small PR to initiate the Unit testing for the BitmapUtil class. #232 

I request you to kindly review the same.

I analysed that even BitmapUtils class has a lot to cover. I would like to suggest breaking the task into many smaller ones e.g. like Class to be tested along with the major functions. That will definitely bring more contribution and easy to close issue.

Thanks

**Comment by Canato** [comment]
For sure, small PRs and iterative work is always better and safer

**Comment by Canato** [comment]
Step one done at #232

**Comment by visheshjindal** [comment]
@anadpc You can contribute here.

**Comment by Canato** [comment]
@visheshjindal I think the tag didn't work, saying cause more help is always good help hahahah

**Comment by Canato** [comment]
Until next year
