### ISSUE TITLE
its not working in android 11. [BUG] - 

### ISSUE THREAD

**Issue by alpesh76** [CanHub/Android-Image-Cropper#249]
This project is not properly working in android 11.
I compiled this project. It's successfully compiled. But it's not cropping images from a select gallery.

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

- `The project is working in many projects and Android 11 devices, please provide a video of the sample in this repository not working on the android 11 so we can debug it`

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template and will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template

_Is important to remember that my work here is volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
