### ISSUE TITLE
[Feat] - Failed To Resolve

### ISSUE THREAD

**Issue by vd1516** [CanHub/Android-Image-Cropper#254]
🚨🚨 Important to remember that this library is maintained for free. 
You can check the maintainers plans for the library in the Project tab. 
If you really want to have some maintainer working in your feature please check the sponsorship options.
But feel free to suggest features and do yourself, this is a community driven open source library

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

_Obs if you have some code for it, feel free to assign yourself open the PR after this issue_

**Comment by Canato** [comment]
No information
