### ISSUE TITLE
[Feat] - consumer proguard rules

### ISSUE THREAD

**Issue by Alireza-Farahani** [CanHub/Android-Image-Cropper#257]
Since this a android library and you publish an aar artifact, you can include proguard rules in the final artifact and remove the burden from end user. See [here](https://developer.android.com/studio/projects/android-library#Considerations)
```groovy
android {
    defaultConfig {
        consumerProguardFiles("lib-proguard-rules.txt")
    }
    ...
}
```
By the way, is it necessary to keep all of `-keep class androidx.appcompat.widget.** { *; }` classes or could it be more narrowed?

**Comment by Canato** [comment]
@Alireza-Farahani this is some I heritage and never had the time to take a look, would you mind of opening a PR with this amazing changes? ^^

**Comment by Alireza-Farahani** [comment]
I can create the PR and I like to, since it seems a great "first PR". It could take a while since I'm not very familiar with PR process.

**Comment by Canato** [comment]
No issue, take your time to make it good, just keep this thread update!

If you need any help let me know and I will review the code with you before merge =)

**Comment by Alireza-Farahani** [comment]
I saw in an issue of ArthurHub ImageCropper that the proguard rule is not necessary. I tested your sample via 
```groovy
minifyEnabled true
shrinkResources true
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
```
and it just worked! Do you have previously faced Proguard issues?

**Comment by Canato** [comment]
This is very sensible, even what we keep on the proguard is not related to this library. But AndroidX.

This may have issue in some usages of AndroidX with this lib, you are right about that is something we just copied to this library.
- If we decide to remove we need to keep and eye if someone who use this library will have it break and fix on the fly.
- If we add to the library, like you suggest, we can sleep calm hahahha. 

I let you decide what is the better cause I like have more people opinions and we work together to improve the code and people usage XD

**Comment by Alireza-Farahani** [comment]
I would go with the first, 
 - The library as you confirmed and as I search it, doesn't reference any `appcompat.widget` classes. All of the library compile dependencies are also androidx libraries which have consumer proguard rules included. For example `appcompat` has: 
```
# aapt is not able to read app::actionViewClass and app:actionProviderClass to produce proguard
# keep rules. Add a commonly used SearchView to the keep list until b/109831488 is resolved.
-keep class androidx.appcompat.widget.SearchView { <init>(...); }

# Never inline methods, but allow shrinking and obfuscation.
-keepclassmembernames,allowobfuscation,allowshrinking class androidx.appcompat.widget.AppCompatTextViewAutoSizeHelper$Impl* {
  <methods>;
}
```
So it seems our proguard rule should not be needed.
 - We are using this library in our app, that is near its first release. We certainly will test it in obfuscated mode
 - The library is keeping `appcompat.widget.**` sub package which is pretty larger

**Comment by Canato** [comment]
Perfect! Feel free to drop the PR @Alireza-Farahani
