### ISSUE TITLE
onActivityResult is deprecated

### ISSUE THREAD

**Issue by zihadrizkyef** [CanHub/Android-Image-Cropper#26]
Hi, i really love your project, but i see that we are still using OnActivityResult which is deprecated.
Maybe we can use this one : https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContract

**Comment by Canato** [comment]
Hey @zihadrizkyef thanks for the suggestion, for sure is time for us to change.

I'm happy if you have time to do it, just need to open the PR ^^

**Comment by dimiitpk** [comment]
Hello guys, there is a way to do this with ActivityResult Api
Create custom contract : 

```
private val cropResultContract by lazy {
        object : ActivityResultContract<Any?, Uri?>() {
            override fun createIntent(context: Context, input: Any?): Intent {
                return CropImage
                    .activity()
                    .setCropShape(CropImageView.CropShape.RECTANGLE)
                    .getIntent(this@Fragment.requireContext())
            }


            override fun parseResult(resultCode: Int, intent: Intent?): Uri? {
                return CropImage.getActivityResult(intent)?.uri
            }
        }
    }
```

Create launcher 

```
private lateinit var cropResultLauncher: ActivityResultLauncher<Any?>

override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        cropResultLauncher = registerForActivityResult(cropResultContract) { uri ->
            uri?.path?.let {
                // parse Uri
            }
        }
    }
```

and when u need to start it

`cropResultLauncher.launch(null)`

**Comment by Canato** [comment]
Yes @dimiitpk 

And this is something we want to add in the library directly, I'm organising now all work to be done in the lib =p 

But feel free to open a PR if you are confident of how doing it!

**Comment by AlexanderHoddleITE** [comment]
It is not a bug or an issue with current version.
@dimiitpk Your idea is nice, but there is a much easier way to do it with ActivityResult.
You need to define:
```
private var imageCropCallback = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
	if (result.resultCode == Activity.RESULT_OK) {
		CropImage.getActivityResult(result.data)?.let { cropResult ->
			// work with cropResult
		}
	}
}
```

And then launch like this:
```
val intent = CropImage
	.activity(uri)
	.setCropShape(CropImageView.CropShape.RECTANGLE)
	.getIntent(requireContext())
	
imageCropCallback.launch(intent)
```

**Comment by Canato** [comment]
@AlexanderHoddleITE please feel free to drop a PR to update the library if you are feeling up to help the community today, hahahaha

**Comment by ArcherEmiya05** [comment]
@Canato no need for PR to update the library for this one, just like @AlexanderHoddleITE said this is not a bug nor an issue with the library as it is already able to work with the latest approach of onActivityResult. Just need to update the README.md  for the documentation update.

**Comment by Canato** [comment]
Indeed @ArcherEmiya05 you can do your own wrapper around, but we are still using `onActivityResult` inside the library, what now is deprecated. Is on my plans to have this wrapper already in the lib, so we could have it without the wrapper =D

**Comment by ArcherEmiya05** [comment]
> 
> 
> Indeed @ArcherEmiya05 you can do your own wrapper around, but we are still using `onActivityResult` inside the library, what now is deprecated. Is on my plans to have this wrapper already in the lib, so we could have it without the wrapper =D

Can't it just be remove since all we need is the intent itself then just leave it to consumer to handle the result?

**Comment by connyduck** [comment]
I would like to send a PR for this, but I am not sure what the best option is here.

One way to have this working could be to have CropImageOptions as input and ActivityResult as output like this:

```kotlin
class CropImageContract : ActivityResultContract<CropImageOptions, CropImage.ActivityResult?>() {

    override fun createIntent(context: Context, input: CropImageOptions): Intent {
        input.validate()
        return Intent().apply {
            val bundle = Bundle()
            bundle.putParcelable(CropImage.CROP_IMAGE_EXTRA_OPTIONS, input)
            putExtra(CropImage.CROP_IMAGE_EXTRA_BUNDLE, bundle)
        }
    }

    override fun parseResult(
        resultCode: Int,
        intent: Intent?
    ): CropImage.ActivityResult? {
        return getActivityResult(intent)
    }
}
```

The problem with this is that one cannot supply a Uri as input, so it only works if you want to show the file picker.

Maybe its better to have the options in the constructor and the uri as input? 
```kotlin
class CropImageContract(
    private val options: CropImageOptions
) : ActivityResultContract<Uri?, CropImage.ActivityResult?>() {
    
    init {
        options.validate()
    }

    override fun createIntent(context: Context, input: Uri?): Intent {
        return Intent().apply {
            val bundle = Bundle()
            bundle.putParcelable(CropImage.CROP_IMAGE_EXTRA_SOURCE, input)
            bundle.putParcelable(CropImage.CROP_IMAGE_EXTRA_OPTIONS, options)
            putExtra(CropImage.CROP_IMAGE_EXTRA_BUNDLE, bundle)
        }
    }

    override fun parseResult(
        resultCode: Int,
        intent: Intent?
    ): CropImage.ActivityResult? {
        return getActivityResult(intent)
    }
}
```

This is less flexible if one needs multiple crop options.

Thoughts?

**Comment by Canato** [comment]
@connyduck and a new data class, like
```
data class CropImageContractInput(
    val uri: Uri?,
    val cropImageOptions: CropImageOptions,
}
```
So we could use `class CropImageContract : ActivityResultContract<CropImageContractInput, CropImage.ActivityResult?>()`

Would work? 🤔

**Comment by connyduck** [comment]
Yes that would work, but its cumbersome if you don't want to supply a uri. Maybe it can be improved by adding some convienience functions. I'll try to find a nice solution.

**Comment by Morons** [comment]
I am working with 
```kotlin
	private val cropActivityResultContract = object : ActivityResultContract<Any?, Uri>() {
		override fun createIntent(context: Context, input: Any?): Intent {
			return CropImage.activity()
				.setGuidelines(CropImageView.Guidelines.ON)
				.getIntent(context)
		}
		
		override fun parseResult(resultCode: Int, intent: Intent?): Uri? {
			return CropImage.getActivityResult(intent)?.uriContent
		}
	}
	
	private lateinit var cropActivityResultLauncher: ActivityResultLauncher<Any?>
```
In my `Button setOnClickListener`
`cropActivityResultLauncher.launch(null)`

**Comment by swagatgithub** [comment]
> It is not a bug nor an issue with current version. @dimiitpk Your idea is nice, but there is a much easier way to do it with ActivityResultContracts. You need to define:
> 
> ```
> private var launcher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
> 	if (result.resultCode == Activity.RESULT_OK) {
> 		CropImage.getActivityResult(result.data)?.let { cropResult ->
> 			// work with cropResult
> 		}
> 	}
> }
> ```
> 
> And then launch like this:
> 
> ```
> val intent = CropImage
> 	.activity()
> 	.setCropShape(CropImageView.CropShape.RECTANGLE)
> 	.getIntent(requireContext())
> 	
> launcher.launch(intent)
> ```

Have You Implemented in the same way? i did ,but my  ActivityResultCallback is not called..

**Comment by Canato** [comment]
Hey @swagatgithub not you don't need to implement yourself like Dimiitpk needed on the time he wrote.

You can use the library activity contracts, like is showed on the README and the sample folder
