### ISSUE TITLE
[Feat] - Gradle cleanup

### ISSUE THREAD

**Issue by Alireza-Farahani** [CanHub/Android-Image-Cropper#265]
There are some small unnecessary or deprecated thing in project's gradle files like:
* Since Kotlin 1.4.0, there's no need to add standard library as a dependency
* Since AGP 4.1 `compileSdkVersion`, `targetSdkVersion` and `minSdkVersion` are deprecated in favor of shorter properties of `compileSdk`, `targetSdk` and `minSdk`
* Since AGP 4.2 java 1.8 support is enabled by default. We could mention this in ReadMe.

See original [article](https://zsmb.co/a-bit-of-gradle-housekeeping/) for more info. I have these changes ready in my fork and could create a pull request if you are OK with it.

**Comment by Canato** [comment]
Hey @Alireza-Farahani thanks for raising this, please be free to create a PR so we can improve this ^^

We just need to be sure we keep backward compatibility.
