### ISSUE TITLE
[Feat] - launch to camera directly

### ISSUE THREAD

**Issue by Hawksbillcat** [CanHub/Android-Image-Cropper#267]
is that possible to intent to camera after click some UI button and return the image to crop activity? 
(can the start picker chahge to optional function?)

**Comment by Canato** [comment]
Hey @Hawksbillcat welcome to the library.

Good news, is possible ^^. We have many ways of doing this, the simple one is: 

```kt
private val cropImage = registerForActivityResult(CropImageContract()) { 
    // deal with result. 
}

// code ... code

// on you UI click call
private fun startCrop() {
    cropImage.launch( 
        options {
            ...
        }
    )
}
```

In the above case we let the library do everything.
But if you want to have only camera (without gallery) you can have this code:

```kt
private val cropImage = registerForActivityResult(CropImageContract()) { 
    // deal with result. 
}
private val pickImage = registerForActivityResult(PickImageContract()) { photoUri ->
    cropImage.launch( 
        options(photoUri) {
            ...
        }
    )
}

// code ... code

// start camera
private fun startPickImage() {
    pickImage.launch(PickImageContractOptions(includeGallery = false))
}
```

All this code you can find at [crop image sample](https://github.com/CanHub/Android-Image-Cropper/blob/main/sample/src/main/java/com/canhub/cropper/sample/crop_image/app/SCropImageFragment.kt) file.

We have a [java](https://github.com/CanHub/Android-Image-Cropper/tree/main/sample/src/main/java/com/canhub/cropper/sample/crop_image_java) one too

**Comment by Canato** [comment]
Will move this to discussion as a Q&A
