### ISSUE TITLE
[BUG] - FileUriExposedException when trying to lunch only camera intent.

### ISSUE THREAD

**Issue by ArmChilingarov** [CanHub/Android-Image-Cropper#274]
- Lib Version 3.3.6
 
**Describe the bug**
App gets crashed when I want to open only camera intent .

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.croppersample/com.canhub.cropper.CropImageActivity}: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.example.croppersample/cache/pickImageResult.jpeg exposed beyond app through ClipData.Item.getUri()

**To Reproduce**
in a crop image sample  use this part of code. 
private val customCropImage = registerForActivityResult(CropImageContract()) {
        ... 
    }

customCropImage.launch(
            options {
                setImagePickerContractOptions(PickImageContractOptions(false,true))
             })

**Media**
<img width="2416" alt="Screen Shot 2021-11-23 at 18 30 17" src="https://user-images.githubusercontent.com/28526900/143043249-8c7c14f7-e4ff-42aa-b1ee-cfac92301551.png">

**Smartphone (please complete the following information):**
 - Device: Xiaomi2 mi a2
 - OS: API Level 30 
 
  - Device: Android emulator
 - OS: API Level 28, 29 

@Canato

**Comment by Canato** [comment]
Duplicated of #253

**Comment by ArmChilingarov** [comment]
Hey @Canato . 

You marked the issue as a duplicate of #253 , but this is absolutely different issue. 
If you need more details, I can provide to you .

**Comment by Canato** [comment]
Sorry @ArmChilingarov you are right, I'm reopening, but hopefully the PR I'm working will fix this too

**Comment by Canato** [comment]
If possible please test

To test this changes
`implementation 'com.github.CanHub:Android-Image-Cropper:271-read-files-without-permission-38df1455d6-1'`

All feedbacks at #280
