### ISSUE TITLE
Crop points for image with Exif rotation

### ISSUE THREAD

**Issue by getmlcode** [CanHub/Android-Image-Cropper#279]
### Discussed in https://github.com/CanHub/Android-Image-Cropper/discussions/278

<div type='discussions-op-text'>

<sup>Originally posted by **getmlcode** November 27, 2021</sup>
I need crop points of various regions, in the image and then extract those regions from image on a different server. It works fine for landscape mode , but for other orientations it is not able to extract correct regions based on crop points provided by the library.

I have dived in the code and there was a comment that says , crop points are provided according to original image. I didn't clearly understand what is meant by that ? Some images have Exif rotation as non zero embedded in their meta info, so what is taken as the origin point for those images ?

It would be nice if someone can shed light on how to interpret crop points in case of images with non zero Exif rotation

Thanks,
Siddharth</div>

**Comment by Canato** [comment]
Hey @getmlcode we have the same topic in 2 places now, will close this one for now do we can keep the discussion in one place. We can open a issue later **following the templates** we have in the repository for new features/
