### ISSUE TITLE
not showing toolbar or any icon to perform action

### ISSUE THREAD

**Issue by ramesh998** [CanHub/Android-Image-Cropper#284]
![Screenshot_1638538216](https://user-images.githubusercontent.com/42915529/144610677-826a8de8-3c5d-43ab-b102-70b8927d361b.png)
Not able to save the crop image
Same issue on emulator and real device

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template and will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template,

_Is important to remember that my work here is volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
