### ISSUE TITLE
[BUG] -  Transparency lost of any transparent image

### ISSUE THREAD

**Issue by Mr-Ramzan** [CanHub/Android-Image-Cropper#289]
- Lib Version // Project  libVersion = "3.3.6"
 
**The bug**
When you try to crop an image on which you already ha some transparent pixels(transparent BG) Library fills its background and transparency is lost in result

**To Reproduce**

1. Go to 'Gallery and select any picture or logo with transparent BG'
2. Click on 'Click Save The result as in video will be shown on same screen'
3. Scroll down to 'Nothing you will see issue there'
4. See error in the attached video

**Expected behavior**
Transparency of an image should not be lost

**Media**

https://user-images.githubusercontent.com/36961360/146167953-4f28c265-9a09-496c-8fa8-d4e1ecbf7402.mp4

**Smartphone (please complete the following information):**
 - Device: [e.g. Techno Camon 15]
 - OS: [Android 11]

**Additional context**
NONE

**Comment by Canato** [comment]
Hey @Mr-Ramzan could you try it on the latest release?

**Comment by Canato** [comment]
Another point, did you setup the file type?  `setOutputCompressFormat(Bitmap.CompressFormat.PNG)`

**Comment by Mr-Ramzan** [comment]
Yes same issue
With latest code

**Comment by Mr-Ramzan** [comment]
> Another point, did you setup the file type? `setOutputCompressFormat(Bitmap.CompressFormat.PNG)`

I just tested same issue

**Comment by Canato** [comment]
@Mr-Ramzan could you provide the image you are using so I can test later with the same? Thanks!

**Comment by Mr-Ramzan** [comment]
![ltixtlrfq5dod0r8q6ws](https://user-images.githubusercontent.com/36961360/146175818-3e8e1aa1-d684-4c9f-b1e3-edaa0ecb3376.PNG)

**Comment by Canato** [comment]
Hey! not sure what you did to enable PNG format, but check my images... this is what a changed.
And check the video. working for me

<img width="743" alt="Screenshot 2021-12-15 at 13 33 13" src="https://user-images.githubusercontent.com/15942449/146195953-8b02b31d-eeef-4302-a71d-18ee6215565c.png">

<img width="538" alt="Screenshot 2021-12-15 at 13 33 19" src="https://user-images.githubusercontent.com/15942449/146195930-08060787-4ca5-4a08-966e-cd20a3df7fb0.png">

https://user-images.githubusercontent.com/15942449/146196600-2523878f-a6c5-472b-99fe-8dd6c1a5349a.mp4

**Comment by Mr-Ramzan** [comment]
```

        customCropImage.launch(
            options {
                setScaleType(CropImageView.ScaleType.CENTER)
                setCropShape(CropImageView.CropShape.OVAL)
                setGuidelines(CropImageView.Guidelines.ON)
                setAspectRatio(4, 16)
                setMaxZoom(8)
                setAutoZoomEnabled(false)
                setMultiTouchEnabled(false)
                setCenterMoveEnabled(true)
                setShowCropOverlay(false)
                setAllowFlipping(false)
                setSnapRadius(10f)
                setTouchRadius(30f)
                setInitialCropWindowPaddingRatio(0.3f)
                setBorderLineThickness(5f)
                setBorderLineColor(R.color.black)
                setBorderCornerThickness(6f)
                setBorderCornerOffset(2f)
                setBorderCornerLength(20f)
                setBorderCornerColor(RED)
                setOutputCompressFormat(Bitmap.CompressFormat.PNG)
                setGuidelinesThickness(5f)
                setGuidelinesColor(RED)
                setBackgroundColor(Color.argb(119, 30, 60, 90))
                setMinCropWindowSize(20, 20)
                setMinCropResultSize(16, 16)
                setMaxCropResultSize(999, 999)
                setActivityTitle("CUSTOM title")
                setActivityMenuIconColor(RED)
                setOutputUri(customUri)
                setOutputCompressFormat(Bitmap.CompressFormat.PNG)
                setOutputCompressQuality(50)
                setRequestedSize(100, 100)
                setRequestedSize(100, 100, CropImageView.RequestSizeOptions.RESIZE_FIT)
                setInitialCropWindowRectangle(null)
                setInitialRotation(180)
                setAllowCounterRotation(true)
                setFlipHorizontally(true)
                setFlipVertically(true)
                setCropMenuCropButtonTitle("Custom name")
                setCropMenuCropButtonIcon(R.drawable.ic_gear_24)
                setAllowRotation(false)
                setNoOutputImage(false)
                setFixAspectRatio(true)
            }
        )
```

**Comment by Mr-Ramzan** [comment]
I have also set compress formate to PNG but it shows a black background ...

**Comment by Mr-Ramzan** [comment]
It works when I change the Output Compress format thank you very much

**Comment by Canato** [comment]
I think you are changing the wrong place of the code. Could you change same places I changed and do the same flow?

+ you may want to have less options for the test, since you have `setOutputCompressFormat(Bitmap.CompressFormat.PNG)` twice XD

**Comment by Mr-Ramzan** [comment]
> I think you are changing the wrong place of the code. Could you change same places I changed and do the same flow?
> 
> * you may want to have less options for the test, since you have `setOutputCompressFormat(Bitmap.CompressFormat.PNG)` twice XD


I changed the output compress format in crop options and it worked as expected.

**Comment by Mr-Ramzan** [comment]
Thank you for quick Support. Let me know if you want to close the issue or please close by yourself.

**Comment by Canato** [comment]
Great that is working =D, welcome!
