### ISSUE TITLE
[Feat] - how to use in java 

### ISSUE THREAD

**Issue by adnangulzar555** [CanHub/Android-Image-Cropper#290]
D:\backbackup\31_12_2020\31_12_2020\app\src\main\java\com\wonderApps\TexOnPicture\MainActivity.java:1243: error: cannot find symbol
                    cropImage.crop();
                    ^
  symbol: variable cropImage

i got this error

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template and will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template,

_Is important to remember that my work here is volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
