### ISSUE TITLE
[BUG]Camera Image Pick Up not working in Xiaomi note 10s, OS 11 

### ISSUE THREAD

**Issue by rushidalvi** [CanHub/Android-Image-Cropper#291]

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template and will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template,

_Is important to remember that my work here is volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
