### ISSUE TITLE
Rotation issue after taking photo from camera 

### ISSUE THREAD

**Issue by Jeyaseelan2528** [CanHub/Android-Image-Cropper#292]
The image is rotated to landscape or 90 automatically, what is the solution for it

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template and will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template,

_Is important to remember that my work here is volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
