### ISSUE TITLE
[BUG] - 502-bad gateway

### ISSUE THREAD

**Issue by techker** [CanHub/Android-Image-Cropper#293]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

tried re building an app i had that was working on 3.3.4 got bad gateway 502

tried latest same issue?

Could not HEAD 'https://urbanairship.bintray.com/android/com/github/CanHub/Android-Image-Cropper/4.0.0/Android-Image-Cropper-4.0.0.pom'. Received status code 502 from server: Bad Gateway

 - Lib Version [e.g. 1.1.0]
 
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Media**
Please add screenshots and/or screen recordings to help explain your problem.
We cannot help without more information

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3XL]

**Additional context**

**Comment by Canato** [comment]
Hey @techker I cannot really read this issue, need better formatting. Could you please reopen filling the template we provide? Thanks!
