### ISSUE TITLE
[BUG] - Received 502 from server

### ISSUE THREAD

**Issue by techker** [CanHub/Android-Image-Cropper#294]
- Lib Version: 3.3.5-4.0.0
 
**Describe the bug**
```
Gradle build gives error : 

Could not HEAD 'https://urbanairship.bintray.com/android/com/github/CanHub/Android-Image-Cropper/4.0.0/Android-Image-Cropper-4.0.0.pom'. Received status code 502 from server: Bad Gateway
```
Any version i try i get the same error.

**To Reproduce**
1. Build project

**Expected behavior**
1. Build correctly with lib

**Comment by Canato** [comment]
Hello @techker

I could not reproduce, I build the project and it work for me. 

Could you share how are you importing the project and/or a open repository I could check? Thanks

**Comment by techker** [comment]
oddly even bitrise gave me that error. So i know its not my local internet.i had version 3.2.1. noticed it never complained that the version was outdated, i changed it to latest 4.0.0 and was the same issue.
to fix it i just downloaded and merge directly what i needed.
thx
From Bitrise:

Could not resolve com.github.CanHub:Android-Image-Cropper:3.2.1.
     Required by:
         project :app
      > Could not resolve com.github.CanHub:Android-Image-Cropper:3.2.1.
         > Could not get resource 'https://urbanairship.bintray.com/android/com/github/CanHub/Android-Image-Cropper/3.2.1/Android-Image-Cropper-3.2.1.pom'.
            > Could not GET 'https://urbanairship.bintray.com/android/com/github/CanHub/Android-Image-Cropper/3.2.1/Android-Image-Cropper-3.2.1.pom'. Received status code 502 from server: Bad Gateway

**Comment by Canato** [comment]
Hey, sorry for the lack of answers here.

I'm on vacation and traveling until 18/01. Just after this I will have the attention of this repository.

Do not need to wait for me, just letting people know as I'm the main maintenance

**Comment by Canato** [comment]
Hey @techker how is this? still and issue?
