### ISSUE TITLE
[BUG] - Image disappears in `CropImageActivity` after configuration change

### ISSUE THREAD

**Issue by samiuelson** [CanHub/Android-Image-Cropper#296]
- Lib Version 4.0.0
 - Reproducible in the sample app
 
**Describe the bug**
The cropped image disappears in `CropImageActivity` on any configuration change (e.g. screen rotation, device theme switch).

**To Reproduce**
Steps to reproduce the behavior in the sample app:
1. Go to 'Sample of custom activity'
2. Pick an image from storage or from the camera
3. Image is displayed correctly
4. Rotate the screen to landscape (or invoke any other configuration change, e.g. switch device's theme from light to dark)
5. Image disappears (it's not visible also when going back to portrait)

**Expected behavior**
The state (image uri, crop, rotation, etc) should be preserved across configuration changes.

**Media**

https://user-images.githubusercontent.com/4527432/147878286-ae9f0299-c05a-4fe5-9d89-a3eb0bea1192.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 4a 5G
 - OS: Android API 31

**Additional context**
Happens both in the sample app, and in my own app using `CropImageActivity` launched in the following way:
```kotlin
options(uri = imageUri) {
    setGuidelines(CropImageView.Guidelines.ON)
    setAllowFlipping(false)
    setActivityTitle("Adjust Image")
    setCropMenuCropButtonTitle("Save")
}
```

**Comment by Canato** [comment]
Hey, sorry for the lack of answers here.

I'm on vacation and traveling until 18/01. Just after this I will have the attention of this repository.

Do not need to wait for me, just letting people know as I'm the main maintenance

**Comment by Canato** [comment]
Indeed, an issue. Happy to someone drop a PR fixing it ^^

**Comment by yoijoe4** [comment]
Hi, guys :) . This issue is indeed unfitting of this great image-cropper library.
I have tested some different versions and it seems this issue started in release '3.3.4'.
Release '3.2.2.' works fine when the screen rotates.

People looking for a current FIX:
To prevent the issue from happening, I currently set the screenOrientation for the Activity in my Manifest file. It seems to work fine for now.
```
<application
	
        <activity android:name="com.canhub.cropper.CropImageActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Base.Theme.AppCompat"/> <!-- default theme has no action bar -->

</application>
```

**Comment by Canato** [comment]
@yoijoe4 thanks for searching this!

@samiuelson this work for you?

Please any of you feel free to drop a PR fixing it ^^

**Comment by samiuelson** [comment]
This is not a solution. Configuration change happens not only during screen rotation but also on theme switch, locale change, etc. Events like those also break the behavior. 

My preferred solution would be to implement ViewModel for CropImageActivity which would survive configuration changes. The ViewModel would intercept user/UI events from CropActivity and compute and expose the current UI state. The activity would collect the state from view model and render it.

**Comment by yoijoe4** [comment]
@samiuelson You are totally right. I forgot to mention that and I have changed my comment accordingly.
