### ISSUE TITLE
Android 10 / 11 Permissions issue

### ISSUE THREAD

**Issue by Canato** [CanHub/Android-Image-Cropper#3]
With the new OS the permission `WRITE_EXTERNAL_STORAGE` got deprecated. 
And now need to use scope storage.

[More here](https://developer.android.com/about/versions/11/privacy/storage)

**Comment by akkie2106** [comment]
still not getting URI From Camera Image

**Comment by Canato** [comment]
Hey @akkie2106 this is not fixed yet, will be in `1.1.0`
`1.0.0` is just a copy from previous lib

**Comment by akkie2106** [comment]
OK

**Comment by akkie2106** [comment]
<queries>
        <intent>
            <action android:name="android.intent.action.GET_CONTENT" />
            <data android:mimeType="image/*" />
        </intent>

        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
    </queries>
i put this in manifest it shows me camera and files to select image but camera is still not working i'm getting null in intent data
@Canato

**Comment by ravindu1024** [comment]
@Canato Sorry mate, was super busy. I updated the PR to remove some unwanted changes I had made. We don't really need the Provider or the Authority. The magic is in how we request the intent: `galleryIntent.addCategory(Intent.CATEGORY_OPENABLE);`. All devices should support this, technically. This works for all API levels including 30.

**Comment by Canato** [comment]
> ```
>     <intent>
>         <action android:name="android.media.action.IMAGE_CAPTURE" />
>     </intent>
> </queries>
> ```
> 
> i put this in manifest it shows me camera and files to select image but camera is still not working i'm getting null in intent data
> @Canato

@akkie2106 please open a new issue with more information. 
What part of the code you get the null, OS, etc

I believe I know a solution 😄 just need to be sure is the same topic
