### ISSUE TITLE
is CropMaxDimensions() supposed to compress Image size from Camera ?

### ISSUE THREAD

**Issue by deanwinchester4848** [CanHub/Android-Image-Cropper#30]
I set CropMaxDimensions(640, 360) in my App
and I ran some Test:

In Device with Android 9:
Image from Gallery with size 16MB can be compress to 760kb
and Image from Camera with size 5.7MB can be compress to 380kb

In Device with Android 10:
Image from Gallery with size 16MB can be compress to 760kb
but Image from Camera with size 3.5MB only compress to 3.4MB

is this possible ?

**Comment by Canato** [comment]
Hey @deanwinchester4848 welcome to our library community.

- When open an issue, please follow our templates to help us to understand and help you. 

I believe you are talking about the method `setMaxCropResultSize(int, int)` can you confirm if this is the case?

Your final statement is `is this possible ?` don't look like a bug for me, but a question. We have the Q&A Discussion for this [here](https://github.com/CanHub/Android-Image-Cropper/discussions)

But about your question. The method `setMaxCropResultSize` is related to the `width` and `height` of the image, not related to the size of it. Any size change is a side effect of this method.

Can you confirm if I understood this right? Thanks

**Comment by deanwinchester4848** [comment]
Thanks, I get it now.
And is it possible to set the Max Size e.g. 2MB ?
