### ISSUE TITLE
Crop option is not showing

### ISSUE THREAD

**Issue by amit7127** [CanHub/Android-Image-Cropper#300]
```
private val cropImage = registerForActivityResult(CropImageContract()) { result ->
        if (result.isSuccessful) {
            // use the returned uri
            val uriContent = result.uriContent
            val uriFilePath = result.getUriFilePath(requireContext()) // optional usage
            val file = uriContent?.toFile()
            onImageSelected(file)
        } else {
            // an error occurred
            val exception = result.error
        }
    }

//For opening the image sector
cropImage.launch(
                options {
                    setGuidelines(CropImageView.Guidelines.ON)
                }
            )
```
![Screenshot_1641921988](https://user-images.githubusercontent.com/20200573/148991762-720dfbad-c24d-4876-95bb-18f7402311c8.png)

After selecting a image from gallery/camera -> Screen is opening to select the image area but not showing any crop option. Please check the screenshot attached.

**Comment by vickyNeji** [comment]
Try using below code inside manifest file

<activity android:name="com.canhub.cropper.CropImageActivity"
            android:theme="@style/Base.Theme.AppCompat"/>

**Comment by vickyNeji** [comment]
Try using below code inside manifest file
`<activity android:name="com.canhub.cropper.CropImageActivity" 
            android:theme="@style/Base.Theme.AppCompat"/>`
