### ISSUE TITLE
[BUG] - Error to sinc

### ISSUE THREAD

**Issue by nandezgarcia** [CanHub/Android-Image-Cropper#302]
When I snc Gradle file and I try to run app, say me:
Could not find com.github.CanHub:Android-Image-Cropper:${version}.
Required by:
    project :app
Search in build.gradle files

some idea?

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template and will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template,

_Is important to remember that my work here is volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
