### ISSUE TITLE
[Feat] - Adding circular cropper corner design with custom color support

### ISSUE THREAD

**Issue by bhagyae5308** [CanHub/Android-Image-Cropper#305]
We are using the library to show crop image.  We are having a requirement to show circular crop corner design with custom color. This library doesn't have support for the same. In order to meet the requirement, I have added some changes in the `CropOverlayView` class. Have tried to expose builder methods to set the cropper corner design. 

Checking if can I create a pull request to this branch for the same changes.
Below is the screenshot for the work done based on our requirement.

![Screenshot_20220118-191359_Sample](https://user-images.githubusercontent.com/8956142/149949634-4ed1ee77-5698-454a-aafd-4781d98b90d4.jpg)

**Comment by Canato** [comment]
Nice work! @bhagyae5308 feel free to drop the PR =D
