### ISSUE TITLE
[BUG] - FrameLayout cannot be cast to CropImageView

### ISSUE THREAD

**Issue by krishanunandan** [CanHub/Android-Image-Cropper#306]
I m getting this error

Unable to start activity ComponentInfo{com.test/com.canhub.cropper.CropImageActivity}: java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to com.canhub.cropper.CropImageView

when using 
  CropImageContractOptions options = new CropImageContractOptions(outputUri, new CropImageOptions())
                .setGuidelines(CropImageView.Guidelines.ON_TOUCH);
        cropImage.launch(options);

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template and will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template,

_Is important to remember that my work here is volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
