### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by asnagni** [CanHub/Android-Image-Cropper#308]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version 4.0.0

**Describe the bug**
Hi guys,
	I was able to use the library (version 3.1.3 to be more specific ) for cropping for cropping. It was simple to initiate the cropping from my Actictivity.
	I tried to migrate to version 4.0.0 and it’s not working/building. Basically the interface changed. Would you have a simple example on how to to use the interface from my Activity (java code). Unfortunately we are using Java not Kotlin. Would you have a simple Java example where I can use the library from my Activity like it was possible with version 3.1.3?

Please see the code below for example how we were using it:

		CropImage.activity()
        .setFixAspectRatio(true)
        .setAspectRatio(1, 1)
        .setAllowFlipping(false)
        .start(getActivity(), this);

**To Reproduce**
1. Add the code I provided
2. Make sure to migrate to version 4.0.0
3. Build

**Expected behavior**
Be able to build and run my App

**Media**
Please add screenshots and/or screen recordings to help explain your problem.
We cannot help without more information

**Smartphone (please complete the following information):**
 - Device: Any android device (Galaxy S7, Redmi 9, Google Pixel 4 etc..)
 - OS: Android 10, 11

**Additional context**
none

**Comment by Canato** [comment]
Hey @asnagni welcome. This is not a bug to open an issue. This is how the library work with the latest updates

Please check this two discussions:
https://github.com/CanHub/Android-Image-Cropper/discussions/286
https://github.com/CanHub/Android-Image-Cropper/discussions/236#discussioncomment-1996311

Would be nice if someone create a Java sample for the java users of the library. We already have for fragment, but not for activity, but is basically the same code
