### ISSUE TITLE
[BUG] - Breaking typo in the migration guide

### ISSUE THREAD

**Issue by Dohmanlechx** [CanHub/Android-Image-Cropper#31]
I spent like 1-2 hours trying to migrate the plugin using this [guide](https://github.com/CanHub/Android-Image-Cropper/wiki/%F0%9F%9A%A8-How-to-migrate-Android-Image-Cropper--%F0%9F%9A%A8) but it refused to work. 

But then I found the issue, this [line](https://github.com/CanHub/Android-Image-Cropper/wiki/%F0%9F%9A%A8-How-to-migrate-Android-Image-Cropper--%F0%9F%9A%A8#update-dependencies) in the migration guide is like this:
`implementation 'com.canhub.cropper:android-image-cropper:${version}'`

When it should be like this (just like on the [README](https://github.com/CanHub/Android-Image-Cropper/blob/main/README.md#step-2-add-the-dependency)):
`implementation 'com.github.CanHub:Android-Image-Cropper:${version}'`

Wanted to report here so people trying to migrate don't need to pull out their hair.

**Comment by Canato** [comment]
Thanks @Dohmanlechx fixing it now.
