### ISSUE TITLE
[BUG] - Not working on Vivo phones

### ISSUE THREAD

**Issue by pradeep-orbi** [CanHub/Android-Image-Cropper#314]
- Lib Version 3.3.5
 
**Describe the bug**
On some of the devices, image is shown as blank

**Media**
(https://drive.google.com/file/d/1UNHS8QdOxx5TlrtibBIr9FzQzeIvryJc/view?usp=sharing)

**Smartphone (please complete the following information):**
 - Device: Vivo
 - OS: Android 11

**Comment by Canato** [comment]
Please use the latest library cause many bugs have been fixed

e.g.
> Issue where some devices based on MIUI would not retrieve image from gallery https://github.com/CanHub/Android-Image-Cropper/issues/253
> When TakePictureContract returns false or null return null result. https://github.com/CanHub/Android-Image-Cropper/issues/287
