### ISSUE TITLE
[BUG] - Cannot find getActivityResult()  while migrating from ArthurHub to CanHub

### ISSUE THREAD

**Issue by shweta30sharma** [CanHub/Android-Image-Cropper#316]
CropImage.ActivityResult result = CropImage.getActivityResult(data);

Calling above code which is working fine with arthur image cropper lib.  So, what I mean is getActivityResult() not available in CropImage class.

**Comment by Canato** [comment]
Plus on our [guide](https://github.com/CanHub/Android-Image-Cropper/wiki/%F0%9F%9A%A8-How-to-migrate-Android-Image-Cropper--%F0%9F%9A%A8) you can read

> With one of the latest release we change how we return values from the library call.
> lease check our samples folder (we have one in Java that the community built) so you can use the Activity Contracts. If you don't wanna do this now, you can use the latest version with the deprecated methods https://github.com/CanHub/Android-Image-Cropper/releases/tag/3.3.6

Everything on the guide ^^
