### ISSUE TITLE
[BUG] - No method find when migrating to Can Hub

### ISSUE THREAD

**Issue by shweta30sharma** [CanHub/Android-Image-Cropper#317]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code
No, I cannot reproduce the  bug in the sample code. 

 - Lib Version [e.g. 1.1.0]
 com.github.CanHub:Android-Image-Cropper:4.1.0

**Describe the bug**
I am migrating from 'com.theartofdev.edmodo:android-image-cropper:2.8.+' to 'com.github.CanHub:Android-Image-Cropper:4.1.0'

Steps I followed: 
1. added dependency.
2. added
import com.canhub.cropper.CropImage
import com.canhub.cropper.CropImageActivity

in my activity and the issue I'm facing is I cannot find --- getActivityResult(data) in CropImage class.  Also, getUri() not present in CropImage.ActivityResult. And cannot find activity in CropImage.

ScreenShots are attached for reference

**Expected behavior**

**Media**
<img width="500" alt="snip_1" src="https://user-images.githubusercontent.com/25972739/154274000-5501c3d4-e06d-4f8d-a3e2-12da1d6707c8.png">
<img width="355" alt="snip_2" src="https://user-images.githubusercontent.com/25972739/154274012-d6caa147-7cea-4740-aa9a-7aa80334398f.png">

**Smartphone (please complete the following information):**
 Running on Redmi Note: 7 Pro

Exact Error:

error: cannot find symbol
            CropImage.ActivityResult result = CropImage.getActivityResult(data);
                                                       ^
  symbol:   method getActivityResult(Intent)
  location: class CropImage

**Comment by Canato** [comment]
Next time, please add a title to your issue please =D

## About your issue:
- You need to use Activity Contracts, like we explain in the [migration guide](https://github.com/CanHub/Android-Image-Cropper/wiki/%F0%9F%9A%A8-How-to-migrate-Android-Image-Cropper--%F0%9F%9A%A8)

=============== IMAGE ===============
![image](https://user-images.githubusercontent.com/15942449/154275683-02ab9727-e70d-481c-af19-b454e3ae3af9.png)
=============== IMAGE ===============

## How to solve it
### Option 1
Use version [3.3.6](https://github.com/CanHub/Android-Image-Cropper/releases/tag/3.3.6) of the library, but this is not the most up to date version

### Option 2
Use Activity contracts, like we have in the [sample java](https://github.com/CanHub/Android-Image-Cropper/blob/main/sample/src/main/java/com/canhub/cropper/sample/crop_image_java/app/SCropImageFragmentJava.java)

Would look something like this
```java
private final ActivityResultLauncher<CropImageContractOptions> cropImage =
            registerForActivityResult(new CropImageContract(), presenter::onCropImageResult);
```
In this case you can create the method `onCropImageResult` on your presenter class or change `presenter::onCropImageResult` to a method in the same file, like `egisterForActivityResult(new CropImageContract(), ::yourAnswerMethod);`

That should have the signature:
`public void yourAnswerMethod(@NonNull CropImageView.CropResult result) { ... }`

And to call the crop, you will need:
```java
CropImageContractOptions options = new CropImageContractOptions(null, new CropImageOptions())

cropImage.launch(options);
```

On the options you can use the settings you prefer, please check the sample code for it

**Comment by shweta30sharma** [comment]
@Canato I've changed my version to 3.3.6

My code is building fine and app is getting installed too, but my cropped image is not uploading.

result.getUriContent() is

content://com.google.android.apps.photos.contentprovider/0/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F278973/ORIGINAL/NONE/image%2Fjpeg/39327663

Also,

result.getUriContent().getPath() is

/my_images/Pictures/cropped2207926145134794118.jpg


Do you think there is some issue with the path.

<img width="509" alt="snip_1" src="https://user-images.githubusercontent.com/25972739/154430461-cbfb1a69-b5ce-4fc4-9fa5-c441ba3ba030.png">

**Comment by shweta30sharma** [comment]
Getting this error in LogCat.

Unable to decode stream: java.io.FileNotFoundException: /my_images/Pictures/cropped981662640046948234.jpg: open failed: ENOENT (No such file or directory)

**Comment by Canato** [comment]
`result.getUriContent().getPath();` should not be use, please use one of the methods we have in the README and on the sample codes, like:

`result.uriContent` for `content://...` schema or `result.getUriFilePath(context, true)` for `file://` schema

**Comment by shweta30sharma** [comment]
Thanks a lot man! @Canato .  Using result.getUriFilePath(context, true) solved problem.

**Comment by Canato** [comment]
Happy that we got there \o/!!!
