### ISSUE TITLE
Unable to resolve com.canhub ?

### ISSUE THREAD

**Issue by RageshAntony** [CanHub/Android-Image-Cropper#318]
After adding the library and resync gradle , The classes not resolve 

The package com.canhub showing 'unable to resolve ' error 

When trying to run build , I am getting this error :

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugKotlin'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform artifact 'Android-Image-Cropper.aar (com.github.CanHub:Android-Image-Cropper:3.3.5)' to match attributes {artifactType=android-res}.
      > Execution failed for JetifyTransform: /Users/sudharsanarajalingam/.gradle/caches/modules-2/files-2.1/com.github.CanHub/Android-Image-Cropper/3.3.5/2710c0ba7adfcfa93c27c2519a6ec7c3ddeeb54a/Android-Image-Cropper-3.3.5.aar.
         > Failed to transform '/Users/sudharsanarajalingam/.gradle/caches/modules-2/files-2.1/com.github.CanHub/Android-Image-Cropper/3.3.5/2710c0ba7adfcfa93c27c2519a6ec7c3ddeeb54a/Android-Image-Cropper-3.3.5.aar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)
```

My current gradle version is 5.6.1 . Is this a reason ? (can't update due to some breaking changes)

I tried clean project , invalidate and restart etc , no solution 

Also checked my gradle deps , they are correct 

Please help me ?

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template and will help me to help you.

(e.g. you didn't share the library version, if you could reproduce on the sample app, which language you are on... just saying "Also checked my gradle deps , they are correct" doesn't help me to understand, would be nice to see the code you are using.. etc)

I will **close** 🔴  this issue so you can reopen following the template,

_Is important to remember that my work here is volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
