### ISSUE TITLE
[BUG] - Could not find com.github.canhub:android-image-cropper:4.1.0.

### ISSUE THREAD

**Issue by Morons** [CanHub/Android-Image-Cropper#320]
```
repositories {
		google()
		mavenCentral()
		gradlePluginPortal()
		maven { url "https://jitpack.io" }
		maven { url "https://plugins.gradle.org/m2/" }
		maven { url "https://dl.bintray.com/kotlin/kotlin-eap" }
	}

``` 
**I have several project with the same issue!**

`ext {android_image_cropper_version = "4.1.0"}`
```
	// Android-Image-Cropper
	implementation "com.github.canhub:android-image-cropper:$android_image_cropper_version"
```
Gradle Sync works as expected and library seem to download perfectly no errors BUT:
Upon Build->Rebuild Project the Error occurs

Further Investigation reveals in External Libraries "Gradle:com.github" does not exist - I can see al my other implemented Libraries there
there fore Gradle is correct in NOT finding it!
**I am using**
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip`
```
Android Studio Bumblebee | 2021.1.1 Patch 1
Build #AI-211.7628.21.2111.8139111, built on February 1, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: external.system.auto.import.disabled=true, ide.instant.shutdown=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: wu.seal.tool.jsontokotlin (3.7.2), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), com.developerphil.adbidea (1.6.4), de.ohmesoftware.parcelablegenerator (0.7.1), org.intellij.plugins.markdown (211.7142.37)
```

**Comment by thekingrenz23** [comment]
> 

![Screen shot](https://user-images.githubusercontent.com/24559541/155249251-5dae0e5f-54d7-40db-9ee2-8a7012e043a8.png)

The same issue tried your solution

**Comment by dovydaskaupas** [comment]
I am still facing the same issue while using **com.github.CanHub:Android-Image-Cropper** (copied it direclty from the comment above)

![dependency issue 23 02 22](https://user-images.githubusercontent.com/24279159/155294816-845f3dcf-0cfc-4f53-aa9e-57d8e9f298ca.PNG)

**Comment by jaikumar0702** [comment]
Hi @Canato  I am facing the same issue , could you please help me?
Actually it showing error when i am adding Maven url{  }

![Screenshot (191)](https://user-images.githubusercontent.com/70019204/155987102-7d5b0f9a-6096-4bd5-8d32-b1c2254942b2.png)
![Screenshot (190)](https://user-images.githubusercontent.com/70019204/155987106-cb9c820c-e166-4af2-b449-68d2b052a9c8.png)
![Screenshot (192)](https://user-images.githubusercontent.com/70019204/155987109-b65ffe13-21ba-4a26-bbc4-a00c70501855.png)

**Comment by Canato** [comment]
Thanks for the images @jaikumar0702.

try to add `mavenCentral()` to your code, like:

```kt
allprojects {
     repositories {
       mavenCentral()
       maven { url 'https://jitpack.io' }
     }
  }
```

And run `File > Invalidate Caches > Invalidate and Restart` option to see if works

**Comment by jaikumar0702** [comment]
I have tried same but still getting this error
![Screenshot (193)](https://user-images.githubusercontent.com/70019204/155990079-2d043c77-780d-469a-a19d-efb1657887d3.png)
r

**Comment by Canato** [comment]
@jaikumar0702 still with the issue? not sure what I can help with =// look like maven is not working for you, is working for other libs ?

**Comment by Vladimir999666119** [comment]
Добрый день. У меня проблема с добавлением библиотеки.. и прошлую версию от Артура тоже не ставиться. А точнее не находит её андройд студия. Посмотрел кучу всего в интернете ничего не помогает. Вроде все сделал по инструкции. Хотя пробовал другую библиотеку похожую на эту тоже не получается. Хотя другую библиотеку добавил без проблем это пикасо
![IMG_20220411_195216_774](https://user-images.githubusercontent.com/103446783/162791173-ca5983c8-b553-4b80-8aaa-ba932a34f14a.jpg)
Помогите пожалуйста

**Comment by Vladimir999666111** [comment]
Good afternoon. I have a problem with adding a library.. and the last version from Arthur is also not put. Or rather, the android studio does not find it. I looked at a bunch of things on the Internet, nothing helps. It seems to have done everything according to the instructions. Although I tried another library similar to this one, it also does not work. Although I added another library without any problems it's Picasso

> > Добрый день. У меня проблема с добавлением библиотеки.. и прошлую версию от Артура тоже не ставиться. А точнее не находит ее андройд студия. Посмотрел кучу всего в интернете ничего не помогает. Вроде все сделал по инструкции. Хотя поиски похожие на это тоже не получаются. Несмотря на то, что другие ресурсы были добавлены без проблем, помогите ![IMG_20220411_195216_774](https://user-images.githubusercontent.com/103446783/162791173-ca5983c8-b553-4b80-8aaa-ba932a34f14a.jpg)пожалуйста
> 
> Извините, русский не входит в число моих языков

Good afternoon. I have a problem with adding a library.. and the last version from Arthur is also not put. Or rather, the android studio does not find it. I looked at a bunch of things on the Internet, nothing helps. It seems to have done everything according to the instructions. Although I tried another library similar to this one, it also does not work. Although I added another library without any problems it's Picasso

**Comment by Vladimir999666111** [comment]
and where to find it in Java. why only kotlin? Arthur had Java, and you had Kotlin.

**Comment by TranHuy2709** [comment]
> I finally found the Solution: With Android Studio Bumblebee, you must make this steps:
> 
> 1. Add this code in `build.gradle`
> 
> ```
> buildscript {
>     repositories {
>         google()
>         mavenCentral()
>         maven { url 'https://jitpack.io' }
>     }
>     dependencies {
>         classpath "com.android.tools.build:gradle:7.0.4"
>         // Some dependencies
>     }
> }
> 
> allprojects {
>     repositories {
>         maven { url 'https://jitpack.io' }
>     }
> }
> 
> task clean(type: Delete) {
>     delete rootProject.buildDir
> }
> ```
> 
> 2. Add this code in `settings.gradle`
> 
> ```
> import org.gradle.api.initialization.resolve.RepositoriesMode
> 
> dependencyResolutionManagement {
>     repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
>     repositories {
>         google()
>         mavenCentral()
>         maven { url 'https://jitpack.io' }
>         jcenter() // Warning: this repository is going to shut down soon
>     }
> }
> rootProject.name = "AppName"
> include ':app'
> ```
> 
> It works for me after that and I can Import the library inside XML

It solved my problem. Thank you so much
