### ISSUE TITLE
[Feat] - Add Skip Editing option to CropImageContractOptions

### ISSUE THREAD

**Issue by Devenom1** [CanHub/Android-Image-Cropper#323]
I've been using the original library and recently discovered this one. Since I required a feature in the original library I've added it to my project and modified the source code.

This is the feature I had added to the original library. I had an option to skip editing the image entirely because I don't require users to edit the images everywhere in my app. I basically want to skip the editing step. So if I pass an option like `setSkipEditing(true)` the CropImageActivity should directly return the entire image (after any processing) without any user interaction.

I'll try and submit a PR

**Comment by Canato** [comment]
Looks nice @Devenom1 

But in the case the user do not need to crop the image, why we don't just retrieve it directly without the library usage?

**Comment by Devenom1** [comment]
Hi @Canato, I had thought the same before but this is why adding this option became very useful.

1. In our app we need users to pick images in multiple places. It's only in some places that we in the app we don't need the images edited. Adding this option lets us keep the UI consistent.
2. The library provides the automatic editing feature that proves to be very useful. Like we can set the quality of the image, aspect ratio of the image, etc and the library takes care of this for us. In some places we may just not need the manual editing option like cropping, flipping or rotating but we still need other features used in this library like setting image quality, resolution, aspect ratio etc.

**Comment by Canato** [comment]
Nice, let's merge when the PR is ready
