### ISSUE TITLE
[BUG] -Cannot find the setImagePickerContractOptions method in the CropImageContractOptions Class 

### ISSUE THREAD

**Issue by gaganO7** [CanHub/Android-Image-Cropper#327]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version [e.g. 1.1.0]
 
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Media**
Please add screenshots and/or screen recordings to help explain your problem.
We cannot help without more information

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3XL]

**Additional context**

Hey @Canato i was using your library and stumble upon one problem which is the below method

setImagePickerContractOptions(
PickImageContractOptions(includeGallery = true, includeCamera = false)
)
this above method, i cannot find in your CropImageContractOptions file, so where i can find this method.

**Comment by Canato** [comment]
@gaganO7 please complete the template information. Otherwise I need to ask the same information to help you

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template and will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template,

_Is important to remember that my work here is volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
