### ISSUE TITLE
[BUG] - Wrong image behaviour when changing scale type

### ISSUE THREAD

**Issue by Canato** [CanHub/Android-Image-Cropper#328]
Happen on Sample code - check video

 - Lib Version `4.1.0`
 
**Describe the bug**
Check video

**To Reproduce**
1. Open sample app
2. First button `Sample using cropimageview`
3. Settings option (FAB right side)
4. Select another Scale Type as `Center Crop`
5. Observe image behaviour

**Media**

https://user-images.githubusercontent.com/15942449/157114811-aabcf7a8-a8bf-476d-852b-e2d6eb67ae79.mp4

**Comment by vanniktech** [comment]
What exactly is wrong here?

**Comment by prasad-333** [comment]
@vanniktech @Canato Looks for some testing purpose someone might have changed the image but anyways this is fixed as per expected behavior. Kindly review the PR #522

**Comment by vanniktech** [comment]
Thanks for the fix!
