### ISSUE TITLE
What would be the easiest way to add one more button in built-in activity?

### ISSUE THREAD

**Issue by pmrzygweb** [CanHub/Android-Image-Cropper#329]

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template and will help me to help you.

If this is a question only you can use [discussions](https://github.com/CanHub/Android-Image-Cropper/discussions)

I will **close** 🔴  this issue so you can reopen following the template,

_Is important to remember that my work here is volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
