### ISSUE TITLE
Bad class file error :  class file has wrong version 55.0, should be 52.0

### ISSUE THREAD

**Issue by pradeep-orbi** [CanHub/Android-Image-Cropper#330]
- Lib Version 3.3.5
 
**Describe the bug**'
I'm getting this error
/files/databinding/ActivityImageCropBinding.java:15: error: cannot access CropImageView
import com.canhub.cropper.CropImageView;
                         ^
  bad class file: /Users/pradeepreddy/.gradle/caches/transforms-3/a44d3bdf15df3609f438fbe5aa746754/transformed/jetified-Android-Image-Cropper-3.3.5-api.jar(com/canhub/cropper/CropImageView.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

**Additional context**
Tried all the solutions suggested in bugs with same error, but nothing is working.
https://github.com/CanHub/Android-Image-Cropper/issues/247
I'm using Android studio Bumblebee. Also tried in android studio Arctic fox version also. Same issue.
I'm using MacBook  M1 Chip.

Can somebody help me in resolving this issue

**Comment by Canato** [comment]
Hey @pradeep-orbi what are you Java Version, SDK version, Gradle version, JVM, Java SE

The information from your project and from your machine too. Important to check if you have multiple Java version installation (less liked to happen, but worth to take a look)

**Comment by pradeep-orbi** [comment]
❯ java -version
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Homebrew (build 17+0)
OpenJDK 64-Bit Server VM Homebrew (build 17+0, mixed mode)

compileSdkVersion 30
gradle-6.8.1-bin.zip

<img width="1000" alt="Screenshot 2022-03-10 at 3 54 25 PM" src="https://user-images.githubusercontent.com/78588549/157642479-8fb2f167-f55b-4c27-a0d7-73818bb37666.png">

**Comment by Canato** [comment]
Can you try to update to Java 11 ?

**Comment by pradeep-orbi** [comment]
Any idea on what is the root cause for this error ?
class file has wrong version 55.0, should be 52.0

**Comment by Canato** [comment]
Did you try Java 11?

**Comment by pradeep-orbi** [comment]
yes, did not work.

**Comment by Canato** [comment]
> Bad class file error : class file has wrong version 55.0, should be 52.0 

It means your Java runtime version is 1.8, but your compiler version (javac) is 11. 
To simply solve it, just advance your JVM version to 11

1. Select "File" -> "Project Structure".
2. Under "Project Settings" select "Project"
3. From there you can select the "Project SDK".

But if you don't want to change the Java runtime version, then do the following steps:
- `JAVA_HOME= "your jdk v11 folder path"`, to make sure jdk is also v11 and use `java -version` and `javac -version` again to ensure it


[more information](https://stackoverflow.com/a/4692743/3117650)

**Comment by pradeep-orbi** [comment]
After changing to Java 11, i was getting another error, which was specific to MacBook M1 chip. Found the solution from this link.
[](https://stackoverflow.com/questions/62131564/a-failure-occurred-while-executing-org-jetbrains-kotlin-gradle-internal-kaptexec)
It got resolved after adding the following to project build.gradle file
```
allprojects {
    // ADD THE FOLLOWING
    configurations.all {
        resolutionStrategy {
            force 'org.xerial:sqlite-jdbc:3.34.0'
        }
    }
}
```
