### ISSUE TITLE
[Feat] - Keep EXIF data

### ISSUE THREAD

**Issue by StampixSMO** [CanHub/Android-Image-Cropper#331]
**Is your feature request related to a problem? Please describe.**
After cropping an image, all original exif data is removed.

**Describe the solution you'd like**
The `Orientation` value being reset is fine, but the other metadata also seems to be missing. Can we keep the other data?

**Describe alternatives you've considered**
Reading out the EXIF before cropping and then placing it back, but that's quite the workaround (and you have leave out `Orientation`).

**Additional context**
/

**Comment by Canato** [comment]
Hey @StampixSMO sorry not sure what you mean by `EXIF data` 

And btw, can you please clear the text issue with the templates parts you are not using? Just to make the read easier ^^

**Comment by StampixSMO** [comment]
@Canato Thanks for the quick response, by exif data I mean the exif headers that are present in JPG files.

They contain data such as e.g. the maker of the smartphone, etc .. The latitude and longitude of the picture taken ...

All this data gets cleared when cropping.

**Comment by Canato** [comment]
Interesting. Indeed would be nice to create new one, with the information of the device it was cropped, when was cropped etc!

Would be great to be done. Feel free to drop the PR. And will add some labels to see if anyone else feel like doing it ^^ 

If no one take ownership of this feature the robot will close automatically in some days =p

**Comment by StampixSMO** [comment]
I tried to do this but I'm not sure about the performance. You can use Apache Commons Imaging: https://commons.apache.org/proper/commons-imaging/

I didn't succeed yet, might have a look again later!
