### ISSUE TITLE
[Feat] - Adding different type of Exception for crop cancel.

### ISSUE THREAD

**Issue by rempawl** [CanHub/Android-Image-Cropper#332]
Is it possible to add some CropCancellationException instead Exception(msg) here?
```
 object CancelledResult : CropImageView.CropResult(
        originalBitmap = null,
        originalUri = null,
        bitmap = null,
        uriContent = null,
        error = Exception("cropping has been cancelled by the user"),
        cropPoints = floatArrayOf(),
        cropRect = null,
        wholeImageRect = null,
        rotation = 0,
        sampleSize = 0
    )
```
 then it would be more convenient to differentiate it from other exceptions using is operator instead ==

**Comment by Canato** [comment]
Good suggestion. Yeah free to people to create a `CropException` class so we can use in our Exceptions.

Feel free to drop a PR or let's see if someone will get this
