### ISSUE TITLE
[BUG] - AlertDialog can always be cancelled, which leads to a black CropActivity

### ISSUE THREAD

**Issue by xvlaze** [CanHub/Android-Image-Cropper#334]
- Lib Version 4.1.0
 
**Describe the bug**
When extending `CropImageActivity`, the `AlertDialog` is cancellable if touched outside. If the user accidentally touches outside the dialog, it is left into a black `CropImageActivity` and the dialog never comes back. If trying to override the method after my `CropImageActivity` extension's `onCreate`:

```
override fun showImageSourceDialog(openSource: (Source) -> Unit) {
        AlertDialog.Builder(this)
            .setTitle("sample title")
            .setCancellable(false) // Does not work :(
            .setItems(
                arrayOf(
                    getString(R.string.pick_image_camera),
                    getString(R.string.pick_image_gallery),
                )
            ) { _, position -> openSource(if (position == 0) Source.CAMERA else Source.GALLERY) }
            .show()
    }
```
...no custom title is assigned, plus the dialog is still cancellable even after told otherwise. The debugger never enters this method.

**To Reproduce**
1. Create a new `CropImageActivity` just as shown in the [documentation](https://github.com/CanHub/Android-Image-Cropper#extend-to-make-a-custom-activity).
2. Touch outside the dialog once it appears.

**Expected behavior**
The dialog should not be cancelled on touch outside.

**Media**
Please add screenshots and/or screen recordings to help explain your problem.
We cannot help without more information

**Smartphone (please complete the following information):**
 - Device: Huawei P40 Pro, Nexus 5 (emulated).
 - OS: Android 10, Android 12 respectively.

**Comment by Canato** [comment]
Indeed, good spot. Will work on listen to dismiss action when I have time,

Free to any one jump in and fix this

**Comment by Canato** [comment]
Yes @RemiMabsout please =D

**Comment by RemiMabsout** [comment]
@Canato i may have a fix but before i try, is the fact that it's an AlertDialog important ? Because it seems like for unknown reasons that i can't use setCanceledOnTouchOutside() with an AlertDialog (which is weird 'cause AlertDialog extends Dialog and Dialog has the method setCanceledOnTouchOutside() ) and btw setCancelable() is for the back key so keeping it will fix a bug that has not happened yet which is closing the dialog with the back key.
