### ISSUE TITLE
[Feat] - Set Fix width for cropper 

### ISSUE THREAD

**Issue by HafijurRahmanEjaro** [CanHub/Android-Image-Cropper#337]
Can we fix the width only height can crop?

**Comment by Canato** [comment]
Hey @HafijurRahmanEjaro sorry I missed this, is not using the template and I didn't spot it.

I will move to discussions. But yeah! You can.

Suggestions to use `setMinCropResultSize(x, y)` and `setMax...` using the values you wanna fixed for your width as min and max values.
