### ISSUE TITLE
[Feat] - does a java version exist ?

### ISSUE THREAD

**Issue by Dayvin30** [CanHub/Android-Image-Cropper#338]
does a java version exist ?

**Comment by Canato** [comment]
Hey @Dayvin30 welcome to the library. 

The best place to ask questions would be in [discussions](https://github.com/CanHub/Android-Image-Cropper/discussions)

You can spot on the README:

[Java Sample](https://github.com/CanHub/Android-Image-Cropper/tree/main/sample/src/main/java/com/canhub/cropper/sample/crop_image_java)

This library works with Java and Kotlin code
