### ISSUE TITLE
Cannot resolve symbol 'CropImage'

### ISSUE THREAD

**Issue by hussi-azam** [CanHub/Android-Image-Cropper#339]
I have added  implementation 'com.github.CanHub:Android-Image-Cropper:4.2.0' in gradle, but i am unable to import CropImage and CropImageActivity

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template and will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template,

_Is important to remember that my work here is volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
