### ISSUE TITLE
[BUG] - Error while Launching CropImage

### ISSUE THREAD

**Issue by hussi-azam** [CanHub/Android-Image-Cropper#340]
class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath

**Comment by Canato** [comment]
> Please check previous solved issues, small search always help


Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template and will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template,

_Is important to remember that my work here is volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
