### ISSUE TITLE
Cropped Image uri not working

### ISSUE THREAD

**Issue by CHetan7-web** [CanHub/Android-Image-Cropper#342]
After cropping the image , uri of image is showing location like this  /my_images/Pictures/cropped6141929761209295842.png: open failed: ENOENT (No such file or directory)
I know it is related to scoped storage and i can't do anything because startCrop is only returning URI which doesn't exist

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template and will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template,

_Is important to remember that my work here is volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
