### ISSUE TITLE
[BUG] - Android-image-cropper ersion 4.2.0

### ISSUE THREAD

**Issue by Blader-1** [CanHub/Android-Image-Cropper#349]
I present the following problem with the android-image-cropper library since I am implementing it in my android studio project and well I need the library to crop the images, I have version 4.2.0 but in my code it generates an error syntax, the truth is I don't know much about android studio because I'm new and I would like to receive help from someone more experienced than me to solve this error, I am attaching images or videos of the problem immediately.
![image](https://user-images.githubusercontent.com/95068777/162000394-7d412a2c-30f9-498a-bd68-6e3ee80e0c48.png)

**Comment by Canato** [comment]
Hey @Blader-1 check the [Java Saample](https://github.com/CanHub/Android-Image-Cropper/blob/main/sample/src/main/java/com/canhub/cropper/sample/crop_image_java/app/SCropImageFragmentJava.java)

We don't call `CropImage.activity` we should call by contract
`private final ActivityResultLauncher<CropImageContractOptions> cropImage = registerForActivityResult(new CropImageContract(), presenter::onCropImageResult);`

Get the sample code in your machine and probably this can guide you
