### ISSUE TITLE
Refactor BitmapUtils to kotlin

### ISSUE THREAD

**Issue by Canato** [CanHub/Android-Image-Cropper#35]

**Comment by SanjayDevTech** [comment]
@Canato I think I can work on this issue... Can I assign myself??

**Comment by Canato** [comment]
@SanjayDevTech yes please, let's do this. I'm doing the #41 

This will put the whole code base into kotlin finally!!!

**Comment by SanjayDevTech** [comment]
@Canato Please review my PR 😀

**Comment by SanjayDevTech** [comment]
@Canato 😅 Java -> Kt Converter issues solved
