### ISSUE TITLE
[Feat] - Perspective Feature

### ISSUE THREAD

**Issue by alpeshrathod25** [CanHub/Android-Image-Cropper#350]
Can you please explain how to manage image perspective feature using this library? I have gone through the code and looking for this feature if you can help.

**Comment by Canato** [comment]
Not sure what you mean by image perspective. Could you provide a example of the result expected? 😬

**Comment by alpeshrathod25** [comment]
Uploading XRecorder_10042022_193852.mp4…

Please look at this.

**Comment by Canato** [comment]
> Uploading XRecorder_10042022_193852.mp4…
> 
> Please look at this.

You need to let the uploading finish ^^ @alpeshrathod25  hahahaha

**Comment by alpeshrathod25** [comment]
> > Uploading XRecorder_10042022_193852.mp4…
> > Please look at this.
> 
> You need to let the uploading finish ^^ @alpeshrathod25 hahahaha

Hahaha, sorry please check on this given link.

https://www.dropbox.com/s/hn0ncir1fez9btz/xrecorder_10042022_193852.mp4?dl=0

**Comment by Canato** [comment]
The library does not have this feature, will let this issue open in case someone wanna develop it.

In case no one take ownership the issue will close it self
