### ISSUE TITLE
Cannot resolve method 'getUri' in 'ActivityResult'

### ISSUE THREAD

**Issue by kmrn777** [CanHub/Android-Image-Cropper#351]
I have 2 fragments Add and Profile and I have public void onActivityResult in both of them. I get same errors in both of them: Uri image = result.getUri();   and   Uri uri = result.getUri();   can you help me fix it?
![Screenshot (340)](https://user-images.githubusercontent.com/94496584/162746118-08e9bed5-33ed-4798-939f-02184a36fd5f.png)
![Screenshot (341)](https://user-images.githubusercontent.com/94496584/162746124-61a574bb-b4dc-41fc-ab24-62c5c11807ab.png)

**Comment by Canato** [comment]
Hey @kmrn777 welcome to the library

please check the [README](https://github.com/CanHub/Android-Image-Cropper/blob/main/README.md) or the [How to migrate Android Image Cropper from arthur hub repo](https://github.com/CanHub/Android-Image-Cropper/wiki/%F0%9F%9A%A8-How-to-migrate-Android-Image-Cropper--%F0%9F%9A%A8) guide or the [java samples](https://github.com/CanHub/Android-Image-Cropper/tree/main/sample/src/main/java/com/canhub/cropper/sample/crop_image_java)/[kotlin samples](https://github.com/CanHub/Android-Image-Cropper/tree/main/sample/src/main/java/com/canhub/cropper/sample/crop_image) of how to use the library. 

`onActivityResult` is deprecated and not supported since release [4.0.0](https://github.com/CanHub/Android-Image-Cropper/releases/tag/4.0.0). The latest release that works is [3.3.6](https://github.com/CanHub/Android-Image-Cropper/releases/tag/3.3.6)

We now use Activity Contract.

Will close this cause the solution is spread across some places, if you need more help let me know 😬

**Comment by kmrn777** [comment]
on my build.gradle (module) i have     implementation 'com.github.CanHub:Android-Image-Cropper:3.3.6'
so why i still have this error? i did migrate everything correctly.

**Comment by kmrn777** [comment]
@Canato i don't know how to change my code now in order to make it work.

**Comment by kmrn777** [comment]
@Canato i posted it on first issue

**Comment by kmrn777** [comment]
![Screenshot (341)](https://user-images.githubusercontent.com/94496584/162774035-40d0b024-da7e-440e-a029-c89219b849f7.png)

**Comment by kmrn777** [comment]
@Canato do you see it now?

**Comment by Canato** [comment]
> ![Screenshot (341)](https://user-images.githubusercontent.com/94496584/162774035-40d0b024-da7e-440e-a029-c89219b849f7.png)

I this screenshot I can see `Uri uri = result.getUri();` please use `Uri uri = result.getBitmap(context)`

**Comment by Canato** [comment]
1 - You need to provide the correct context. Just writing `context` without defining a variable will not magically solve the problem. Time to google a little and learn a little more =). This shows a little laziness from your side, which makes me lazy to help. I'm trying to help you here, but I need to know you are really trying. Not just copy and paste my code without trying to understand it. 

2 - What are the options that appear to complete when you type `... = result. ` normally Android Studio will provide some suggestions to complete, like this case:
<img width="681" alt="Screenshot 2022-04-11 at 16 37 11" src="https://user-images.githubusercontent.com/15942449/162777719-381bf881-fd49-4e3d-ba96-b71f737b1d22.png">
What appears to you? _(please attach a screenshot)_

**Comment by kmrn777** [comment]
![Screenshot (344)](https://user-images.githubusercontent.com/94496584/162778342-daae9492-c486-4919-b8ad-5cd05d17d78f.png)
@Canato i am trying, i did google much but im seriously stuck on this uri

**Comment by Canato** [comment]
Don't worry you will get there. =)

Can you try `Uri uri = result.uriContent`

**Comment by Canato** [comment]
Sorry, this is Java, you probably need 
`Uri uri = CropImage.getActivityResult(data).getUriContent();`

But try to change and learn kotlin and activity contracts. 

Working with old tools will make your life harder =/

**Comment by kmrn777** [comment]
@Canato i will learn kotlin, i agree with you. but i already started this project in java so till the end you know. btw, i did change into Uri uri = CropImage.getActivityResult(data).getUriContent(); i still have error. 
![Screenshot (345)](https://user-images.githubusercontent.com/94496584/162838076-53f03d45-4dba-4039-8fb0-37e8170d4cb7.png)

**Comment by Canato** [comment]
what are the options after the `...Result(data).` ??

Sorry for not been helpful as much as I would like, but this is old code and Java so I need to remember the context, any of my projects uses Javas of this old version of the library =/

**Comment by kmrn777** [comment]
yeah i understand you, don't worry. here:
![Screenshot (346)](https://user-images.githubusercontent.com/94496584/162940250-2b1d15d6-22bf-43fa-b9e4-4a8b5e81b7c7.png)

**Comment by Canato** [comment]
Sorry @kmrn777 no more ideas here, would need to spend some time looking into the code for a better help =((

Hopefully you can return to the code base in this release tag and check the sample code to see what works

**Comment by vishalkale** [comment]
@kmrn777 Workaround is to create a Kotlin extension function like

**_GetUri.kt_**
`fun CropImage.ActivityResult?.getUri(): Uri? {
    return this?.uriContent
}`

and in `onActivityResult` -> `Uri uri = GetUriKt.getUri(CropImage.getActivityResult(data));`

Hope this helps you! 👍

**Comment by kmrn777** [comment]
@vishalkale thank you but i'm writing on java :(

**Comment by vishalkale** [comment]
> @vishalkale thank you but i'm writing on java :(

You don't have to convert any existing files to Kotlin only 1 extension file and it should work.

**Comment by kmrn777** [comment]
@vishalkale wait what do you mean? again.

**Comment by vishalkale** [comment]
Just create 1 Kotlin file `GetUri.kt` which contains 
`fun CropImage.ActivityResult?.getUri(): Uri? { return this?.uriContent } `

**Comment by kmrn777** [comment]
@vishalkale on fragments where this Profile and Add java classes containes?

**Comment by kmrn777** [comment]
![Screenshot (354)](https://user-images.githubusercontent.com/94496584/163606503-41f30f58-bcc9-4a0e-9710-867dca53d268.png)
@vishalkale like this?

**Comment by lazyDevPro** [comment]
@kmrn777 Here is the solution:
 @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {
            if (resultCode == RESULT_OK) {
                Uri resultUri = CropImage.getPickImageResultUriContent(MainActivity.this, data);
                Log.e(TAG, "onActivityResult: "+resultUri.toString());
            }
        }
    }

**Comment by kmrn777** [comment]
@lazyDevPro do you know what i should do now? because yeah i checked your code it doesn't work.

**Comment by vishalkale** [comment]
> ![Screenshot (354)](https://user-images.githubusercontent.com/94496584/163606503-41f30f58-bcc9-4a0e-9710-867dca53d268.png) @vishalkale like this?

Just get rid of `class GetUri` and only keep function 
` fun CropImage.ActivityResult?.getUri(): Uri? { return this?.uriContent } `

**Comment by kmrn777** [comment]
@vishalkale my Profile fragment is fine now, but Add fragment there's this new error:
![Screenshot (356)](https://user-images.githubusercontent.com/94496584/163711841-7e8b738c-572f-40f8-a5a7-74edd3e3ecd2.png)

**Comment by lazyDevPro** [comment]
@kmrn777 Here is the solution working 100% worked for me:
Step 1:
![2022-04-18_01-53-44](https://user-images.githubusercontent.com/49026890/163731038-63a524c4-8123-4d35-8318-c1c44b8ccb9f.jpg)

Step 2: You may get an error while syncing cause of the new way of android Gradle settings, just remove highlighted code from `build.gradle` and sync
![2022-04-18_01-54-38](https://user-images.githubusercontent.com/49026890/163731071-e6c0a112-3ab6-4443-bca7-029ecda9a729.jpg)

Explaniation:
@vishalkale answer is right but if you have made your project work on java by default then it is not compiling the kotlin code to make it work you need to add kotlin compiler in the project the above, it is the automated step provided by android to add the kotlin compiler.

@Canato I think the migration guide has error and it won't gonna work because @kmrn777 issue is correct there is no getUri for the java code can work in kotlin but not in JAVA so you can update the migration guide.

**Comment by kmrn777** [comment]
@lazyDevPro hello. i did all your steps but i still have this same error:
![Screenshot (357)](https://user-images.githubusercontent.com/94496584/163798447-521d92d4-12e7-4c8e-bb3e-4862cea149e4.png)

**Comment by Canato** [comment]
@kmrn777 you probably need to add `@JvmStatic` to your method inside you new class

> I think the migration guide has error and it won't gonna work because @kmrn777 issue is correct there is no getUri for the java code can work in kotlin but not in JAVA so you can update the migration guide.

Indeed @lazyDevPro we need to update the guide, someone who does this migration could provide new steps. The library changed so much so far.

**Comment by lazyDevPro** [comment]
@kmrn777 remove `class GetUri{` and only keep `fun CropImage.ActivityResult?.getUri(): Uri? { return this?.uriContent }` Like shown in the image

![2022-04-20_01-21-42](https://user-images.githubusercontent.com/49026890/164084483-bd66744c-4b92-4d2d-9c04-8f288e53de19.jpg)

then in main `onActivityResult()`

![2022-04-20_01-22-59](https://user-images.githubusercontent.com/49026890/164084758-b0d49e72-d198-4575-912d-971e52979d09.jpg)

**Comment by lazyDevPro** [comment]
> @kmrn777 you probably need to add `@JvmStatic` to your method inside you new class
> 
> > I think the migration guide has error and it won't gonna work because @kmrn777 issue is correct there is no getUri for the java code can work in kotlin but not in JAVA so you can update the migration guide.
> 
> Indeed @lazyDevPro we need to update the guide, someone who does this migration could provide new steps. The library changed so much so far.

I'll surely do that, the current solution needs a kotlin class and kotlin compiler in java code and that is not very efficient I am looking for a solution by using java only and after that, I'll share the details to update the migration guide.

**Comment by lazyDevPro** [comment]
@vishalkale can you explain how this function `fun CropImage.ActivityResult?.getUri(): Uri? { return this?.uriContent }` accesses the `ActivityResult` constructor to get `uriContent`? and can it be replicated in java?

**Comment by kmrn777** [comment]
@lazyDevPro hey man. so i exactly did what you've said. GetUri.kt is fine, Profile fragment is also fine, but Add fragment there's an error. you will see from screenshots:
![Screenshot (388)](https://user-images.githubusercontent.com/94496584/164105444-d9f9d550-aa09-4622-9555-706db1cd2199.png)
![Screenshot (389)](https://user-images.githubusercontent.com/94496584/164105446-b79e61a2-ee08-4b18-985e-f2e70f9083a3.png)
![Screenshot (390)](https://user-images.githubusercontent.com/94496584/164105449-d9ae3217-89b2-462d-9c9b-32f69a24c61f.png)

**Comment by lazyDevPro** [comment]
@kmrn777 follow this one now https://github.com/CanHub/Android-Image-Cropper/issues/351#issuecomment-1100945480

**Comment by kmrn777** [comment]
@lazyDevPro i did that one too, but no success

**Comment by lazyDevPro** [comment]
> @lazyDevPro i did that one too, but no success

@kmrn777 Please share a screenshot of your `build.gradle`

**Comment by kmrn777** [comment]
![Screenshot (393)](https://user-images.githubusercontent.com/94496584/164457298-c1f04610-391d-42a9-8878-077687ec3cb6.png)
![Screenshot (394)](https://user-images.githubusercontent.com/94496584/164457309-792ac81c-5e93-46bf-97ac-68a4fb3a8681.png)
![Screenshot (395)](https://user-images.githubusercontent.com/94496584/164457312-35381654-78d1-4724-99c7-eec5027dbef3.png)
@lazyDevPro

**Comment by kmrn777** [comment]
@lazyDevPro 
![Screenshot (404)](https://user-images.githubusercontent.com/94496584/164701226-d7bae510-e9ec-45f0-af7b-ce030fe9a7a4.png)
i do as you say and i receive it. do you have teams maybe? you could do it on my laptop

**Comment by kmrn777** [comment]
@lazyDevPro 
my version of android:
![Screenshot (405)](https://user-images.githubusercontent.com/94496584/164913491-67fe0954-a461-457c-bda2-f5d368ada491.png)

**Comment by lazyDevPro** [comment]
@kmrn777 email me at lazydevpro@gmail.com because I don't think it's now a library issue but the personal issue, I will try to help.

**Comment by lazyDevPro** [comment]
@Canato I have tried getting the JAVA only solution for version [3.3.6](https://github.com/CanHub/Android-Image-Cropper/releases/tag/3.3.6)
 migration but so far nothing worked only way to achieve this is by using the kotlin compiler If you want I can add those steps in the wiki.

**Comment by Canato** [comment]
@lazyDevPro Can you open a PR with the steps?

I was even thinking about having a second README only for Java. as `README_JAVA.md` and in the main `README.md` we have a link for it. What do you think?

**Comment by kmrn777** [comment]
@lazyDevPro thanks mate, i don't know how but it compiled it on kotlin, so it works now... @Canato thanks for your help also :)

**Comment by Canato** [comment]
@lazyDevPro I refactor the documentation, trying to make more clear. And add a new file just for Java usage of the library

[Java Usage doc](https://github.com/CanHub/Android-Image-Cropper/blob/main/.documentation/java_usage.md)

Could you add there any of the important steps to have this working on Java? So the community can get the benefits ^^

**Comment by lazyDevPro** [comment]
hi @Canato sorry I was away for some work and didn't check the notification, sure I am going through it now and will add the steps.
