### ISSUE TITLE
[BUG] - Permission Denial: starting Intent  act=android.media.action.IMAGE_CAPTURE

### ISSUE THREAD

**Issue by sureshseenis** [CanHub/Android-Image-Cropper#352]
It not asking the permission straightaway it crashed

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template that will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template

_Is important to remember that my work here is a volunteer and to save time and have better answers help me that people use the templates._ 

Thanks!! 🎉
