### ISSUE TITLE
[BUG] - can't see the crop button

### ISSUE THREAD

**Issue by piyush921** [CanHub/Android-Image-Cropper#353]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version - 3.3.5
 
**Describe the bug**
Can't see the crop button. So, can't crop the image. 

**To Reproduce**
1) pick image from gallery
2) open crop image screen
3) But crop button not showing

**Expected behavior**
There should be a crop button on cropping screen

**Media**
![cropping](https://user-images.githubusercontent.com/18148080/163168671-c6b0cd18-9e34-4dcc-b285-c7495ab1905c.jpeg)

**Smartphone (please complete the following information):**
 - Device:  Samsung J8
 - OS:  Android API 29

Code Snippet 
![image](https://user-images.githubusercontent.com/18148080/163169015-51f23804-da76-48eb-adc3-0367c8036a6a.png)

**Comment by Canato** [comment]
Hey @piyush921 thanks for the issue. Does your app theme as no action bar? 

If yes, you should add this 
```kt
<activity android:name="com.canhub.cropper.CropImageActivity"
  android:theme="@style/Base.Theme.AppCompat"/> <!-- optional (needed if default theme has no action bar) -->
  ```Do

**Comment by piyush921** [comment]
Hi Canato, 
Thanks for the reply.
My default theme for app is Theme.MaterialComponents.Light which is set in application tag in manifest file.

And adding android:theme="@style/Base.Theme.AppCompat" to my activity does not resolved my issue.

**Comment by Canato** [comment]
@piyush921 not sure, this is some versions behind. Suggest you use the latest version so we can check better what can be the issue. 

You can check the sample code too.. maybe get some insight there 🤔 

> And adding android:theme="@style/Base.Theme.AppCompat" to my activity does not resolve my issue.
You don't add to your activity, you add to `CropImageActivity` exactly like the code I paste is written.

**Comment by BitTim** [comment]
I had the same problem and fixed it by adding what @Canato originally mentioned [here](https://github.com/CanHub/Android-Image-Cropper/issues/353#issuecomment-1097942114) in the `AndroidManifest.xml` within the application tags:

```xml
<application>
    ...
    <activity
        android:name=".MainActivity"
        android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>

    <!-- Inserted here -->
    <activity android:name="com.canhub.cropper.CropImageActivity"
      android:theme="@style/Base.Theme.AppCompat"/> <!-- optional (needed if default theme has no action bar)
</application>
```

**Comment by piyush921** [comment]
> @piyush921 not sure, this is some versions behind. Suggest you use the latest version so we can check better what can be the issue.
> 
> You can check the sample code too.. maybe get some insight there 🤔
> 
> > And adding android:theme="@style/Base.Theme.AppCompat" to my activity does not resolve my issue.
> 
> You don't add to your activity, you add to `CropImageActivity` exactly like the code I paste is written.

It worked, thanks
