### ISSUE TITLE
[BUG] - Some translations are missing

### ISSUE THREAD

**Issue by yasmanets** [CanHub/Android-Image-Cropper#357]
- Lib Version [4.2.1]
 
**Describe the bug**
When the source selector is displayed, the texts are always in English.

**To Reproduce**
 - Displays the source picker dialog

**Expected behavior**
The text must appear in the language of the device.

**Media**
![Screenshot](https://user-images.githubusercontent.com/34303875/164666561-6b0d1492-13d6-4d2c-b322-1e73edd76483.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 9A
 - OS: Android 10

**Additional context**

**Comment by Canato** [comment]
@yasmanets thanks for raising this. Please open a PR with the translations so we can add ^^

**Comment by yasmanets** [comment]
Thanks @Canato !!
