### ISSUE TITLE
[BUG] - Fatal Exception: java.lang.RuntimeException Unable to start activity ComponentInfo{com.knudge.ielts/com.theartofdev.edmodo.cropper.CropImageActivity}: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.knudge.ielts/cache/pickImageResult.jpeg exposed beyond app through ClipData.Item.getUri()

### ISSUE THREAD

**Issue by AmolPardeshi99** [CanHub/Android-Image-Cropper#363]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version [e.g. 1.1.0]
 
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Media**
Please add screenshots and/or screen recordings to help explain your problem.
We cannot help without more information

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3XL]

**Additional context**

**Comment by AmolPardeshi99** [comment]
Caused by android.os.FileUriExposedException
file:///storage/emulated/0/Android/data/com.knudge.ielts/cache/pickImageResult.jpeg exposed beyond app through ClipData.Item.getUri()

**Comment by Canato** [comment]
Hey @AmolPardeshi99 looks like you are using an old library version and you did not fill the template. 

Please update to the latest version. Will close this issue, when you open please fill the template with the important information
