### ISSUE TITLE
[BUG] - Black background is coming for .PNG images while cropping

### ISSUE THREAD

**Issue by kranthisvk** [CanHub/Android-Image-Cropper#365]
I am getting black background for png images while cropping. How to resolve this issue?

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template that will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template

_Is important to remember that my work here is a volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
