### ISSUE TITLE
[BUG] - Black background is coming for transparent .PNG images while cropping

### ISSUE THREAD

**Issue by kranthisvk** [CanHub/Android-Image-Cropper#366]
- v4.2.1
 
**I am getting black background for png images while cropping. How to resolve this issue?**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Image Picker and select any .png image with transparent background and then go to Crop Image Activity
2. Click on Crop after selecting the crop area
4. See the cropped image result now. It will be coming with black background instead of transparent background

**Background of the cropped image result was supposed to be transparent**

Below image is what I have picked to crop it. You can see that the image is having transparent background here.
![WhatsApp Image 2022-05-13 at 12 29 28 PM](https://user-images.githubusercontent.com/88330039/168231142-ed235b79-24d2-44f9-93cd-2bae2af227be.jpeg)

Below image is the result I got from crop activity. You can see that the image is having black background.
![WhatsApp Image 2022-05-13 at 12 29 29 PM](https://user-images.githubusercontent.com/88330039/168231493-57775052-0800-4ed5-93af-d6f72dc670a8.jpeg)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 9 Pro
 - OS: Android 11

All other images which are not transparent are just working fine except for the transparent .png images.

**Comment by Canato** [comment]
Hey, @kranthisvk thanks for the detailed explanation.

### One questions
- Could you reproduce it on the sample app?

### One possible solution
Did you set up the outcome format? `setOutputCompressFormat(Bitmap.CompressFormat.JPEG)` is the default, maybe you need to change it for png.

**Comment by kranthisvk** [comment]
private fun cropImage(uri: Uri?, aspectRatio: Float) {
    try {
        cropImageForResultLauncher?.launch(
            options(uri) {
                setOutputUri(uri)
                setOutputCompressFormat(Bitmap.CompressFormat.PNG)
                setGuidelines(CropImageView.Guidelines.ON)
                setBackgroundColor(Color.TRANSPARENT)
                if (aspectRatio > 0) setAspectRatio((aspectRatio *
100).toInt(), 100)
            }
        )
    } catch (e: Exception) {
        e.printStackTrace()
    }
}



Hi,

Thank you for replying. I have made changes to my code and set the
outputformat to .PNG format. But still getting the image output with black
background. I have even changed the background color to a transparent
background.

I have added the sample code snippet from my project.

**Comment by kranthisvk** [comment]
I have removed background color option to set it to transparent color too
but no change in image output. Still getting the image with black
background.

**Comment by Canato** [comment]
@kranthisvk sorry, can you please not use `email` reply? I won't format making it harder to understand your answer.

Could you please format your answers using md file?

I still need to know `Could you reproduce it on the sample app?`

This is the first template question. 
If you `git clone` the project and run the sample app... can you reproduce it?
