### ISSUE TITLE
[BUG] - Uri Received lacks 'file' scheme:

### ISSUE THREAD

**Issue by Morons** [CanHub/Android-Image-Cropper#368]
Version 4.2.1
 
Actually the cropper works fine and produces the Uri, however! getting the `jave.io.File` from the Uri present the problem in < Android API 31 Platform >

**My Code to Produce the URI**
```kotlin
	val imageCropLauncher = rememberLauncherForActivityResult(CropImageContract()) { result ->
		if (result.isSuccessful) {
			// use the cropped image
			imageUri = result.uriContent ?: Uri.EMPTY
			imageFilePath = result.getUriFilePath(context = context, uniqueName = true).toString()
```
The Uri produced from Android-Image-Cropper is an `android.net.Uri`
The `result.getUriFilePath` produces and filename e.g. `/data/user/0/{Package Name}/cache/temp_file_20220518_084809.jpg`

**to get a java.io.File**
```kotlin
val file: File = imageUri.toFile()
```
this is done by 
`androidx.core.net UriKt - Uri.toFile(): File androidx.core:core-ktx:1.7.0@aar`
```kotlin
public fun Uri.toFile(): File {
    require(scheme == "file") { "Uri lacks 'file' scheme: $this" }
    return File(requireNotNull(path) { "Uri path is null: $this" })
}
```
**and produces** java.io.File
`content://{Package Name}.cropper.fileprovider/my_images/Pictures/cropped9190345921296464979.jpg`
** The Error**
Therefore I get
`java.lang.IllegalArgumentException: Uri lacks 'file' scheme:`

Any other solution I may try? 
**Bug or Not?**

**Comment by Morons** [comment]
Will test this asap

**Comment by Morons** [comment]
**The Solution** Thank you for your suggestion, I implemented this in Compose
```kotlin
	val imageCropLauncher = rememberLauncherForActivityResult(contract = CropImageContract()) { result ->
		if (result.isSuccessful) {
			// use the cropped image
			resultImageUri = result.uriContent
			imageFilePath = result.getUriFilePath(context = context, uniqueName = true).toString()
			if (resultImageUri?.scheme?.contains("content") == true) {
				// replace Scheme to file
				val builder = Uri.Builder()
					builder.scheme("file")
						.appendPath(imageFilePath)
				val imageUri = builder.build()
				viewModel.onEvent(CreatePostEvent.CropImage(imageUri))
			}
		} else {
			// an error occurred cropping
			val exception = result.error
			Log.e(GLOBAL_TAG, "CropImageContract Exception $exception")
		}
	}
```
**NOTES:**
Basically if the scheme does contains `content:\\` the `val file: File = imageUri.toFile()`  crash with the error!!
so I re-build the Uri from the `.getUriFilePath` with the scheme `file:\\` and use it with correct results

Thank you for this support!

**Comment by Canato** [comment]
@Morons if you don't mind, would be great to add this Question and solution to our FAQ

https://github.com/CanHub/Android-Image-Cropper/blob/main/.documentation/FAQ.md

Can you open a PR with it?  Thanks!
