### ISSUE TITLE
I need help with this please asap

### ISSUE THREAD

**Issue by DarknessQuake** [CanHub/Android-Image-Cropper#371]
I need help on these issues as the android image cropper from Arthurhub is deprecated and the other version from canhub image cropper is the one im using. I am doing an scan receipt function using a ocr scanner but android studio has since updated and there is no suitable tutorial on this version on line anywhere.

    getOCRDataBtn.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            CropImage.setGuidelines(Guidelines.ON).start(ScanReceipt.this);>I need help on this line as im using can hub android image cropper
        }
    }
protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
    super.onActivityResult(requestCode, resultCode, data);
    if(resultCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE)
    {
        CropImage.ActivityResult result = CropImage.ActivityResult.getActivityResult(data);>I need help on this line as im using can hub android image cropper
        if(resultCode == RESULT_OK)
        {
            Uri resultUri = result.getUri();>I need help on this line as im using can hub android image cropper
            try {
                bitmap = MediaStore.Images.Media.getBitmap(this.getContentResolver(), resultUri);
                getTextFromImage(bitmap);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template that will help me to help you.

> And please use the MD format for code, really hard to read code this way. <<<<<<<<<

I will **close** 🔴  this issue so you can reopen following the template

_Is important to remember that my work here is a volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
