### ISSUE TITLE
I need help with 3 errors and i hope this is ok canato

### ISSUE THREAD

**Issue by DarknessQuake** [CanHub/Android-Image-Cropper#372]
the problem that i am having is three sections that i need help with:

```
CropImage.setGuidelines(CropImageView.Guidelines.ON).start(ScanReceipt.this);
```
this is for an setonclicklistener and having a lot of trouble trying to figure this out.

```
 CropImage.ActivityResult result = CropImageView.getActivityResult(data);
  if(resultCode == RESULT_OK)
            {
 Uri resultUri = result.getUri();
  try {
bitmap = MediaStore.Images.Media.getBitmap(this.getContentResolver(), resultUri);
getTextFromImage(bitmap);
 } catch (IOException e) {
 e.printStackTrace();
  }
```
The 2 other problems are the Crop Image view (getActivityResult) as i tried to get a much information as possible to sort this out to non avail while the other is .getUri.

I was using the arthurhub image cropper that is now deprecated and now using this one.

i hope this is clearer due to not using this for quite some time.

**Comment by Canato** [comment]
Hey @DarknessQuake wanna help you, but I have a lot of requests... I really need people to use the template to avoid me asking the same stuff we have on the template.

If you have questions, please use [discussions](https://github.com/CanHub/Android-Image-Cropper/discussions) and open a `Q&A` (Question and Answer) type of discussion

If you believe (or know) that you have a bug:
1 - Click on New issue 
<img width="127" alt="Screenshot 2022-05-23 at 17 50 47" src="https://user-images.githubusercontent.com/15942449/169869774-103c2e45-5107-4acd-8d3c-edd5970a4b57.png">
2 - Select the bug report template
<img width="1176" alt="Screenshot 2022-05-23 at 17 50 42" src="https://user-images.githubusercontent.com/15942449/169869822-4781b171-ced2-4e90-ae7a-893b40b259cc.png">
3 - Fill the template answering the questions, like "Have you checked the sample app?", which library version are you? How can I reproduce? etc

<img width="646" alt="Screenshot 2022-05-23 at 17 51 02" src="https://user-images.githubusercontent.com/15942449/169869947-7974ed18-c64b-4c19-a3f0-182df8ae7de4.png">

**Comment by Canato** [comment]
Don't wanna push you out... but I have no idea if you are using the activity of the library, or custom or the view directly etc

And other questions. that's the reason the templates help the conversations to start

**Comment by DarknessQuake** [comment]
ok i will try this out thanks
