### ISSUE TITLE
[BUG] - setGuidelines in CropImage, getActivityResult in CropImageView and getUri in ActivityResult

### ISSUE THREAD

**Issue by DarknessQuake** [CanHub/Android-Image-Cropper#373]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

![Code Problem Android Studio](https://user-images.githubusercontent.com/5896215/169873265-f2f21ba4-2eba-45fa-8e9d-f327567d4e9c.jpg)

![Android Studio 3 Problems](https://user-images.githubusercontent.com/5896215/169874028-0ea497d3-9ba8-4202-80ba-67954a9f584a.jpg)

[ScanReceipt.txt](https://github.com/CanHub/Android-Image-Cropper/files/8756959/ScanReceipt.txt)

 - Lib Version [4.2.2]
 - Gradle Plugin Version [4.2.2]
 - Gradle Version [7.3.3]
 
**Describe the bug**
First Bug: I have a setGuidelines issue from using ArthurHub image cropper and trying to convert piece of code to CanHub version
Second Bug: I have getActivityResult issue when trying to get the data
Third Bug: i am trying to get the Uri but its not giving me the option from my current knowledge.

i have been searching online to solve this issue for 7 days and is driving me insane. there is 0 information on this version because people are using the ArthurHub version that no longer works (for me anyway) as this is deprecated. 
see attached txt file for full code.

**Smartphone (please complete the following information):**
 - Device: [Pixel 3a_API_x86]
 - OS: [Android 6.0 Marshmallow]

**Comment by Canato** [comment]
Hey, @DarknessQuake I see that you are using Java. 
Have you checked our [documentation for Java usage](https://github.com/CanHub/Android-Image-Cropper/blob/main/.documentation/java_usage.md)?

You can see how to properly make the calls in the Java Sample _(link on the docs)_ for Android Contracts.
If you are not planning to use Android Contracts you need to use version `3.3.6`, like the documentation explains

**Comment by DarknessQuake** [comment]
ok i will try this to see if this would get it to work thank you will try it and report back.

**Comment by DarknessQuake** [comment]
![2 errors to go](https://user-images.githubusercontent.com/5896215/169882944-8d4c1144-2884-4937-8fd1-4d015d37d88a.jpg)
i got 1 error sorted so thank you for that
i have looked at the kt file and yes it makes sense now lol i dont understand the getActivityResult because looking at the documentation that you have provided its crossed out and mine is red (same thing) is there a piece of code that replace this.

**Comment by Canato** [comment]
`getActivityResult` will not work on the latest release. Only until `3.3.6`.

After this release we update to use Android Contracts (the usage of it can be checked on the JavaSample^^)

**Comment by DarknessQuake** [comment]
right!!! thank you i wondered about that im going to use 3.3.6 or lower to see if it is sorted it not i will use android contracts thank 
you.
