### ISSUE TITLE
[BUG] - Can't Implement Library in the project

### ISSUE THREAD

**Issue by goldenacid12** [CanHub/Android-Image-Cropper#375]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version [e.g. 1.1.0]
 
**Describe the bug**
Hello the creator, I have been trying to use the image cropper, I have found the previous image cropper made by theartofdev, and It works fine for file manager and gallery but not for the camera, and I found out that there's newer version that you made, I have been trying to update using your tutorial but until now I can't find the reason of the failing implementation. Maybe you could help me find the problem. I have tried it on a new project and still showing the same result.

**To Reproduce**

**Expected behavior**

**Media**
![image](https://user-images.githubusercontent.com/99663816/171182425-e4392d13-2d17-41d5-a8e9-b6a03b8144fb.png)
![image](https://user-images.githubusercontent.com/99663816/171182468-e5216404-f3ad-4464-bffb-a53d8035ec8f.png)
![image](https://user-images.githubusercontent.com/99663816/171182957-5febdd49-1db0-4dcf-86f2-b1e6e9296997.png)

Please add screenshots and/or screen recordings to help explain your problem.
We cannot help without more information

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 9]
 - OS: [Android 11]

**Additional context**

**Comment by goldenacid12** [comment]
I don't know how but the program fixed itself.

**Comment by Canato** [comment]
Sometimes Gradle cache work in mysterious ways. Happy that is working
