### ISSUE TITLE
Can't see Crop button in new liberary

### ISSUE THREAD

**Issue by dev1-bitronics** [CanHub/Android-Image-Cropper#377]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version [e.g. 1.1.0]
 
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Media**
Please add screenshots and/or screen recordings to help explain your problem.
We cannot help without more information

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3XL]

**Additional context**

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template that will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template

_Is important to remember that my work here is a volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉

**Comment by Canato** [comment]
Probably you wanna check the [FAQ](https://github.com/CanHub/Android-Image-Cropper/blob/main/.documentation/FAQ.md) ^^
