### ISSUE TITLE
[BUG] - Back button issue

### ISSUE THREAD

**Issue by vineet1061** [CanHub/Android-Image-Cropper#378]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 when we capture image from camera and go back without capture image then crop activity is showing on single back

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template that will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template

_Is important to remember that my work here is a volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
