### ISSUE TITLE
[Feat] - Publish library to mavenCentral

### ISSUE THREAD

**Issue by vanniktech** [CanHub/Android-Image-Cropper#393]
This would be much better than jitpack

**Comment by Canato** [comment]
Which benefits do you see? 

I don't mind if we change or have two places to deploy if we can automate as much as possible. 

If we change, we need to be sure people will get along

**Comment by vanniktech** [comment]
Much more reliable and is de facto the standard.

**Comment by vanniktech** [comment]
Also a licensing file is missing

**Comment by Canato** [comment]
Agreed, would be great to have

**Comment by vanniktech** [comment]
![https://media0.giphy.com/media/o0eOCNkn7cSD6/giphy.gif?cid=ecf05e47fpwq704xkksizlet9nrn2kn001r0o54dxavo2ryz&rid=giphy.gif&ct=g](https://media0.giphy.com/media/o0eOCNkn7cSD6/giphy.gif?cid=ecf05e47fpwq704xkksizlet9nrn2kn001r0o54dxavo2ryz&rid=giphy.gif&ct=g)
