### ISSUE TITLE
[Feat] - CropImageView has no way of setting a CropImageOptions programmatically

### ISSUE THREAD

**Issue by vanniktech** [CanHub/Android-Image-Cropper#397]
Currently, it's constructed via XML attributes, however when using that View programmatically there's no real way to pass in a `CropImageOptions` to configure it

I wanted to use #390 only to realize that there's no way for me to actually use it.

Maybe the options would also need to be splitted since `CropImageView` calls into `CropOverlayView` which calls into `CropWindowHandler` and they are all sharing the same options. Seems like each should have their own.

**Comment by Canato** [comment]
I like the idea, let's see how would be implemented on the sample app 👍
