### ISSUE TITLE
Downgrade targetSdkVersion

### ISSUE THREAD

**Issue by PaulWoitaschek** [CanHub/Android-Image-Cropper#400]
As this library sets targetSdkVersion to 31, this forces all consumers to also target api 31. Is there any reason to do so?

**Comment by Canato** [comment]
Nothing that I remember now, we could remove it.

**Comment by Canato** [comment]
> Don't stale me, it's a good idea and no mess 😁

Stale robot go brrrrrr brrrrr 

hahahaha.

**Comment by pratyaksh1610** [comment]
@Canato  What is the issue ?  I am unable to understand. Can you explain in brief .
.
.
Thankyou
Pratyaksh

**Comment by Canato** [comment]
> @Canato What is the issue ? I am unable to understand. Can you explain in brief . . . Thankyou Pratyaksh

@pratyaksh1610 the library today set up targetSdkVersion to version 31. What forces who use to have the same target. This is probably something we can remove. Need testing
