### ISSUE TITLE
mistake in hindi conversion of  "Crop"

### ISSUE THREAD

**Issue by Pradeepkuumar** [CanHub/Android-Image-Cropper#402]
mistake in hindi conversion of  "Crop"
it is showing "Crop" = फसल
it will be   "Crop" = काटे

Please update

**Comment by Canato** [comment]
Please open a PR with the fix

**Comment by PaulWoitaschek** [comment]
@Pradeepkuumar 
You can click here on the edit button and edit it in the browser directly:
https://github.com/CanHub/Android-Image-Cropper/blob/main/cropper/src/main/res/values-hi/strings.xml

**Comment by pratyaksh1610** [comment]
I would like to work on this issue. Pls assign this issue to me. I have resolved the issue.
.
.
Thankyou
Pratyaksh

**Comment by Canato** [comment]
Can do @pratyaksh1610

**Comment by pratyaksh1610** [comment]
@Canato I have made a PR. Pls review.
