### ISSUE TITLE
Crashing in Android 12 and 13

### ISSUE THREAD

**Issue by ArcherEmiya05** [CanHub/Android-Image-Cropper#405]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version [e.g. 1.1.0]
 
**Describe the bug**
App crash when using the library.

**To Reproduce**

Case 1:
1. Launch CropImage intent
2. Choose Camera
3. Crash!

Logs:
`Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list hasLabel(0) {U(content)}} (has extras) } from ProcessRecord{65880b 3431:com.sample.sample/u0a148} (pid=3431, uid=10148) with revoked permission android.permission.CAMERA`

Case 2:
1. Launch CropImage intent
2. Choose Gallery
3. In your code access the return Uri like this

```
//Get the file using imageURI
File thumbnailFile = new File(imageUri.getPath());

Bitmap compressedImageFile = BitmapFactory.decodeFile(thumbnailFile.getAbsolutePath(), options);

compressedImageFile.compress(Bitmap.CompressFormat.PNG, 50, byteArrayOutputStream); // Crash! Bitmap is empty
```

Logs:

`Unable to decode stream: java.io.FileNotFoundException: /my_images/Pictures/cropped1075363767022160999.jpg: open failed: ENOENT (No such file or directory)`

**Expected behavior**
Works well with the latest SDK version

**Media**
![image](https://user-images.githubusercontent.com/38008900/177231662-f3b5d71c-d3d6-436d-81e3-b9c35e4c23c9.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 4 (Emulator),  Redmi Note 11 (Physical)
 - OS: Android 12 and 13

**Comment by Canato** [comment]
The first point of the template: `Did you test on the sample app`?
Te second point: `Which library version are you using`?

**Comment by ArcherEmiya05** [comment]
I am closing this issue now, the solution for the first issue was removing the CAMERA permission from manifest. The solution for `FileNotFoundException` was replacing `File` with `InputStream is = getContentResolver().openInputStream(mProfilePicURI)`

**Comment by ArcherEmiya05** [comment]
I am closing this issue now, the solution for the first issue was removing the CAMERA permission from manifest. The solution for `FileNotFoundException` was replacing `File` with `InputStream is = getContentResolver().openInputStream(mProfilePicURI)`

**Comment by ArcherEmiya05** [comment]
Sorry I would like to reopen this issue specially the CAMERA permission part. Removing it from my app module manifest does fix the issue but I need that permission for other feature of the app as well that is not using this library, one example is for video calling. I think the CAMERA permission should be pass on the consumer module which is usually the app module. 

This error is showing on Android 11 above if I my memory is correct.

`Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list hasLabel(0) {U(content)}} (has extras) } from ProcessRecord{65880b 3431:com.sample.sample/u0a148} (pid=3431, uid=10148) with revoked permission android.permission.CAMERA`

**Comment by ArcherEmiya05** [comment]
Closing now this issue, the fix is to request CAMERA permission and grant it before using this library if `android.permission.CAMERA` is set in the manifest.
