### ISSUE TITLE
[BUG] - Not all EXIF values are supported

### ISSUE THREAD

**Issue by Mouwrice** [CanHub/Android-Image-Cropper#408]
- Lib Version 4.3.0

**Describe the bug**
EXIF values not only define rotation but also mirroring, see EXIF values 2, 4, 5, 7:
![image](https://user-images.githubusercontent.com/56763273/179480833-2d1ae6cb-7f49-44bf-bd60-4e09e6b3b241.png)

But sadly that is not implemented in this library.

**To Reproduce**

1. Open the app
2. Select `SAMPLE USING CROPIMAGEVIEW` 
3. Choose an image that has EXIF value 2, 4, 5 or 7 (using the bottom left button) and see that they are orientated wrongly.

The exact images used are:
https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_2.jpg
https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_4.jpg
https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_5.jpg
https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_7.jpg

Try to crop an image that has an EXIF value of 2, 4, 5 or 7 and see that the image is in fact not correctly mirrored:
This is an image with EXIF value of 2
![image](https://user-images.githubusercontent.com/56763273/179481103-219b73b9-ee34-4999-9254-244aeb9f3ae0.png)

**Expected behavior**
Make use of these enums:
https://developer.android.com/reference/androidx/exifinterface/media/ExifInterface#ORIENTATION_FLIP_HORIZONTAL
https://developer.android.com/reference/androidx/exifinterface/media/ExifInterface#ORIENTATION_FLIP_VERTICAL
https://developer.android.com/reference/androidx/exifinterface/media/ExifInterface#ORIENTATION_TRANSPOSE
https://developer.android.com/reference/androidx/exifinterface/media/ExifInterface#ORIENTATION_TRANSVERSE

Which define what tranformations you need to apply to the image to get the correct orientation.

**Media**
You can test this out yourself by using the images provided in this repo:
https://github.com/recurser/exif-orientation-examples

**Proposed solution**
From a quick overview it seems that you should be able to pretty easily update the rotate function by exif value to also flip the image
https://github.com/CanHub/Android-Image-Cropper/blob/2f867e993670bb75597d6633284ca616fe045b12/cropper/src/main/java/com/canhub/cropper/BitmapUtils.kt#L90-L107

**Comment by Canato** [comment]
@Mouwrice this is great, please open a PR and let's fix this =)

**Comment by Mouwrice** [comment]
> @Mouwrice this is great, please open a PR and let's fix this =)

On it 💪
