### ISSUE TITLE
Cropping issue on some devices

### ISSUE THREAD

**Issue by ksk-tech** [CanHub/Android-Image-Cropper#414]
- Lib Version 3.3.6, 4.3.1
 
**Describe the bug**
Cropping flow fails in some cases after taking a photo on some devices. We have reproduced it on Samsung devices. Usually it's reproduced if a user switches cameras and then takes a photo, but sometimes we get the same result with no camera switch. 
In our app with the lib integrated the following result is logged - `cropping has been cancelled by the user`

**To Reproduce**
1. Open the sample app on a Samsung device. The issue is definitely reproduced on Samsung S21+ with Android 12 here - [Samsung Remote Test Lab](https://developer.samsung.com/remotetestlab/deviceList.action?os=101#550)
2. Click on `Sample Calling CropImage` -> `Call Liabrary Directly Without URI` -> `Camera` -> switch cameras -> take a photo and press `OK`

**Expected behavior**
Correct cropping flow

**Media**

https://user-images.githubusercontent.com/85189211/180975228-f1a7de8e-ba75-4518-abe4-3a588a840930.mp4

**Smartphone (please complete the following information):**
 - Device: [Samsung S21/S21+]
 - OS: [Android 12]

**Additional context**
It seems like the context for getting a photo image doesn't survive in most of the cases on Samsung devices.
I have no such issue on Pixel 4A.

**Comment by Canato** [comment]
Back from holidays, will check ASAP

**Comment by ksk-tech** [comment]
Hello @Canato, hope you are doing well. 
Have you managed to reproduce the issue?

**Comment by Canato** [comment]
Hey @ksk-tech not yet. I started a new job as manager on the last weeks

Basically, my time has been reduced a lot. But I didn't forget this. 
I just need to find time to make this volunteer work ^^

Sad to say, but capitalism force me to focus where the money comes in hahahaha

**Comment by Canato** [comment]
Back this week will take a look. sorry for the long time on this

**Comment by Canato** [comment]
@ksk-tech Thanks for raising this and sorry for so long to answer. Last month have being crazy.

Indeed I could reproduce with some devices, but mostly I could not.

Yet, not sure what could cause this, something that Samsung is being annoying with its context/cache
For sure we can do something about it, just need to discover what. And hope they will fix it

**Comment by vanniktech** [comment]
@ksk-tech have you found any workaround? Is this still happening?

**Comment by siddeshpillai** [comment]
https://github.com/CanHub/Android-Image-Cropper/issues/355#issuecomment-1292771572

**Comment by ksk-tech** [comment]
@vanniktech @Canato it seems like the Samsung Camera app update has fixed the issue.

**Comment by vanniktech** [comment]
Alright, thanks. Closing this :)
