### ISSUE TITLE
[BUG] - Intent Chooser option are twice

### ISSUE THREAD

**Issue by ritu-patidar** [CanHub/Android-Image-Cropper#415]
- Lib Version : 4.21 / 4.3.1
 
**Describe the bug**
Showing Intent Chooser option are twice - I set the options.setShowIntentChooser(true); it is showing option are twice.
![Screenshot_2022-07-26-18-51-51-31_c31b32364ce19ca8fcd150a417ecce58](https://user-images.githubusercontent.com/110038930/181019361-78fad3a1-1bf4-4a38-b25d-f5951903fe2f.jpg)
![Screenshot_2022-07-26-18-54-18-502_android](https://user-images.githubusercontent.com/110038930/181019376-44e27fa7-3045-43cf-8ab5-4f389437bb74.jpg)

**Expected behavior**
Selection option should appear only once

**Screenshots**
https://drive.google.com/file/d/1BA_2pBY-jWyd5oVEw4UJA-C69iq1maF5/view?usp=sharing
https://drive.google.com/file/d/1ETb5n8yi3MNQ982s7vRk4FbxJw_7inTz/view?usp=sharing

**Smartphone**
 - Device:  Realme C3 - Version 11
 -  Device:  Realme 7A - Version 10

**Comment by Canato** [comment]
@ritu-patidar can you reproduce on the sample app?

Could you provide a video of the issue on the sample app? 

Thanks!

**Comment by Devenom1** [comment]
@ritu-patidar Do you have dual space or dual apps set up on your device?
