### ISSUE TITLE
API Level 30 and about

### ISSUE THREAD

**Issue by SanganiKrish** [CanHub/Android-Image-Cropper#416]
The Devices which are runing about api level 30 are crashing after croping and  passing through intent

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template that will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template

_Is important to remember that my work here is a volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
