### ISSUE TITLE
[Feat] - Photo picker Android 13

### ISSUE THREAD

**Issue by Canato** [CanHub/Android-Image-Cropper#419]
[photo picker](https://developer.android.com/about/versions/13/features/photopicker)

**Comment by Canato** [comment]
@pratyaksh1610 for Android 13 there is this new way to pick images (link on the issue) we need to bring this to our library to stay up to date.

**Comment by thekingrenz23** [comment]
any update on this one? we need to use the new photo picker for android 13

**Comment by Canato** [comment]
Look like no one is working on this @thekingrenz23 feel free to drop a PR!

But I believe should be backwards compatible, no? Is just a new better way of doing it

**Comment by dineshkarthi95** [comment]
Hey @Canato I can help on this issue and pick it up, let me know :)

**Comment by Canato** [comment]
Hey, sorry, I'm not providing support for the library until we decide on a new responsible. 
Check more on the discussion: https://github.com/CanHub/Android-Image-Cropper/discussions/441

**Comment by vanniktech** [comment]
I don't see any benefit adding this to the library itself. You can use this functionality already and just pass the url to this library. (Please correct me if I'm mistaken)
