### ISSUE TITLE
[Feat] - Add custom color customisations for CropImageActivity toolbar and background

### ISSUE THREAD

**Issue by Devenom1** [CanHub/Android-Image-Cropper#421]
**Is your feature request related to a problem? Please describe.**
The current library doesn't let us set custom colors to match a particular theme we require for the toolbar and the activity background.

**Describe the solution you'd like**
It would be nice to add options to customize colors for the tool bar and activity background.

**Describe alternatives you've considered**
There's a setBackground color but that doesn't seem to be for the activity background

**Additional context**
I'm a bit rusty but I will attach a PR to this soon

Something like this image below where I set a gray toolbar and black activity background.

![image](https://user-images.githubusercontent.com/11510037/184700178-6c4c87ad-3c64-4ad0-8948-5c0314eaa748.png)

**Comment by Canato** [comment]
We can already override, but that's a great idea, hopefully, someone will have time to add this!

**Comment by Devenom1** [comment]
Already made a PR.
