### ISSUE TITLE
[BUG] - Back button dosen't work when activity launched.

### ISSUE THREAD

**Issue by Chandra-Sekhar-Bala** [CanHub/Android-Image-Cropper#427]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version [4.3.1]
 
**Describe the bug**
After invoking ```CropImageContract()``` two options appeared ```camera and gallery```, at this moment if we press the back button it doesn't work. 

**To Reproduce**
 *Launch the ```CropImageContract()``` then press back button.

**Expected behavior**
User should be taken back to where this activity was invoked.

**Smartphone (please complete the following information):**
 - Device: [Pixel 4 - API 30]
 - OS: [Android 11]

**Comment by Canato** [comment]
Indeed, good catch!
