### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by setifa** [CanHub/Android-Image-Cropper#430]
Please Help
i had issue when migrating.
![00](https://user-images.githubusercontent.com/112350771/187095172-412e120d-9032-4e7b-8d8d-cc542b7fa9ac.jpg)

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template that will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template

_Is important to remember that my work here is a volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
