### ISSUE TITLE
[BUG] - Migration don't find activity

### ISSUE THREAD

**Issue by setifa** [CanHub/Android-Image-Cropper#431]
- Lib Version [4.3.1]
 
**Describe the bug**
This issue appeared after migrating from the old library to the new.
When running the App i face this error:
Unresolved reference: activity

**To Reproduce**

**Expected behavior**
when i write "CropImage" then "." in the checkbox it doesn't appear "activity" or "getActivityResult"

**Media**
![00](https://user-images.githubusercontent.com/112350771/187239670-1ae724ec-7590-4a50-b9ed-96ba08d54597.jpg)

**Smartphone (please complete the following information):**
 - Device: [Nexus 4 API 22]
 

**Additional context**
Please HELP Me

**Comment by Canato** [comment]
Hi @setifa you are using an old format of the library. If you wanna use the latest format you need to check how to use the library on the [README](https://github.com/CanHub/Android-Image-Cropper#calling-crop-directly) or check the sample codes we provide.

[Why did we make this change?](https://github.com/CanHub/Android-Image-Cropper/issues/26)
