### ISSUE TITLE
[Feat] - Plans to Implement this for KMM/ D-KMP etc.

### ISSUE THREAD

**Issue by Morons** [CanHub/Android-Image-Cropper#435]
Going forward we need to prepare for a massive change to KMM/D-KMP in the future (Why have 2 or more apps, each for another platform if you can shere...)
Will you consider to start adding iOS/Desktop/Web etc?

**Comment by Canato** [comment]
I"m happy if someone wanna do the work! My self I don't have the knowledge or time! ^^
