### ISSUE TITLE
[BUG] - Setting toolbar color to white does not work

### ISSUE THREAD

**Issue by Devenom1** [CanHub/Android-Image-Cropper#436]
- Lib Version 4.3.1
 
## Bug
Setting the toolbar color to `Color.WHITE` doesn't work.

This happens because of a condition checking if toolbar color is `-1` assume it's not set. Unfortunately `-1` is also the value of `Color.WHITE`.

PS: I had made this feature. Will fix it

**Comment by Canato** [comment]
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template that will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template

_Is important to remember that my work here is a volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉
