### ISSUE TITLE
[BUG] - Manifest merge error

### ISSUE THREAD

**Issue by thekingrenz23** [CanHub/Android-Image-Cropper#442]
It was working 5 days ago 

- 4.2.0 also tried the latest no luck
 
**Describe the bug**
Cant build my app it works the last time i build it 

**4.2.0 Error**
```
> Task :app:processDebugMainManifest FAILED
C:\Users\ASTI\Desktop\sprint_ten\secondary\kooha_android\app\src\main\AndroidManifest.xml:49:13-49 Error:
	Attribute activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity@theme value=(@android:style/Theme) from [com.github.CanHub:Android-Image-Cropper:4.2.0] AndroidManifest.xml:49:13-49
	is also present at [androidx.test:core:1.0.0] AndroidManifest.xml:29:13-84 value=(@style/InstrumentationActivityInvokerEmptyActivityTheme).
	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:46:9-53:20 to override.
C:\Users\ASTI\Desktop\sprint_ten\secondary\kooha_android\app\src\main\AndroidManifest.xml:57:13-56 Error:
	Attribute activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyFloatingActivity@theme value=(@android:style/Theme.Dialog) from [com.github.CanHub:Android-Image-Cropper:4.2.0] AndroidManifest.xml:57:13-56
	is also present at [androidx.test:core:1.0.0] AndroidManifest.xml:36:13-87 value=(@style/InstrumentationActivityInvokerFloatingActivityTheme).
	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:54:9-61:20 to override.

```

**4.3.2 Error**
```
> Task :app:processDebugMainManifest FAILED
C:\Users\ASTI\Desktop\sprint_ten\secondary\kooha_android\app\src\main\AndroidManifest.xml:27:9-33:20 Error:
	android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
C:\Users\ASTI\Desktop\sprint_ten\secondary\kooha_android\app\src\main\AndroidManifest.xml:34:9-40:20 Error:
	android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyFloatingActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
```

**Comment by thekingrenz23** [comment]
I found out that the test:core activies does not have export on them how do i fix this?

**Comment by thekingrenz23** [comment]
Closing this issue now because facebook-gamingservices:15.0.0 is the problem

**Comment by ahmednawaz22** [comment]
@thekingrenz23
facing these issues after updating CanHub version.
any idea?

app/src/main/AndroidManifest.xml:27:9-33:20 Error:
	android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
app/src/main/AndroidManifest.xml:34:9-40:20 Error:
	android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyFloatingActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by thekingrenz23** [comment]
> @thekingrenz23 facing these issues after updating CanHub version. any idea?
> 
> app/src/main/AndroidManifest.xml:27:9-33:20 Error: android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details. app/src/main/AndroidManifest.xml:34:9-40:20 Error: android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyFloatingActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

Yes its a problem with test:core:1.0.0 its activity is not exported for me the test:core:1.0.0 is used by facebook-gaming module which is part of the facebook sdk. I removed the whole facebook sdk and just included the facebook login sdk because thats really all i need.

you should check what library you are using that uses test:core:1.0.0

**Comment by thekingrenz23** [comment]
you should update to test:core:1.4.0

**Comment by ahmednawaz22** [comment]
thanks @thekingrenz23 

still same issue
/app/src/main/AndroidManifest.xm:27:9-33:20 Error:
	android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
/app/src/main/AndroidManifest.xml:34:9-40:20 Error:
	android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyFloatingActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by thekingrenz23** [comment]
add me on discord ill show you code.wizard#1787

**Comment by thekingrenz23** [comment]
> thanks @thekingrenz23
> 
> still same issue /app/src/main/AndroidManifest.xm:27:9-33:20 Error: android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details. /app/src/main/AndroidManifest.xml:34:9-40:20 Error: android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyFloatingActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

it should work just adding the test:core:1.4.0 wont fix the issue you have to find libraries you are using that depended on it and must ovverried the values

**Comment by ahmednawaz22** [comment]
@thekingrenz23 thanks buddy :) 
issue was in manifest file of jetifier-core-1.0.0
