### ISSUE TITLE
[BUG] - 521 at https://jitpack.io/com/github/CanHub/Android-Image-Cropper/4.3.0/Android-Image-Cropper-4.3.0.pom

### ISSUE THREAD

**Issue by pratikdhody** [CanHub/Android-Image-Cropper#444]
Hi,

Using expo-image-picker and getting a 521 on the pom package?

![image](https://user-images.githubusercontent.com/48036133/192759062-b5ed4b58-b337-4c02-ba99-3de4b3ea30e2.png)

Please advise

Cheers

**Comment by Canato** [comment]
https://github.com/CanHub/Android-Image-Cropper/discussions/441

**Comment by pratikdhody** [comment]
probably worth mentioning that to expo @Canato as they've changed to point this package as part of expo SDK 45?
https://github.com/expo/expo/blob/main/CHANGELOG.md#-breaking-changes-2

**Comment by vanniktech** [comment]
Yeah jitpack is sometimes flaky. Tracking this via #393
