### ISSUE TITLE
[BUG] - Converting Code

### ISSUE THREAD

**Issue by Rast3** [CanHub/Android-Image-Cropper#445]
Hi, i was using the old image_cropper from 'com.theartofdev.edmodo:android-image-cropper:2.8.+'. Now i'm using this new library 'com.github.CanHub:Android-Image-Cropper:4.3.2' but i don't know how to convert this parts of code:

CropImage.activity(picUri)
                        .setGuidline(CropImageView.Guidelines.ON)
                        .setAspectRatio(4,3)
                        .start(getContext(),Add.this);

CropImage.ActivityResult result = CropImage.getActivityResult(data);

Uri image = result.getUri();

Thanks for reading, hope u can help me.

**Comment by Canato** [comment]
Hey sorry, not providing support for the library until we decide a new responsible, check more on the discussion: https://github.com/CanHub/Android-Image-Cropper/discussions/441

**Comment by vanniktech** [comment]
Please check the sample app there are various showcases. We don't have the time to answer usage questions.
