### ISSUE TITLE
[Feat] - Java version

### ISSUE THREAD

**Issue by Rast3** [CanHub/Android-Image-Cropper#448]
Hi, is there a java version of the "Calling crop directly" code pls?

**Comment by Canato** [comment]
Yes, please check the FAQ
Or the link for a Java explanation on the README

Is the first links

![Screenshot 2022-10-03 at 09 59 31](https://user-images.githubusercontent.com/15942449/193539227-1c85ffcc-a2ac-458d-b98e-1dea49679921.png)
