### ISSUE TITLE
Can't find Wiki/ Documentation.

### ISSUE THREAD

**Issue by kumzi** [CanHub/Android-Image-Cropper#472]
I was using 'com.theartofdev.edmodo:android-image-cropper:2.8.0' previously, Now I would like to build with this library.
But unfortunately the samples are with Kotlin and I would like some Java examples/ documentation. I can't find the wiki page of this repo. Kindly help.

**Comment by vanniktech** [comment]
Migration is here https://github.com/CanHub/Android-Image-Cropper#migrating-from-android-image-cropper
We've ditched Java samples but you can call the code from Java.

**Comment by vanniktech** [comment]
They are also in the README now :)

We'll focus on Kotlin now. It's state of the art.

**Comment by kumzi** [comment]
Kindly share the old Java sample. I badly need to use this in one of my school project.

**Comment by vanniktech** [comment]
https://github.com/CanHub/Android-Image-Cropper/commit/ce3bf1b476e2ce0404abc1ba9c245c68dec42f23
