### ISSUE TITLE
The thickness of the crop box is too thick

### ISSUE THREAD

**Issue by tasy5kg** [CanHub/Android-Image-Cropper#473]
I have been using Android-Image-Cropper for a while.

Recently I found the thickness of the crop box is too thick, so it is sometimes difficult for users to judge whether the pixels on the edge of the border will be cropped.

![image](https://user-images.githubusercontent.com/30869777/197398010-607a95a2-a31e-49a7-9418-40e54c108eec.png)

---

And this is the image cropping box in Google Photos, which has thinner edges so users can crop photos more precisely.

![image](https://user-images.githubusercontent.com/30869777/197398115-3f63beba-b1d0-4eaf-9348-76620737d665.png)

---

So I'm wondering if there is any way to achieve a more precise crop box style when using this library, like what Google Photos looks like?

Sincerely.

**Comment by vanniktech** [comment]
Have you looked at all of the options in `CropImageOptions`? `borderLineThickness` should be what you're looking for.

**Comment by tasy5kg** [comment]
I found it! Thanks for your prompt reply.
