### ISSUE TITLE
[BUG] - Can't see camera option

### ISSUE THREAD

**Issue by kaustubhkp** [CanHub/Android-Image-Cropper#52]
- Lib Version [e.g. 1.1.0]
 
**Describe the bug**
When I am trying to launch CropImage activity on Google pixel 4 XL, It won't show camera option.

**To Reproduce**
On button click I am launching CropImage activity and I am expecting it should ask user to choose from below options
Camera or Gallery
But on Google Pixel 4 XL It directly shows photos from device

**Expected behavior**
It should ask user to chose photo from Camera or Gallery

**Screenshots**

**Smartphone (please complete the following information):**
 - Google Pixel 4 XL
 - Android OS 11

**Additional context**

**Comment by Canato** [comment]
Thanks @kaustubhkp this is the similar issue we have here: #20 

I will tag this as duplicated and I have on my roadmap the plans to fix this. Any case if you feeling excited about Open Source today, feel free to jump in and make a PR =D
