### ISSUE TITLE
[BUG] Cannot find import com.canhub

### ISSUE THREAD

**Issue by imufiid** [CanHub/Android-Image-Cropper#521]
I tried migrate from ```com.theartofdev.edmodo:android-image-cropper:2.8.+``` to ```com.vanniktech:android-image-cropper:4.4.0``` in my project.. but i can't import from package ```com.canhub.``` 

gradle version: gradle-6.5-all.zip
kotlin version: 1.6.21

why?

**Comment by imufiid** [comment]
i tried ```com.vanniktech:android-image-cropper:4.4.0``` like in docs, still not find com.canhub package

**Comment by prasad-333** [comment]
Did you build gradle sync the project after change? sometimes Android Studio cries, you might need to restart AS with Invaliding Cache. Give this a try.

**Comment by vanniktech** [comment]
@imufiid any response to what @prasad-333 said?

**Comment by nguyenhuuloc99** [comment]
help me  not found CropImage.activity().

**Comment by imufiid** [comment]
oke it worked, but in my case had to restart AS several time, idk what happened

**Comment by vanniktech** [comment]
Best to report that to the Android Studio Issue Tracker.
