### ISSUE TITLE
Update Readme file to state compileSdk

### ISSUE THREAD

**Issue by MariusBudin** [CanHub/Android-Image-Cropper#525]
This library is not compatible with projects with minCompileSdk 31 or below.
I understand the choice but please kindly add it to the Readme file so people don't waste time and only learn about it when trying to compile.

**Comment by vanniktech** [comment]
minCompileSdk is 21. Are you talking about something else?

**Comment by MariusBudin** [comment]
Project compileSdk, sorry, not minSdk

**Comment by vanniktech** [comment]
Why is your compileSdk so low? You have to update at some point anyway

**Comment by MariusBudin** [comment]
Big projects might have their own reason. The dependency goes the other way around. I see [this was brought up before](https://github.com/CanHub/Android-Image-Cropper/issues/523) so it was a known thing but just ignored, feel free to close this, just trying to bring in some transparency
