### ISSUE TITLE
Cropping Exception

### ISSUE THREAD

**Issue by criticalAY** [CanHub/Android-Image-Cropper#527]
`com.canhub.cropper.CropException$Cancellation: crop: cropping has been cancelled by the user` Exception arises when we try to crop an image and press back without actually cropping the image

**Comment by vanniktech** [comment]
Yeah that's wanted

**Comment by criticalAY** [comment]
it generates a report because of that is there a way to handle it?

**Comment by vanniktech** [comment]
try/catch
