### ISSUE TITLE
Migrate from com.theartofdev.edmodo

### ISSUE THREAD

**Issue by hannesa2** [CanHub/Android-Image-Cropper#532]
Hi, found this repository as an promising successor from non-maintained 
`com.theartofdev.edmodo:android-image-cropper:2.8.0`

That's why I start to migrate to `com.vanniktech:android-image-cropper:4.5.0` and run into some issues
A: you removed `CROP_IMAGE_ACTIVITY_REQUEST_CODE`
B:  you removed this Activity start/result mechanism

> <img width="881" alt="image" src="https://user-images.githubusercontent.com/3314607/204716243-74b94846-9136-4a11-b7f6-072524583846.png">

and this

> <img width="575" alt="image" src="https://user-images.githubusercontent.com/3314607/204716295-2407bd78-e0ee-4e65-8819-594bb9c6f7f4.png">

I didn't invented the code snippets but I received this pain.

What's the new way doing this, or what's the new recommended way to do this ?

**Comment by vanniktech** [comment]
https://github.com/CanHub/Android-Image-Cropper#migrating-from-android-image-cropper
