### ISSUE TITLE
Rotate image improvements

### ISSUE THREAD

**Issue by filipiandrader** [CanHub/Android-Image-Cropper#537]
I was developing a feature where I need to rotate the image by a specific angle, but I realized that the rotateImage function wasn't working correctly, when I was aligning it to any side and trying to go back one or two degrees it didn't work correctly correct. I decided to see how it was being done and made the correction, I recorded two videos, the first is showing how it is currently and the second has already been corrected and working correctly.

before adjusting the method:

https://user-images.githubusercontent.com/90324370/207723300-12ecdf70-092d-4bd1-88b1-60ca77241880.mp4

after adjusting the method:

https://user-images.githubusercontent.com/90324370/207723267-0bc07486-5a05-406c-ba43-a6b2d0d9d131.mp4

I also noticed that it would be more interesting to change the parameter type from integer to float, in case someone wants to develop a feature using a range of values and these values have values of type float.

if you approve such changes, I can open a PR and it will have all the changes that were made

**Comment by vanniktech** [comment]
Yes, PR with any improvements are welcome! I don't use this particular feature.

**Comment by filipiandrader** [comment]
@vanniktech, but I have a problem, when I pass a negative angle and the method calculates the positive value, the crop overlay does not follow the photo correctly, do you know how I can adjust this for this fix?

**Comment by vanniktech** [comment]
Unfortunately no. I'm also new to this code base

**Comment by filipiandrader** [comment]
@Canato can you help me with this overlay bug?

**Comment by Canato** [comment]
@filipiandrader I would love to be able to help. But the rotation has been my worst nightmare on this lib.

It is literally the one thing that I couldn't do from my to-do list in this lib 😭.

My lame suggestion _(because you did much more them I was able)_ is to check for negative numbers and do the 360 math to make it positive.

Like `-90` rotation equals to `270`

**Comment by spporan** [comment]
After opening the CropImageActivity, the system back press does not work. Seems to be an interrupted system back press.

**Comment by Canato** [comment]
> After opening the CropImageActivity, the system back press does not work. Seems to be an interrupted system back press.

Sorry @spporan is this related to the rotation?
