### ISSUE TITLE
No apps can perform this action

### ISSUE THREAD

**Issue by YoussefIbrahim80** [CanHub/Android-Image-Cropper#538]
when I use this on a tablet and attempt to open the camera it states it can't find the camera app to take the needed picture.
![Screen Shot 2023-01-10 at 6 06 58 PM](https://user-images.githubusercontent.com/104222661/211572661-32afcc21-2fa7-4acb-a46f-94e92173cf6f.png)

**Comment by vanniktech** [comment]
Yeah that's wanted, if there's no camera on that tablet.
