### ISSUE TITLE
compileSdkVersion of at least 33

### ISSUE THREAD

**Issue by tomascrespo** [CanHub/Android-Image-Cropper#539]
Hi! I am using your library successfully, but when I build a Java project it says me: 

> 5 issues were found when checking AAR metadata:
> 
>   1.  Dependency 'androidx.activity:activity:1.6.0' requires libraries and applications that
>       depend on it to compile against version 33 or later of the
>       Android APIs.
> 
>       :app is currently compiled against android-32.
> 
>       Recommended action: Update this project to use a newer compileSdkVersion
>       of at least 33, for example 33.
> 
>       Note that updating a library or application's compileSdkVersion (which
>       allows newer APIs to be used) can be done separately from updating
>       targetSdkVersion (which opts the app in to new runtime behavior) and
>       minSdkVersion (which determines which devices the app can be installed
>       on).
> 
>   2.  Dependency 'androidx.activity:activity-ktx:1.6.0' requires libraries and applications that
>       depend on it to compile against version 33 or later of the
>       Android APIs.
> 
>       :app is currently compiled against android-32.
> 
>       Recommended action: Update this project to use a newer compileSdkVersion
>       of at least 33, for example 33.
> 
>       Note that updating a library or application's compileSdkVersion (which
>       allows newer APIs to be used) can be done separately from updating
>       targetSdkVersion (which opts the app in to new runtime behavior) and
>       minSdkVersion (which determines which devices the app can be installed
>       on).
> 
>   3.  Dependency 'androidx.core:core:1.9.0' requires libraries and applications that
>       depend on it to compile against version 33 or later of the
>       Android APIs.
> 
>       :app is currently compiled against android-32.
> 
>       Recommended action: Update this project to use a newer compileSdkVersion
>       of at least 33, for example 33.
> 
>       Note that updating a library or application's compileSdkVersion (which
>       allows newer APIs to be used) can be done separately from updating
>       targetSdkVersion (which opts the app in to new runtime behavior) and
>       minSdkVersion (which determines which devices the app can be installed
>       on).
> 
>   4.  Dependency 'androidx.core:core-ktx:1.9.0' requires libraries and applications that
>       depend on it to compile against version 33 or later of the
>       Android APIs.
> 
>       :app is currently compiled against android-32.
> 
>       Recommended action: Update this project to use a newer compileSdkVersion
>       of at least 33, for example 33.
> 
>       Note that updating a library or application's compileSdkVersion (which
>       allows newer APIs to be used) can be done separately from updating
>       targetSdkVersion (which opts the app in to new runtime behavior) and
>       minSdkVersion (which determines which devices the app can be installed
>       on).
> 
>   5.  Dependency 'androidx.annotation:annotation-experimental:1.3.0' requires libraries and applications that
>       depend on it to compile against version 33 or later of the
>       Android APIs.
> 
>       :app is currently compiled against android-32.
> 
>       Recommended action: Update this project to use a newer compileSdkVersion
>       of at least 33, for example 33.
> 
>       Note that updating a library or application's compileSdkVersion (which
>       allows newer APIs to be used) can be done separately from updating
>       targetSdkVersion (which opts the app in to new runtime behavior) and
>       minSdkVersion (which determines which devices the app can be installed
>       on).

So I have to set compileSdkVersion to 33, which is very restrictive. 

Does really your lib requiere SDK 33 or is it some problem related with my project?

I am importing:
`implementation 'com.vanniktech:android-image-cropper:4.5.0'`

**Comment by vanniktech** [comment]
AndroidX is forcing this on us. It's time for everyone to upgrade. Better now when you still have time.
