### ISSUE TITLE
[BUG] - NPE when accepting a photo on Android 11

### ISSUE THREAD

**Issue by hlupico** [CanHub/Android-Image-Cropper#54]
- 2.0.3
 
**Describe the bug**
A user that opts to take a photo can capture a picture and upon accepting the photo (aka, tapping on the check mark) they are returned to destination that launched CropImageActivity.

What's happening is an NPE is thrown (see below) when user accepts the photo, CropImageActivity.onActivityResult is called with `resultCode == RESULT_CANCELED`. 

`2021-02-10 09:45:14.860 6815-6815/? E/CAM_StateMachine: Failed to process event: com.android.camera.captureintent.event.EventTapOnConfirmPhotoButton@f96e55 `

`2021-02-10 09:45:14.861 6815-6815/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.camera2, PID: 6815
    java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:890)
        at com.google.common.base.Optional.of(Optional.java:103)
        at com.android.camera.captureintent.state.StateSavingPicture.onEnter(StateSavingPicture.java:77)
        at com.android.camera.captureintent.stateful.StateMachineImpl.jumpToState(StateMachineImpl.java:62)
        at com.android.camera.captureintent.stateful.StateMachineImpl.processEvent(StateMachineImpl.java:110)
        at com.android.camera.captureintent.state.StateOpeningCamera$9.onClick(StateOpeningCamera.java:307)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
`

**To Reproduce**
1. From CropImageActivity, select Camera option
2. Accept permissions if needed
3. Take photo
4. Accept Photo
5. CropImageActivity is cancelled, NPE reported above is thrown.

**Expected behavior**
1. From CropImageActivity, select Camera option
2. Accept permissions if needed
3. Take photo
4. Accept Photo
5. CropImageActivity proceeds to crop image

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Emulator, Pixel 3a 
 - OS: API 30

**Additional context**

**Comment by Canato** [comment]
@hlupico Thanks for this, indeed we need to fix this, I will add in the todo, but please feel free to jump into the code if you believe you got the issue,

**Comment by hlupico** [comment]
@Canato - Thanks! I'll circle back to take a deeper look tomorrow.

**Comment by gautamDev36** [comment]
Have you resolved this issue ? I am also getting this issue from gallery file pick too. My device is Samsung M2 os 11.

**Comment by Canato** [comment]
Hey @gautamDev36 the issue still open, so sadly no one had the time yet to solve the issue. Is one of the priorities on the ToDo.

I will add the label `Help wanted` if someone else wanna jump in and open a PR to fix this.

**Comment by hlupico** [comment]
Hey all, I haven't had the change to look at this. I'm in Austin, Texas and its just been a hot mess here. It's on my radar but not sure when I'll get to it.

**Comment by Canato** [comment]
Just to let you know, I will start to work in a sample code using the `CropImageActivity` so we can reproduce it locally and fix! 
Is my next task

**Comment by kaanhangithub** [comment]
After the latest version 2.1.1, the problem has been resolved for me. I used device: Emulator, Pixel 3a
Operating System: API 30.

**Comment by Canato** [comment]
@hlupico @gautamDev36  can you try on te latest `2.2.1` ?

If doesn't work I finish to add 3 types of sample in the codebase, could you please try to replicate it on the sample code?

I will remove the `pinned` tag until we have answers =)

**Comment by bharathkm7** [comment]
> After the latest version 2.1.1, the problem has been resolved for me. I used device: Emulator, Pixel 3a
> Operating System: API 30.

Hi Can you brief what is this version 2.1.1 for?

**Comment by Canato** [comment]
@bharathkm7 thanks for checking, but I'm having hard time to reproduce, the issue description says

>To Reproduce
>Steps to reproduce the behavior:
>1. From CropImageActivity, select Camera option
>1. Accept permissions if needed
>1. Take photo
>1. Accept Photo
>1. CropImageActivity is cancelled, NPE reported above is thrown.

If you run the sample project we have 3 buttons, the latest 2 buttons use CropImageActivity, but they are working, could you try to reproduce the issue there? Maybe is a device/OS issue that I'm not hitting.

I'm having a hard time to spot the problem without being able to reproduce it.

You can use the second option `Sample of CustomActivity`

**Comment by kaanhangithub** [comment]
> > After the latest version 2.1.1, the problem has been resolved for me. I used device: Emulator, Pixel 3a
> > Operating System: API 30.
> 
> Hi...what is this version 2.1.1 for? I am still facing this issue

After android 11, I think we need to use a **file provider** in our code, this might be the problem?
add file provider in android manifest.xml
<provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"></meta-data>
</provider>
file_paths.xml
 <?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-files-path name="files" path="." />
</paths>
this might help. Works for me.

**Comment by kaanhangithub** [comment]
> > After the latest version 2.1.1, the problem has been resolved for me. I used device: Emulator, Pixel 3a
> > Operating System: API 30.
> 
> Hi...what is this version 2.1.1 for? I am still facing this issue

Adding a file provider in the android manifest might help. Since after android 11, we have to deliver URI by file provider.

**Comment by Canato** [comment]
> > > After the latest version 2.1.1, the problem has been resolved for me. I used device: Emulator, Pixel 3a
> > > Operating System: API 30.
> > 
> > Hi...what is this version 2.1.1 for? I am still facing this issue
> 
> Adding a file provider in the android manifest might help. Since after android 11, we have to deliver URI by file provider.

@kaanhangithub indeed you are right about it!

But I try to add a library file provider. That should been merged in the app Manifest.

You can see we have a empty custom file provider class. 

The goal was to avoid the need of this to use the library, maybe is not fully working :///

**Comment by groupboard** [comment]
Yes, you need to use FileProvider. Solution: https://stackoverflow.com/a/66859444/1192732

**Comment by Canato** [comment]
@groupboard thanks for the suggestion. Not sure if `you` means the library or the users. But indeed the library use `FileProvider`

**Comment by ashcode1997** [comment]
@groupboard still I'm not able to crop the image when selecting the camera option .

**Comment by groupboard** [comment]
@ashcode1997 Yes, I looked at the code, and it looks fine. Does it stop crashing when you remove this line?:

`intent.putExtra(MediaStore.EXTRA_OUTPUT, outputFileUri)`

and is it definitely going into the         "if (isAtLeastQ29()) {" block of getCaptureImageOutputUri ?

**Comment by ashcode1997** [comment]
No it is not going , when I select the camera the result code is 0 and the intent is null

**Comment by Canato** [comment]
> No it is not going , when I select the camera the result code is 0 and the intent is null

Do you have the camera permissions in your Manifest?

**Comment by ashcode1997** [comment]
Yeah , only facing this issue in android 11

**Comment by Canato** [comment]
> Yeah , only facing this issue in android 11

@ashcode1997 can you reproduce in one of the sample apps in this repository?
