### ISSUE TITLE
AIC   I   Try get URI for scope storage - content://

### ISSUE THREAD

**Issue by Bilel-Android** [CanHub/Android-Image-Cropper#541]
I had this debug info when I tried to create a bitmap from uricontent in the block "  result.isSuccessful() ", and as result I can't get the cropped image in my imageView. here is the code (Java) :

private final ActivityResultLauncher<CropImageContractOptions> cropImage = registerForActivityResult(
            new CropImageContract(),
            result -> {
                if(result.isSuccessful()){
                    // Use the returned uri.
                    Uri uriContent = result.getUriContent();
                    Bitmap imageBitmap = null;
                    try{
                        if (Build.VERSION.SDK_INT < 29) {
                            imageBitmap = MediaStore.Images.Media.getBitmap(
                                    this.getContentResolver(), uriContent);
                        } else {
                            imageBitmap = ImageDecoder.decodeBitmap(ImageDecoder.createSource(
                                    this.getContentResolver(), uriContent));
                        }
                    } catch (IOException e) {
                        Log.e(TAG, "IOException:"+e.getMessage(), new RuntimeException(e));
                    }

                    binding.myImageView.setImageBitmap(imageBitmap);

                } else {
                    // An error occurred.
                    String exception = result.getError().getMessage();
                    Log.e(TAG,  exception, new Throwable());
                }
            });

**Comment by vanniktech** [comment]
Please consult with the sample app
