### ISSUE TITLE
Result getUriFilePath return incorrect file path

### ISSUE THREAD

**Issue by andreiVas80** [CanHub/Android-Image-Cropper#545]
Android API 31.
Pre requirements
1. Go to camera and make photo.
2. Open CropImageActivity and crop the image
3. On registerForActivityResult get CropResult and call `getUriFilePath` with parameter uniqName = false

Now:
1. Go to Gallery and take image
2. Open CropImageActivity and crop the image
3. On registerForActivityResult get CropResult and call `getUriFilePath` with parameter uniqName = false
4. Result from 3 use in imageView

Actual: Image from Pre requirements will be shown
Expected: Image from gallery will be shown

**Comment by vanniktech** [comment]
Just roll your own Activity and use the CropImageView.
