### ISSUE TITLE
Picture cache

### ISSUE THREAD

**Issue by morningos** [CanHub/Android-Image-Cropper#546]
There are too much `cropped` image cache, is there any funtion to remove those cache? I have to delete them by myself when app exiting...

![image](https://user-images.githubusercontent.com/44289789/218541298-7207f831-b8c5-4b16-9813-a82998e296f0.png)

Can you add `file.deleteOnExit()` or use same name cache file to make the folder clear,

**Comment by Canato** [comment]
Hey @morningos, is not exactly cache clean, but there is a option to make you cache only one image per time

What happens is that you can override every time you make a crop, so be aware in case you need to access a previously cropped image later.

You can call this method directly and change `uniqueName` value, which will make it override using the same value
```kt
    /**
     * The file path of the image to load
     * Null if you get cropped image was executed, no output requested or failure.
     *
     * [context] used to access Android APIs, like content resolve, it is your activity/fragment/widget.
     * [uniqueName] If true, make each image cropped have a different file name, this could
     * cause memory issues, use wisely.
     */
    fun getUriFilePath(context: Context, uniqueName: Boolean = false): String? =
      uriContent?.let { getFilePathFromUri(context, it, uniqueName) }
```

On the sample app, there is a usage of how this can be achieved.

@vanniktech I see we don't have the documentation with the methods list and the FAQ. 
Would you like me to add this information somewhere for future users?

**Comment by Canato** [comment]
@morningos another option, maybe more elegant, if you don't want to lose the previous cropped value is to set your own `customOutputUri` when calling `croppedImageAsync()` or when you put your `CropImageOptions`.

This means you can decide on the URI and clear later or override it.

To be honest, I thing this /\ will solve you issue and what I present before may not 🤔

**Comment by vanniktech** [comment]
> @morningos another option, maybe more elegant, if you don't want to lose the previous cropped value is to set your own `customOutputUri` when calling `croppedImageAsync()` or when you put your `CropImageOptions`.

Yeah honestly, this should be enforced. I also use the `customOutputUri` parameter.

> I see we don't have the documentation with the methods list

The library / code is the documentation. We could improve this sentence though:

```
If true, make each image cropped have a different file name, this could
     * cause memory issues, use wisely.
```

Also never understood why it's related to causing memory issues.
