### ISSUE TITLE
Getting crash in  android 12

### ISSUE THREAD

**Issue by Ganeshkumar1010** [CanHub/Android-Image-Cropper#547]
The issue showing like this 
2023-02-24 12:17:02.054 11317-11317 
StrictMode              com.example.croppersample            D  StrictMode policy violation; ~duration=601 ms: android.os.strictmode.DiskReadViolation
![image](https://user-images.githubusercontent.com/101241567/221111785-7c48cdb0-4366-4106-b395-2690ec966e9f.png)

**Comment by vanniktech** [comment]
PR welcome!

**Comment by vanniktech** [comment]
I don't see any reference to this library in the stacktrace.
