### ISSUE TITLE
Wrong text of action bar title  in urdu locale 

### ISSUE THREAD

**Issue by Ayesha17** [CanHub/Android-Image-Cropper#550]
crop_image_menu_crop the text against this key in urdu is wrong . please change to تصویر کو تراشیں

**Comment by vanniktech** [comment]
Happy to get a PR for this.

**Comment by Ayesha17** [comment]
@vanniktech can you please give me the rights or help me in creating a pull request. Because i got an error **Can't create a new pull request: Push failed: ERROR: Permission to CanHub/Android-Image-Cropper.git denied to Ayesha17. Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.** I tried a lot of thing but nothing works

**Comment by Ayesha17** [comment]
@vanniktech can you get my pr ?

**Comment by vanniktech** [comment]
You need to submit one

**Comment by Ayesha17** [comment]
I am unable to create a pr. It shows me an error 
**fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.** 
Can you please help me with this error?

**Comment by vanniktech** [comment]
Closed by #554
