### ISSUE TITLE
Modify Crop text

### ISSUE THREAD

**Issue by DeveloperAdam** [CanHub/Android-Image-Cropper#555]
How to modify the Crop text as i want it to be "Done" instead of "Crop". Check the attachment 
![WhatsApp Image 2023-03-15 at 9 00 21 AM](https://user-images.githubusercontent.com/31724563/225211372-451569d9-0544-4159-ba6a-361e33ca8135.jpeg)

**Comment by vanniktech** [comment]
Create your own activity and just use the CropImageView. Or alternatively, override the string resource.
