### ISSUE TITLE
Access view crop!

### ISSUE THREAD

**Issue by CharlesMSilva** [CanHub/Android-Image-Cropper#558]
Hello!

I would like to know if I can somehow get the view of the crop, because I saw that it is private, I wanted to add a tooltip in the position that the view of the crop is.

Would there be any way?

**Comment by vanniktech** [comment]
It's public. https://github.com/CanHub/Android-Image-Cropper/blob/main/cropper/src/main/kotlin/com/canhub/cropper/CropImageView.kt just roll your own activity.

**Comment by CharlesMSilva** [comment]
@vanniktech I'm referring to the cutting part CropOverlayView.
