### ISSUE TITLE
Missing Method getCroppedImageAsync()

### ISSUE THREAD

**Issue by mandrachek** [CanHub/Android-Image-Cropper#560]
Attempting to convert an old project from theartofdev version, and tried both 4.3.3 as recommended and 4.5.0, however
`cropImageView.getCroppedImageAsync()` does not appear to exist, although it's still referenced in the readme.

**Comment by vanniktech** [comment]
Probably a left over. Feel free to PR a removal of the method in the README.

**Comment by karthickramanathan95** [comment]
What is the replacement for this method? @vanniktech

**Comment by fhalqahtani** [comment]
> Attempting to convert an old project from theartofdev version, and tried both 4.3.3 as recommended and 4.5.0, however `cropImageView.getCroppedImageAsync()` does not appear to exist, although it's still referenced in the readme.

cropImageView.croppedImageAsync(customOutputUri = uri)

**Comment by vanniktech** [comment]
That's right. Thanks @fhalqahtani

**Comment by abhishekdharwal-hexa** [comment]
How to use this 

cropImageView.croppedImageAsync(customOutputUri = uri)

**Comment by abhishekdharwal-hexa** [comment]
How to use this 

cropImageView.croppedImageAsync(customOutputUri = uri)
