### ISSUE TITLE
Increase image width or initial zoom.

### ISSUE THREAD

**Issue by CharlesMSilva** [CanHub/Android-Image-Cropper#562]
Hello! I'm using the library to capture screenshot.

The idea is to take a screenshot and open an activity with the image. Everything is working, but the image, as it has the dimensions of the device, turns out to be smaller when displayed in cropimageview.

What I would like to know is if I could at least increase the side width a little so that the screenshot is not too small.

I tried using an initial cropRect to define an initial zoom, but it doesn't affect the screen when opening, you have to touch it.

**Comment by vanniktech** [comment]
Just write your own activity and use the CropImageView directly.
