### ISSUE TITLE
Every cropped image is saving with a unique name in app files/Pictures 

### ISSUE THREAD

**Issue by sixdaystudio** [CanHub/Android-Image-Cropper#564]
When I crop an image using Android 12 or 12+, the cutter creates a file named "cropped3655457542457542.png", for example, in the application's file folder: `Android/data/app-name-space/files/Pictures`. This behavior causes each successive crop to have an incorrect file path in the result.

Steps:
1 -  Starts the launcher:
```kotlin
cropImage.launch(
    options {
        setGuidelines(CropImageView.Guidelines.ON)
        setAspectRatio(2, 3)
        setRequestedSize(592, 840, CropImageView.RequestSizeOptions.RESIZE_FIT)
        setActivityTitle(getString(R.string.activity_label_image_crop))
        setOutputCompressFormat(Bitmap.CompressFormat.PNG)
        setOutputCompressQuality(100)
    }
)
```
2 - On result if I need the `uriFilePath` the system keeps getting the last cropped image file, not the actual cropped. The actual cropped only works with the `uriContent` but the system keeps saving a new file with a cropped+randomNumber in name.

How to prevent the system to creates a new file every crop action?

**Comment by vanniktech** [comment]
There's a boolean option somewhere. Also, i'd advise you to set the target / output uri and that way you are in control where the file is stored.
