### ISSUE TITLE
Toolbar is not shown

### ISSUE THREAD

**Issue by AiSa639** [CanHub/Android-Image-Cropper#566]
supportActionBar is not being shown. Here is options:

CropImageOptions(
          imageSourceIncludeCamera = includeCamera,
          imageSourceIncludeGallery = includeGallery,
          guidelines = CropImageView.Guidelines.ON_TOUCH,
          fixAspectRatio = true,
          aspectRatioX = 4,
          aspectRatioY = 3,
          activityTitle = "activityTitle",
          cropMenuCropButtonTitle = "cropMenuCropButtonTitle",
          backgroundColor = colorCompat(R.color.color_black),
          toolbarColor = colorCompat(R.color.textBrand),
          toolbarTintColor = colorCompat(R.color.textBrand)
)

Am I missing some parameter in options? 

![telegram-cloud-photo-size-2-5352716753895016857-y](https://user-images.githubusercontent.com/24824398/234492333-ae4006ed-0ed7-42d7-ab6b-259f3e11c317.jpg)

**Comment by jeremybestdev** [comment]
any uck bro?

**Comment by vanniktech** [comment]
Please have a look at the sample app.

**Comment by hiteshsarsava** [comment]
@vanniktech Atleast Add some example to roll own activity. Also Add disclaimer in notes with Bold Letters. I wasted 2 hours for this. Because I am using No Action bar Activity Theme in App. Now these days all the devs using this practice.
