### ISSUE TITLE
Toolbar shadow flexibility

### ISSUE THREAD

**Issue by smaksym-phillips** [CanHub/Android-Image-Cropper#567]
I would be very grateful if U could add new flag to the CropImageOptions, so it would remove the toolbar shadow for more design flexibility.

if(toolbarElevationEnabled.not()) it.setElevation(0)

Somewhere here
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/129379845/235985844-d7151d87-01f1-40f7-8fb3-5818456da80e.png">

**Comment by vanniktech** [comment]
I'd prefer if we got rid of that entire bundled Activity alltogether and let everyone simply create their own Activity and just use the CropView. So, no. Unfortunately, not.
