### ISSUE TITLE
On older OS (Pie), top app bar is not visible

### ISSUE THREAD

**Issue by chrisagay** [CanHub/Android-Image-Cropper#569]
This is the view when used on a Pixel 2 XL running Q (29) or higher
![image](https://github.com/CanHub/Android-Image-Cropper/assets/15876311/e8de0dde-7a41-46c6-a6e6-fa52f5751f41)

But this is what I see when running a Pixel 2XL on Pie (28)
![image](https://github.com/CanHub/Android-Image-Cropper/assets/15876311/d5e47df9-2080-4d95-ac95-3d894d941c28)

Is there a setting I can enable to resolve this issue quickly?

**Comment by vanniktech** [comment]
Just roll your own Activity and use CropImageView directly.
