### ISSUE TITLE
[Feat] - Hello how I set to different request codes on same activity and on results after that???

### ISSUE THREAD

**Issue by fivedofficial** [CanHub/Android-Image-Cropper#57]
I want to add two different request codes to the same activity but it is only giving one 
public static final int PICK_IMAGE_CHOOSER_REQUEST_CODE = 200;

I cannot use the same CHOOSER on both image pickers.

**Comment by Canato** [comment]
Hey @fivedofficial  thanks for the question. 
I will move this under `Discussion - Q&A` 

if in the end of the discussion we realize we need a new feature or bug fix we can open an issue for this =).

====
Now, about your question, can you show the code you are calling? 
The code related to `PICK_IMAGE_CHOOSER_REQUEST_CODE` is to be sure you get the answer from our activity.

The idea about activities is that you call the activity with the request code and get the value back based on the request code, I don't see the need for having two request code on the same time. But what could be possible is to give the user a choice of override the default request code. Would not be hard to do this! 

Just need to understand better what this is about =)

Thanks!
