### ISSUE TITLE
Jepack compose integration is freezing

### ISSUE THREAD

**Issue by williankl** [CanHub/Android-Image-Cropper#579]
So, basically just by adding this:

```
@Composable
public fun CropperWrapper(
    sourceImage: Bitmap,
    modifier: Modifier = Modifier,
) {
    AndroidView(
        modifier = modifier,
        factory = { context -> CropImageView(context) },
        update = { cropImageView ->
            cropImageView.setImageBitmap(sourceImage)
        }
    )
}
```

The app freezes with no error or issue being logged (as far as I saw).
Any ideas? I'll try and look through the source code to find a solution, but a helping hand would be great here. 👀

**Comment by williankl** [comment]
Only thing that I found until now is that it does not freeze if I remove the `cropImageView.setImageBitmap(sourceImage)` line.
But also does not show anything (as expected).

**Comment by williankl** [comment]
Okay, found an interesting solution. Seems like the problem is that it is entering a infine loop calling the `onLayout` method. Changing the parent layout to a `LinearLayout` as such:
```
@Composable
public fun ProCropper(
    sourceImage: Bitmap,
    modifier: Modifier = Modifier,
) {
    AndroidView(
        modifier = modifier,
        factory = { context -> LinearLayout(context) },
        update = { layout ->
            val cropper = CropImageView(layout.context)
            layout.addView(cropper)
            cropper.setImageBitmap(sourceImage)
        }
    )
}
```
Made it work like a charm. When I clear some time, I'll try to take a deeper look into this problem. But for now, let's call this a solution.

**Comment by vanniktech** [comment]
Thanks for sharing your workaround!

**Comment by TwilightKHQ** [comment]
@williankl it's useful for me. thinks!
```
AndroidView(
    modifier = Modifier.fillMaxSize(),
    factory = { context: Context ->
        val viewRoot = LayoutInflater.from(context).inflate(
            R.layout.layout_picture_crop, null, false
        ) as LinearLayout
        cropImageView = viewRoot.findViewById<CropImageView>(R.id.cropImageView).apply {
            setImageBitmap(bitmap)
        }
        viewRoot
    },
    update = { layout ->
        layout.children.forEach { child ->
            if (child is CropImageView) cropImageView = child
        }
    })
```

**Comment by ZQ-BB** [comment]
it really works , but i want to konw why it happens ?
