### ISSUE TITLE
Scale image after cropping

### ISSUE THREAD

**Issue by deM1d** [CanHub/Android-Image-Cropper#581]
Hi. I want to scale cropped image to specific size. For example I want image side must be maximum 1024 px. After user picked and cropped image it will be scaled(Example : Source(width=2048, height=512). Result(width=1024, height=256)). Is there easy way to do it by this library or I should scale image by my hands?
Thanks for help guys!

**Comment by vanniktech** [comment]
Call the scale method with the desired with on the CropImageView.

**Comment by deM1d** [comment]
I use cropping directly(by CropImageContract) without CropImageView.

**Comment by vanniktech** [comment]
Then you'll have to switch to `CropImageView` or do the cropping directly.

In my opinion, I'd get rid of the `CropImageContract`s but I know a lot of people use them.

**Comment by deM1d** [comment]
Thank you for help!
