### ISSUE TITLE
screenshot position offset

### ISSUE THREAD

**Issue by xiao2612278** [CanHub/Android-Image-Cropper#583]
![image](https://github.com/CanHub/Android-Image-Cropper/assets/9213888/6a290a49-795c-4ec8-bb35-30f595ff02fd)
![image](https://github.com/CanHub/Android-Image-Cropper/assets/9213888/54c43fac-d744-4a9c-82a2-9cdf66131a5d)

The intercepted area is inconsistent with the returned result;
The bottom will move up and the right area will move right!

**Comment by vanniktech** [comment]
Never had this problem, but feel free to create a PR

**Comment by Magic-Books** [comment]
I have also encountered similar problems before, and ultimately found out that it was due to the use of AutoSize. You need to confirm if it is the same problem or if you are using other UI adapted third-party libraries.
