### ISSUE TITLE
Feat: Exclude low res images in picker.

### ISSUE THREAD

**Issue by EzequielAdrianM** [CanHub/Android-Image-Cropper#586]
Hello, is there any possibility of making the Gallery picker exclude (do not even show to the user) images that are too low in resolution, for example thumbnails (smaller than 96x96). Or should we create our custom picker then pass the picker result Uri to the image cropper.

**Comment by vanniktech** [comment]
> Or should we create our custom picker then pass the picker result Uri to the image cropper.

Yep.
