### ISSUE TITLE
Can't import 'options' in 4.5.0 version

### ISSUE THREAD

**Issue by p42rthicle** [CanHub/Android-Image-Cropper#592]
```
cropImageLauncher.launch(
        option {
          
        }
      )
```

Can't import the options block here from com.canhub.cropper.options

What is the replacement for it in 4.5.0 version?

**Comment by NicolasGodfather** [comment]
the same

**Comment by Himanshu3009** [comment]
Try this 
```
var cropImageContractOptions = CropImageContractOptions(data?.data,CropImageOptions(imageSourceIncludeGallery = false,imageSourceIncludeCamera= true));
cropImageLauncher.launch(cropImageContractOptions);
```

**Comment by azizur-rehman** [comment]
> Try this
> 
> ```
> var cropImageContractOptions = CropImageContractOptions(uri,CropImageOptions(imageSourceIncludeGallery = true,imageSourceIncludeCamera= true));
> cropImageLauncher.launch(cropImageContractOptions);
> ```

what is uri?

**Comment by HamzaAkram-shyk** [comment]
cropImage.launch(
      options(uri = imageUri) {
        setGuidelines(Guidelines.ON)
        setOutputCompressFormat(CompressFormat.PNG)
      }
    )
    
  Can't import these things 

What is the replacement for it in the 4.5.0 version?

**Comment by ronycodex** [comment]
Hey I have just found the solution.
Drop a ❣️ if i helped you.

`cropImage.launch(
                    CropImageContractOptions(
                        uri = uri,
                        cropImageOptions = CropImageOptions(
                            guidelines = CropImageView.Guidelines.ON,
                            outputCompressFormat = Bitmap.CompressFormat.PNG,
                            outputCompressQuality = 50,
                            fixAspectRatio = true,
                            aspectRatioX = 1,
                            aspectRatioY= 1,
                        )
                    )
                )`
