### ISSUE TITLE
How to restore cropOverlayWindow after fragment resume()?

### ISSUE THREAD

**Issue by kenslee-studio** [CanHub/Android-Image-Cropper#594]
I am making an app where the user crops a region on Image and takes it to other fragment , from there he can come back or save that part , but when he comes back cropOverlayWindow comes back to its initial position.  I want to keep it intact. Same happens when user pushes app in background and again resumes it

Also apart from this, there is one more problem. When the distance between borders is too close we can't move the frame at all , to see this bug try using aspect ratio of 1 : 5 or 1 : 6

**Comment by vanniktech** [comment]
I think this is similar to https://github.com/CanHub/Android-Image-Cropper/issues/589 and hence closing. If you disagree please leave a comment
