### ISSUE TITLE
How to use CropImageView in Compose?

### ISSUE THREAD

**Issue by phongbm** [CanHub/Android-Image-Cropper#596]
I want to use CropImageView in Compose project, how to do that?

**Comment by Pantsoffski** [comment]
Like this: 

`val cropImage = rememberLauncherForActivityResult(CropImageContract()) { result ->
        if (result.isSuccessful) {
            // Use the returned uri.
            val uriContent = result.uriContent
            val uriFilePath = result.getUriFilePath(context) // optional usage
        } else {
            // An error occurred.
            val exception = result.error
        }
    }` 

and start with e.g. this: 

`cropImage.launch(
            CropImageContractOptions(
                uri = null,
                cropImageOptions = CropImageOptions(
                    imageSourceIncludeGallery = true,
                    imageSourceIncludeCamera = false,
                    fixAspectRatio = true
//                    aspectRatioX = 1,
//                    aspectRatioY = 1,
                )
            )
        )`

**Comment by hoangchungk53qx1** [comment]
https://gist.github.com/hoangchungk53qx1/b17356cc82515666058b3d53781bf5d5

**Comment by vanniktech** [comment]
Seems like there is a solution. We don't have official Compose support, but I'm willing to take PRs that either improve the overall component / provide a proper Compose support.

**Comment by maztak** [comment]
Pantsoffski's formatted code

```kotlin
    val cropImage = rememberLauncherForActivityResult(CropImageContract()) { result ->
        if (result.isSuccessful) {
            // Use the returned uri.
            val uriContent = result.uriContent
            val uriFilePath = result.getUriFilePath(context) // optional usage
        } else {
            // An error occurred.
            val exception = result.error
        }
    }

    cropImage.launch(
        CropImageContractOptions(
            uri = null,
            cropImageOptions = CropImageOptions(
                imageSourceIncludeGallery = true,
                imageSourceIncludeCamera = false,
                fixAspectRatio = true
                // aspectRatioX = 1,
                // aspectRatioY = 1,
            )
        )
    )
```
