### ISSUE TITLE
Is there any callback when crop window is ready to crop?

### ISSUE THREAD

**Issue by azizanhakim** [CanHub/Android-Image-Cropper#6]
I am trying cropImageView.cropRect = myRect
then when I try cropImageView.croppedImage immediattly not getting the exact myRect area cropped bitmap.
Is your library taking some time to draw a rectangle on the image?
If yes is there any callback available so that I can know - Yeah my area is ready now I can call getCroppedImage() method on it.

**Comment by Canato** [comment]
Hey @azizanhakim could not fully get you, could you give me more context ? 

What are you trying to do? use the built-int crop activity, or use the crop image in a custom activity? This image come from gallery/camera or is the one the library is getting?

Are you using [this guide](https://github.com/CanHub/Android-Image-Cropper/wiki/Set-initial-crop-window-rectangle) ?

Sorry to make more questions, still going down in the lib details
