### ISSUE TITLE
[BUG] - Android 11 one time permission crash

### ISSUE THREAD

**Issue by KurasovAnton** [CanHub/Android-Image-Cropper#60]
Library version
 - 1.0.0
 - https://github.com/ArthurHub/Android-Image-Cropper (2.8.0)
 
**Describe the bug**
The app crashes after some time on the camera screen if the One-time permission chosen.

"If the user sends your app to the background, your app can continue to access the data for a short period of time." (https://developer.android.com/training/permissions/requesting#one-time)
The app went to the background when the camera is opened.

**To Reproduce**
1. Choose the image from the camera
2. Give "Only this time" permission
3. Stay on camera app for 1 minute.
4. The app crashes

**Expected behavior**
The app shouldn't crash

**Smartphone (please complete the following information):**
 - Device: Pixel 2, pixel 3xl emulator
 - OS: Android 11

**Comment by Canato** [comment]
Hey @KurasovAnton we have some fixes around OS 10 and 11 on the latest releases.

Can you check if work with the latest library? `2.1.0`
