### ISSUE TITLE
[Help Wanted] - Build failed with AAPT: error:unexpected element <queries> found in <manifest>.

### ISSUE THREAD

**Issue by JibuVarghese** [CanHub/Android-Image-Cropper#61]
- Lib Version [e.g. 1.1.0]
 
**Describe the bug**
After adding implementation 'com.github.CanHub:Android-Image-Cropper:2.1.0' build failed with error /Users/oc/.gradle/caches/transforms-2/files-2.1/225e0e7423424895791e1e3386ede31a/Android-Image-Cropper-2.1.0/AndroidManifest.xml:11:5-22:15: AAPT: error: unexpected element <queries> found in <manifest>.
    

**Smartphone (please complete the following information):**
 - Device: Samsung M30
 - OS: Android 11

**Additional context**

**Comment by JibuVarghese** [comment]
Updating the gradle version to 4.0.2 fixed the issue.
classpath 'com.android.tools.build:gradle:4.0.2'

**Comment by Canato** [comment]
@JibuVarghese thanks for raising and finding the fix! hahahah

This can help more people in the future. \o/ 🎉
