### ISSUE TITLE
ActivityResultContract for custom activity

### ISSUE THREAD

**Issue by andriishpek-sigma** [CanHub/Android-Image-Cropper#611]
It would be nice if `CropImageContract` allows to provide custom activity class. Currently I need to implement custom contract with delegation to library implementation:

```
class CustomCropImageContract :
    ActivityResultContract<CropImageContractOptions, CropImageView.CropResult>() {

    private val delegate = CropImageContract()

    override fun createIntent(context: Context, input: CropImageContractOptions): Intent {
        return delegate.createIntent(context, input).apply {
            setClass(context, CropImage::class.java)
        }
    }

    override fun parseResult(resultCode: Int, intent: Intent?): CropImageView.CropResult {
        return delegate.parseResult(resultCode, intent)
    }

    override fun getSynchronousResult(
        context: Context,
        input: CropImageContractOptions
    ): SynchronousResult<CropImageView.CropResult>? {
        return delegate.getSynchronousResult(context, input)
    }
}
```

`CropImageContractOptions` may be a good place to provide custom `class`.

**Comment by vanniktech** [comment]
Roll your own activity and just use the CropImageView.

**Comment by andriishpek-sigma** [comment]
@vanniktech  That's not the question I'm asking. I am using my own activity. And I have to write this crutch as above for result handing, simply because your default result contract isn't suitable for custom activities.

**Comment by vanniktech** [comment]
> simply because your default result contract isn't suitable for custom activities.

Yeah also this I'm planning to deprecate. It makes no sense to use this from the library if you are writing your own Activity.

**Comment by andriishpek-sigma** [comment]
> It makes no sense to use this from the library if you are writing your own Activity.

It does. I extend `CropImageActivity` that returns as a result `CropImageView.CropResult`. On the other hand `CropImageContract` properly parses and returns actual instance of `CropImageView.CropResult`. 

The point of my suggestion is that `CropImageActivity` can be extended, but `CropImageContract` cannot (it explicitly creates an intent on `CropImageActivity`)
