### ISSUE TITLE
Can I Customize Crip Edit Screen In Android Compose?

### ISSUE THREAD

**Issue by jminie-o8o** [CanHub/Android-Image-Cropper#612]
Hello I am Android Developer from South Korea. First, Thank you for this Wonderful Tool

I would like to customize the screen itself to crop the image, i.e. customize the CropImageActivity. Is there any way to do this?

<img width="160" alt="스크린샷 2024-01-31 오후 5 24 50" src="https://github.com/CanHub/Android-Image-Cropper/assets/79504043/da7e39c5-3250-4d22-a636-b3b667f1bd3e">

Want to Edit this Screen

**Comment by vanniktech** [comment]
Just roll your own activity / compose whatever and use the existing view.
