### ISSUE TITLE
[Feature Request] Support for Rounded Rectangle Crop Shape

### ISSUE THREAD

**Issue by tasy5kg** [CanHub/Android-Image-Cropper#622]
Currently, the library supports cropping images into rectangles and ovals, as defined by [CropShape](https://github.com/CanHub/Android-Image-Cropper/blob/main/cropper/src/main/kotlin/com/canhub/cropper/CropImageView.kt#L1556-L1565).

I kindly request the implementation of cropping into rounded rectangles.

Despite the availability of methods like Canvas.drawRoundRect() in the Android SDK, integrating this functionality into [CropImageView](https://github.com/CanHub/Android-Image-Cropper/blob/main/cropper/src/main/kotlin/com/canhub/cropper/CropImageView.kt) would streamline the cropped preview view experience.

Thank you sincerely for considering this feature request, and for providing this user-friendly and robust image cropping library for every Android developer.

**Comment by vanniktech** [comment]
Isn't rounded rect an oval?

**Comment by tasy5kg** [comment]
> Isn't rounded rect an oval?

I don't think so... maybe I didn't express myself clearly. I want the picture to be cropped into a rectangle with the four corners of the rectangle rounded, like this:

![tasy5kg-vIm2dkS73Vo-unsplash_round_rect](https://github.com/CanHub/Android-Image-Cropper/assets/30869777/25c4b989-ade4-425c-8af9-5ecc38919ed7)

**Comment by vanniktech** [comment]
Ah I would advise against this and do it on your view layer instead and save the pictures always as a rectangle. You're much more flexible with this.

**Comment by tasy5kg** [comment]
Thank you, I think you have a point and I agree with you. 🙏
