### ISSUE TITLE
Allow selecting multiple images at a time from the Gallery

### ISSUE THREAD

**Issue by aelkaragy** [CanHub/Android-Image-Cropper#626]
### Feature request
We currently need to have the **MultipleImageSelection** feature in the CropImageOptions. 

If enabled, 

- the user can select multiple images from the Gallery,
- and then the Crop Image Activity is shown for each one of the selected images subsequently.

_Can we have this feature any time soon?_

**Comment by vanniktech** [comment]
Super unlikely. You should be able to do it yourself by using the CropImageView and rolling your own implementation for allowing multiple images

**Comment by vanniktech** [comment]
I'd rather not. Ideally, I would want the API to slim down way more so the only piece of thing you get is a perfect CropImageView that you can use in your Activity and have 100% flexibility with it and build custom solutions just like yours in your own repository. Less is more.
