### ISSUE TITLE
No toolbar / buttons to confirm the crop

### ISSUE THREAD

**Issue by rexmtorres** [CanHub/Android-Image-Cropper#629]
I just started using the library.  I'm using the 4.5.0 (latest as of this writing).  But when I launch it, by default, it just shows the image to be cropped in a white activity devoid of any buttons / toolbar.  I've tried the different settings in CropImageOptions, but none of them seem to show any buttons / toolbar.

Here are the settings I've tried:
```kotlin
imageCropper.launch(
    CropImageContractOptions(
        uri = uri,
        cropImageOptions = CropImageOptions(
            cropShape = CropImageView.CropShape.OVAL,
            aspectRatioX = 1,
            aspectRatioY = 1,
            fixAspectRatio = true,
            outputCompressQuality = 75,
            backgroundColor = Color.MAGENTA,
            activityBackgroundColor = Color.BLACK,
            toolbarColor = Color.BLUE,
            toolbarTitleColor = Color.WHITE,
            toolbarBackButtonColor = Color.CYAN,
            toolbarTintColor = Color.RED,
            activityMenuIconColor = Color.GREEN,
            activityMenuTextColor = Color.GREEN,
            showCropLabel = true,
            multiTouchEnabled = true,
            activityTitle = "Hello",
            cropperLabelText = "It's me"
        )
    )
)
```

As you can see from the screenshot below, there's no toolbar or any button to confirm the crop.  The `activityTitle` also does not show, which seems to indicate that there indeed is no toolbar.
![Screenshot_1716280613](https://github.com/CanHub/Android-Image-Cropper/assets/17244755/624f152f-4b7d-4633-9c5d-61c6bfd75124)

**Comment by vanniktech** [comment]
Just roll your own activity.

**Comment by rexmtorres** [comment]
Then maybe remove those parameters?  **toolbar**_**XXX**_, **activityMenu**_**XXX**_ would lead people to believe that those actually do something.

**Comment by Arise** [comment]
Trying to save the world, in your app AndroidManifest.xml, just add:
```
        <activity android:name="com.canhub.cropper.CropImageActivity"
            android:theme="@style/Base.Theme.AppCompat"/>
```
Crop tools should then display fine.

**Comment by hiteshsarsava** [comment]
@vanniktech Atleast Add some example to roll own activity. Also Add disclaimer in notes with **Bold Letters**. I wasted 2 hours for this. Because I am using No Action bar Activity Theme in App. Now these days all the devs using this practice.

**Comment by vanniktech** [comment]
https://github.com/CanHub/Android-Image-Cropper#2-using-cropview
