### ISSUE TITLE
How to block crop event in View ?

### ISSUE THREAD

**Issue by theduc0x** [CanHub/Android-Image-Cropper#630]
I want to block the crop event after setAspectRatio.
I have a list of AspectRatio and just let the user choose from those categories and the user can just drag and drop it in the View but I don't want the user to be able to crop the View again

![image](https://github.com/CanHub/Android-Image-Cropper/assets/78410128/416a571e-bc68-40b1-8916-83e671f6ae6f)

I want to block the crop event from the 4 corners like in that picture, but still keep the hold and move event on it

**Comment by vanniktech** [comment]
I think you'd want to set `fixAspectRatio = true`.

**Comment by vanniktech** [comment]
Closing as a duplicate of https://github.com/CanHub/Android-Image-Cropper/issues/620
