### ISSUE TITLE
Can't see crop and save option getting white screen backgroud

### ISSUE THREAD

**Issue by Iamthemax** [CanHub/Android-Image-Cropper#631]
private ActivityResultLauncher<CropImageContractOptions> cropImage =
            registerForActivityResult(new CropImageContract(), result -> {
                if (result.isSuccessful()) {
                    // Use the returned uri.
                    Uri uriContent = result.getUriContent();
                } else {
                    // An error occurred.
                    Exception exception = result.getError();
                }

            });

    private void startCrop() {

        CropImageOptions cropImageOptions=new CropImageOptions();
        cropImageOptions.guidelines= CropImageView.Guidelines.ON;
        cropImageOptions.cropMenuCropButtonTitle="Crop";
        cropImageOptions.guidelinesThickness= Color.RED;

        cropImage.launch(new CropImageContractOptions(null, cropImageOptions));

    }

![issue](https://github.com/user-attachments/assets/b718d359-5d03-4689-9df9-5f226d7bf1a8)

**Comment by vanniktech** [comment]
Roll your own activity and just use the CropImageView.
