### ISSUE TITLE
Cannot resolve symbol CropImage

### ISSUE THREAD

**Issue by artworkad** [CanHub/Android-Image-Cropper#645]
I followed the [migration instructions](https://github.com/CanHub/Android-Image-Cropper?tab=readme-ov-file#migrating-from-android-image-cropper) for an old project. When importing

    import com.canhub.cropper.CropImage;

I get `Cannot resolve symbol CropImage`. Any idea what the issue might be?

**Comment by vanniktech** [comment]
It might not exist any more. I don't know this type.

**Comment by artworkad** [comment]
My Kotlin version was too old. Updated to newer version to make it work.
