### ISSUE TITLE
Failed to transform Android-Image-Cropper-1.1.1.aar to match attributes {artifactType=android-assets}.

### ISSUE THREAD

**Issue by davmaene** [CanHub/Android-Image-Cropper#651]
hello there i'm trying to build my app under RN but i'm getting this issue
![Screenshot 2024-10-13 102410](https://github.com/user-attachments/assets/f703f79e-386f-4f78-bebc-351883f2ab97)

**Comment by vanniktech** [comment]
That version is too old
