### ISSUE TITLE
[BUG] - I am facing issue while migrating   from api 'com.theartofdev.edmodo:android-image-cropper:2.8.+' to  implementation 'com.github.CanHub:Android-Image-Cropper:2.1.0'

### ISSUE THREAD

**Issue by jagdeepmohd** [CanHub/Android-Image-Cropper#66]
- Lib Version [e.g. 1.1.0]
 
**Describe the bug** : I want to upgrade to this version because I am facing issues in android 11 for Camera option . It is giving me empty black screen instead of crop preview and error code is coming file is not image . Can you please confirm which version works fine with android 11 and how to include this library in project.
A clear and concise desc
![image](https://user-images.githubusercontent.com/35160366/108862483-48f05480-7616-11eb-9153-e85115a1a7fb.png)
ription of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3XL]

**Additional context**

**Comment by jagdeepmohd** [comment]
@Canato  : Can you please help me with setup of this library in my project.

**Comment by Canato** [comment]
Hey @jagdeepmohd did you check the readme file? 

The informations on this issues look like incomplete.

O the mean time, you can check this guide maybe? https://github.com/CanHub/Android-Image-Cropper/wiki/%F0%9F%9A%A8-How-to-migrate-Android-Image-Cropper--%F0%9F%9A%A8

Let me know if helps

**Comment by jagdeepmohd** [comment]
@Canato I am getting error while adding dependency to build.gradle. it is giving can't resolve this dependency.  I am using same steps given by you in migration .

**Comment by Canato** [comment]
@jagdeepmohd could you show the code you are using on the root `build.gradle` and on the module `build.gradle` ?

**Comment by jagdeepmohd** [comment]
@Canato  : It is resolved after making correction to root build.gradle .  I was using  maven { url 'https://jitpack.io' }  under buildscript   instead of allprojects  .  I hope android 11 : Camera permission issue is resolved with 2.1.0 version ? I will give this library a try tomorrow.

**Comment by Canato** [comment]
Perfect! @jagdeepmohd 

Let us know we fixed many issues about Android 10 and 11, but for sure there is some more to kill. Will close here, but feel free to open another issue or add your toughs on the ones that are open.

**Comment by aemb2084** [comment]
Hi Canato.-

I am having a problem implementing your library, apparently it cannot find it. How can I solve this problem?

![Screenshot 2021-07-20 233320](https://user-images.githubusercontent.com/21280986/126431364-dbf7d435-c810-479e-9052-216b965a0b37.png)

This is the configuration in my Gradle module:

![Screenshot 2021-07-20 233320](https://user-images.githubusercontent.com/21280986/126431585-8708e98e-da6d-40cf-a08e-f818b78b6204.png)

This is the configuration in my Gradle project:

![Screenshot 2021-07-20 233320](https://user-images.githubusercontent.com/21280986/126431663-4cea918c-661a-4a6d-8abc-99376abf1b3a.png)

**Comment by Canato** [comment]
Hey @aemb2084 you need to change `${version}` to the latest number version.

Today would be `implementation 'com.github.CanHub:Android-Image-Cropper:3.2.1'`

**One small tip, always open a new discussion or issue instead of updating a close one, we can miss this notification ;)**

**Comment by gaganO7** [comment]
Hey @Canato  i was using your library and stumble upon one problem which is the below method

setImagePickerContractOptions(
                        PickImageContractOptions(includeGallery = true, includeCamera = false)
                    )
this above method, i cannot find in your CropImageContractOptions file, so where i can find this method.
