### ISSUE TITLE
[BUG] - Inconsistency between Oval and Rectangle shapes

### ISSUE THREAD

**Issue by chriscoomber** [CanHub/Android-Image-Cropper#77]
- Lib Version [e.g. 2.1.1]
 
**Describe the bug**
For Rectangle shape: if you drag too far outside the crop window, nothing happens.
For Oval shape: if you drag far outside the crop window, it resizes the crop window as if you were touching the nearest handle (corners or sides).

**To Reproduce**
1. Go to the sample app.
2. Shrink the crop window a bit.
3. Try touching and dragging outside the crop window.
4. Now try with cropShape Oval

**Expected behavior**
Both crop shapes are consistent. I think I'd expect both to behave like the rectangular shape, i.e. if you touch too far outside the crop window nothing happens.

**Smartphone (please complete the following information):**
 - Device: Samsung S20FE
 - OS: Android 10

**Additional context**
This issue is caused, essentially, by the fact that `getOvalPressedMoveType` (in `CropWindowHandler.kt`) doesn't return null values for touches far outside the crop window, whereas `getRectanglePressedMoveType` does.

This is not a pressing issue for me. It could be a good first issue for someone to fix.

**Comment by Canato** [comment]
Indeed, this maybe be trick because of android xml are always a square. Will need a little math to return null when the area is outside the oval form.

A nice enhancement!

**Comment by Canato** [comment]
I was making some tests and looking other crop tools, we have the guidelines whenit's oval to show the touch area. Will let this as intent feature, cause help with the gesture when cropping something oval. If more people raise this as an issue we return to the topic. 

Thanks!


![ovalCropGuidelines](https://user-images.githubusercontent.com/15942449/110934094-7ed74d80-8325-11eb-8879-9266b904b04c.png)
