### ISSUE TITLE
How to Change icons color and crop text color? 

### ISSUE THREAD

**Issue by ahmadbajwa12315** [CanHub/Android-Image-Cropper#8]
I just need to change toolbar icon and text color according to my app theme.

**Comment by Canato** [comment]
Hey did you check this guide? [Activity-Visual-Customization](https://github.com/CanHub/Android-Image-Cropper/wiki/Activity-Visual-Customization)

If this don't work maybe this can help [Using-CropImageView-in-own-Activity](https://github.com/CanHub/Android-Image-Cropper/wiki/Using-CropImageView-in-own-Activity)

Let me know!

**Comment by ahmadbajwa12315** [comment]
![Screenshot_20201203_143107](https://user-images.githubusercontent.com/73605676/100991094-6e6c4580-3574-11eb-9e25-2a73389f4672.png)

Still icons color are white.

**Comment by Canato** [comment]
@ahmadbajwa12315 can you show the code where you are trying to change the colour? The guide give two options

**Comment by ahmadbajwa12315** [comment]
> @ahmadbajwa12315 can you show the code where you are trying to change the colour? The guide give two option
I tired the both options.

**Comment by ahmadbajwa12315** [comment]
> @ahmadbajwa12315 can you show the code where you are trying to change the colour? The guide give two options


I am using this one (Hey did you check this guide? Activity-Visual-Customization)

**Comment by Canato** [comment]
@ahmadbajwa12315 can you show the code please?

**Comment by ahmadbajwa12315** [comment]
**Style:**
```
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:textColor">@color/black</item>
        <item name="titleTextColor">@color/black</item>
        <item name="actionMenuTextColor">@color/black</item>


        <item name="android:textColorPrimary">@color/black</item>
    </style>
```

**Manifest**
```
   <activity android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
            android:theme="@style/AppTheme"/>
```

**Java**
```
           CropImage.activity(data.getData())
                    .setAllowRotation(true)
                    .setAllowFlipping(true)
                    .setAspectRatio(80, 100)
                    .start(this);
```

**Comment by Canato** [comment]
Thanks for the code, but I cannot know which resources you are using. You shared the style.
What is the value of colorPrimary? 

you can use too `setActivityMenuIconColor(ColorYouWant)` method

And please check that you are using an old library. `om.theartofdev.edmodo.cropper.CropImageActivity` is not maintaned 

check the guide about how to update https://github.com/CanHub/Android-Image-Cropper/wiki/%F0%9F%9A%A8-How-to-migrate-Android-Image-Cropper--%F0%9F%9A%A8

**Comment by ahmadbajwa12315** [comment]
> Thanks for the code, but I cannot know which resources you are using. You shared the style.
> What is the value of colorPrimary?
> 
> you can use too `setActivityMenuIconColor(ColorYouWant)` method
> 
> And please check that you are using an old library. `om.theartofdev.edmodo.cropper.CropImageActivity` is not maintaned
> 
> check the guide about how to update https://github.com/CanHub/Android-Image-Cropper/wiki/%F0%9F%9A%A8-How-to-migrate-Android-Image-Cropper--%F0%9F%9A%A8


now I understand, I was using old library.
