### ISSUE TITLE
[BUG] - ActionMode is truncate. Please don't used non released dependencies

### ISSUE THREAD

**Issue by cmoijulien** [CanHub/Android-Image-Cropper#85]
- Lib Version 2.2.1
 
**Describe the bug**

My action mode is truncate. This is due to a bug in the dependency of appcompat.
Please don't used non released dependencies to solve this issue.

Current lib dependencies version :

androidXAppCompatVersion = '1.3.0-beta01'

**My workaround :**
```
 implementation ('com.github.CanHub:Android-Image-Cropper:2.2.1'){
        exclude group: 'androidx.appcompat'
}

```
**Screenshots**
![Screenshot_20210312_101507](https://user-images.githubusercontent.com/858465/110922142-a0cdd180-831f-11eb-9c04-a934342f7e2b.jpg)

**Smartphone (please complete the following information):**
 - Device: Honor 10
 - OS: Android 10 API 29

**Comment by Canato** [comment]
Sorry for the issue @cmoijulien we need to use this because of the new permissions Google/Android released, where we have different behaviours for OS under 9, OS 10 and OS 11.

Is on my plans to remove the permissions request from the library, passing to the user of the lib, but is a future work to be done!

Thanks for finding the problem and posting a workaround until we get there

**Comment by Canato** [comment]
Could you just double confirm if material version is a issue here? cause this should not be in the library gradle. Only the appcompat version

**Comment by cmoijulien** [comment]
No it's only appcompat version. I updated the report

**Comment by cmoijulien** [comment]
> Could you just double confirm if material version is a issue here? cause this should not be in the library gradle. Only the appcompat version

No it's only appcompat version. I updated the report

**Comment by Canato** [comment]
@cmoijulien just release a new version `2.2.2` where the library is using `appCompat` last stable version.

Will close the ticket, but let me know if is not fixed.
