### ISSUE TITLE
'android.os.AsyncTask' is deprecated

### ISSUE THREAD

**Issue by Prabha10cs** [CanHub/Android-Image-Cropper#9]

**Comment by Canato** [comment]
indeed, hopefully we can update this soon

**Comment by Canato** [comment]
Just to be clear with who will help. Let's use **Coroutines**

**Comment by SanjayDevTech** [comment]
@Canato Can I work on this issue? Could you assign it to me?

**Comment by Canato** [comment]
Yes @SanjayDevTech will add you to the team, so I can assign to you, please keep us update ^^

**Comment by SanjayDevTech** [comment]
@Canato sure... I will commit the changes to my forked repository...

**Comment by Canato** [comment]
@SanjayDevTech please use Coroutines as much you can =)

**Comment by SanjayDevTech** [comment]
This is my plan @Canato :
1) Migrate some code to Kotlin (Just to implement Coroutine)
2) Replace AsyncTask with Coroutines
3) Refactoring CropImageView to use new Coroutine class 😃

**Comment by Canato** [comment]
> This is my plan @Canato :
> 
> 1. Migrate some code to Kotlin (Just to implement Coroutine)
> 2. Replace AsyncTask with Coroutines
> 3. Refactoring CropImageView to use new Coroutine class 😃

 Perfect! can we do this in 3 PRs to make faster to review?

**Comment by SanjayDevTech** [comment]
@Canato I have done 50% of migration
It is saying me to wait for your approval

**Comment by Canato** [comment]
@SanjayDevTech Please open a PR so I can review and approve

**Comment by SanjayDevTech** [comment]
@Canato Opened : )

**Comment by SanjayDevTech** [comment]
@Canato Final PR is opened : )

**Comment by SanjayDevTech** [comment]
@Canato ChangeLog and Readme updated
