### ISSUE TITLE
Access CropWindowHandler from view

### ISSUE THREAD

**Issue by omkar-tenkale** [CanHub/Android-Image-Cropper#96]
I had this special requirement 
We need to get the 4 ratios, Top left right bottom 
of the selected rect and original rect

For this purpose i need to access the CropWindowHandler 
variable which is private 

Can it be made public or a getter method?

**Comment by Canato** [comment]
No issue! Please open a PR with a getter method and let's have it =D

Follow the [guide](https://github.com/CanHub/Android-Image-Cropper/blob/main/CONTRIBUTING.md#doing-some-code)

And if possible, please add the case in one of the sample codes we have ^^

**Comment by omkar-tenkale** [comment]
I haven't used this lib yet
Was planning to move from https://github.com/igreenwood/SimpleCropView to this one

But looked into code to find it doesn't provide access to rect like that library

> mCropView.getActualCropRect()

Unable to do PR as code is in kotlin != java ;[

Can you do it this time?

**Comment by Canato** [comment]
> I haven't used this lib yet
> Was planning to move from https://github.com/igreenwood/SimpleCropView to this one for the zoom feature
> 
> But looked into code to find it doesn't provide access to rect like that library
> 
> > mCropView.getActualCropRect()
> 
> Unable to do PR as code is in kotlin != java ;[
> 
> Can you do it this time?

We can make Java static. I will put on my todo list, sadly this is not priority until more people ask for this =/

I will tag as help wanted, maybe someone can jump in a do this if they need to ^^
